select count(1) as total from
(
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE T1
WHERE CD_LOTE = 2014091801
  AND CD_TP_OPER = 6
  AND CD_TP_PESSOA = 'F'
  AND DT_PRIM_VCTO_CONTRATO IS NOT NULL
  AND DT_LIQUID IS NOT NULL
  AND QT_MES_CONTT IS NOT NULL
  AND  DATEDIFF(month,DT_LIQUID,DATEADD(month,(QT_MES_CONTT-1),DT_PRIM_VCTO_CONTRATO)) >
            (SELECT VL_PARAM FROM TB_REGRA_PARAMETRO WHERE CD_REGRA  = 93 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_QMes_PrazoCurto')            
  AND EXISTS
    (SELECT 1 FROM TB_PERFIL_INFORMACAO P
     WHERE CD_IDENTF_PERFIL = 19
       AND CD_VARIAVEL_PRIMEIRA = T1.CD_DOC_IDENTF_CLIE
       AND CD_VARIAVEL_SEGUNDA  = T1.CD_TP_IDENTF_CLIE
       HAVING COUNT(*) > (SELECT VL_PARAM FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 93 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_QtdContratoPF')     
      )      
UNION    
             
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO FROM TB_TRANS_ANLSE T1
WHERE CD_LOTE = 2014091801
  AND CD_TP_OPER = 6
  AND CD_TP_PESSOA = 'J'
  AND DT_PRIM_VCTO_CONTRATO IS NOT NULL
  AND DT_LIQUID IS NOT NULL
  AND QT_MES_CONTT IS NOT NULL
  AND  DATEDIFF(month,DT_LIQUID,DATEADD(month,(QT_MES_CONTT-1),DT_PRIM_VCTO_CONTRATO)) >
            (SELECT VL_PARAM FROM TB_REGRA_PARAMETRO WHERE CD_REGRA  = 93 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_QMes_PrazoCurto')
  AND EXISTS
    (SELECT 1 FROM TB_PERFIL_INFORMACAO P
     WHERE CD_IDENTF_PERFIL = 19
       AND CD_VARIAVEL_PRIMEIRA = T1.CD_DOC_IDENTF_CLIE
       AND CD_VARIAVEL_SEGUNDA  = T1.CD_TP_IDENTF_CLIE
       HAVING COUNT(*) > (SELECT VL_PARAM FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 93 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_QtdContratoPJ')     
      )             
) s; 
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 93