SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 73 - Investimentos significativos em produtos de baixa rentabilidade e liquidez |' ||   
'Objetivo: C) Investimentos significativos em produtos de baixa rentabilidade e liquidez. C.C. Bacen n.3.542/2012, Art. 1º, Inciso V |' ||   
'Conclusão: Investimentos significativos em produtos de baixa rentabilidade e liquidez |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||  
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' || 
'Produto: ' || T.CD_PRODUTO || COALESCE((SELECT '-' || NM_PRODUTO FROM TB_PRODUTO WHERE CD_PRODUTO = T.CD_PRODUTO), 'Produto não cadastrado') || '|' || 
'Parâmetro valor mínimo para Pessoa Física (pm_ValorMinimoPF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  || 
'Baixa Rentabilidade: Sim |' ||  
'Baixa Liquidez: Sim |'  
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T INNER JOIN TB_PRODUTO P ON T.CD_PRODUTO = P.CD_PRODUTO 
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote   
  AND T.CD_TP_PESSOA = 'F'  
  AND T.CD_TP_OPER = 1 
  AND T.VL_OPER IS NOT NULL 
  AND T.VL_OPER >= (:pm_ValorMinimoPF) 
  AND P.FL_BX_RENTABILIDADE = 1 
  AND P.FL_BX_LIQUIDEZ = 1 
UNION ALL  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 73 - Investimentos significativos em produtos de baixa rentabilidade e liquidez |' ||   
'Objetivo: C) Investimentos significativos em produtos de baixa rentabilidade e liquidez. C.C. Bacen n.3.542/2012, Art. 1º, Inciso V |' ||   
'Conclusão: Investimentos significativos em produtos de baixa rentabilidade e liquidez |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||   
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||  
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' || 
'Produto: ' || T.CD_PRODUTO || COALESCE((SELECT '-' || NM_PRODUTO FROM TB_PRODUTO WHERE CD_PRODUTO = T.CD_PRODUTO), 'Produto não cadastrado') || '|' || 
'Parâmetro valor mínimo para Pessoa Jurídica (pm_ValorMinimoPJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  || 
'Baixa Rentabilidade: Sim |' || 
'Baixa Liquidez: Sim |' 
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T INNER JOIN TB_PRODUTO P ON T.CD_PRODUTO = P.CD_PRODUTO 
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote   
  AND T.CD_TP_PESSOA = 'J'  
  AND T.CD_TP_OPER = 1 
  AND T.VL_OPER IS NOT NULL 
  AND T.VL_OPER >= (:pm_ValorMinimoPJ) 
  AND P.FL_BX_RENTABILIDADE = 1 
  AND P.FL_BX_LIQUIDEZ = 1
  
  