SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,     
'Análise: Regra 91 - Solicitação de concessão de crédito incompatível com a capacidade econômica |' ||   
'Objetivo: B) Solicitação de concessão de crédito no País incompatível com a atividade econômica ou com a capacidade financeira do cliente. C.C. Bacen n.3.542/2012, Art. 1º, Inciso VII |' ||   
'Conclusão: Solicitação de concessão de crédito no País incompatível com a atividade econômica ou com a capacidade financeira do cliente |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Natureza da Transação: ' ||  
CASE T.CD_NATUR_OPER 
	 WHEN 1 THEN 'Crédito' 
	 WHEN 2 THEN 'Débito' 
	 WHEN 3 THEN 'Evento' 
	 ELSE 'Natureza não cadastrada' 
END || '|' || 
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT ' - ' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), ' - Tipo não cadastrado') || '|' || 
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT ' - ' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), ' - Forma não cadastrada') || '|' || 
'Valor Renda: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||  
'Ocupação: ' || COALESCE((SELECT NM_OCUP FROM TB_OCUP WHERE M.CD_OCUP = CD_OCUP),'Ocupação não cadastrada') || '|' || 
'Valor médio mensal de crédito por ocupação: ' || COALESCE(TO_CHAR(M.VL_MED_CREDITO, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||  
'Parâmetro que indica o valor mínimo para disparo da regra para Pessoa Física (pm_ValorMinimoPF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' || 
'Parâmetro percentual de flexibilização da renda do cliente (pm_PercRenda): ' || COALESCE((SELECT TO_CHAR(:pm_PercRenda, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' || 
'Parâmetro percentual de flexibilização da média mensal de crédito da ocupação (pm_PercOcupacao): ' || COALESCE((SELECT TO_CHAR(:pm_PercOcupacao, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T INNER JOIN TB_CLIE_RENDA C  
ON T.CD_DOC_IDENTF_CLIE = C.CD_DOC_IDENTF_CLIE AND T.CD_TP_IDENTF_CLIE = C.CD_TP_IDENTF_CLIE  
INNER JOIN TB_MED_OCUP M ON C.CD_OCUP = M.CD_OCUP 
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote   
  AND T.CD_TP_PESSOA = 'F'   
  AND T.CD_NATUR_OPER = 1 
  AND T.CD_FORMA_OPER = 6 
  AND T.VL_OPER IS NOT NULL 
  AND T.VL_OPER > (:pm_ValorMinimoPF) 
  AND ((T.VL_RENDA_FAT IS NOT NULL AND 
        T.VL_OPER > (T.VL_RENDA_FAT * (:pm_PercRenda/100))) 
       OR 
       (M.VL_MED_CREDITO IS NOT NULL AND 
        T.VL_OPER > (M.VL_MED_CREDITO * (:pm_PercOcupacao/100)) 
       ) 
       OR 
       T.VL_RENDA_FAT IS NULL 
      ) 
UNION ALL  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,     
'Análise: Regra 91 - Solicitação de concessão de crédito incompatível com a capacidade econômica |' ||   
'Objetivo: B) Solicitação de concessão de crédito no País incompatível com a atividade econômica ou com a capacidade financeira do cliente. C.C. Bacen n.3.542/2012, Art. 1º, Inciso VII |' ||   
'Conclusão: Solicitação de concessão de crédito no País incompatível com a atividade econômica ou com a capacidade financeira do cliente |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||     
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Natureza da Transação: ' ||  
CASE T.CD_NATUR_OPER 
	 WHEN 1 THEN 'Crédito' 
	 WHEN 2 THEN 'Débito' 
	 WHEN 3 THEN 'Evento' 
	 ELSE 'Natureza não cadastrada' 
END || '|' || 
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT ' - ' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), ' - Tipo não cadastrado') || '|' || 
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT ' - ' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), ' - Forma não cadastrada') || '|' || 
'Valor Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||  
'Ramo de Atividade: ' || COALESCE((SELECT TO_CHAR(NM_RAMO_ATIVID) FROM TB_RAMO_ATIVID WHERE T.CD_RAMO_ATIVID = CD_RAMO_ATIVID),'Ramo de Atividade não cadastrado') || '|' || 
'Valor médio mensal de crédito por ramo de atividade: ' || COALESCE(TO_CHAR(R.VL_MED_CREDITO, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||  
'Parâmetro que indica o valor mínimo para disparo da regra para Pessoa Jurídica (pm_ValorMinimoPJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' || 
'Parâmetro percentual de flexibilização do faturamento (pm_PercFaturamento): ' || COALESCE((SELECT TO_CHAR(:pm_PercFaturamento, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' || 
'Parâmetro percentual de flexibilização da média mensal de crédito do ramo de atividade (pm_PercRamoAtividade): ' || COALESCE((SELECT TO_CHAR(:pm_PercRamoAtividade, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T INNER JOIN TB_MED_RAMO_ATIVID R ON T.CD_RAMO_ATIVID  = R.CD_RAMO_ATIVID 
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote   
  AND T.CD_TP_PESSOA = 'J'   
  AND T.CD_NATUR_OPER = 1 
  AND T.CD_FORMA_OPER = 6  
  AND T.VL_OPER IS NOT NULL 
  AND T.VL_OPER > (:pm_ValorMinimoPJ) 
  AND ((T.VL_RENDA_FAT IS NOT NULL AND 
        T.VL_OPER > (T.VL_RENDA_FAT * (:pm_PercFaturamento/100))) 
       OR 
       (R.VL_MED_CREDITO IS NOT NULL AND 
        T.VL_OPER > (R.VL_MED_CREDITO * (:pm_PercRamoAtividade/100)) 
       ) 
       OR 
       T.VL_RENDA_FAT IS NULL 
      )
      
      