/* a) Movimentação de recursos em espécie em moeda estrangeira ou cheques de viagem, */  
/* que apresente atipicidade em relação a atividade econômica do cliente ou incompatibilidade */  
/* com a sua capacidade econômico-financeira;*/  
  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 30 - Movimentação em espécie em moeda estrangeira ou cheque de viagem |' ||   
'Objetivo: a) Movimentação de recursos em espécie em moeda estrangeira ou cheques de viagem, que apresente atipicidade em relação à atividade econômica do cliente ou incompatibilidade com a sua capacidade econômico-financeira. C.C. Bacen n.3.542/2012, Art. 1º, Inciso II |' ||   
'Conclusão: Cliente movimentou recursos em espécie em moeda estrangeira ou cheques de viagem, apresentando atipicidade em relação à sua atividade econômica ou incompatibilidade com a sua capacidade econômico-financeira |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||   
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||   
'Valor Renda: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||    
'Parâmetro percentual de flexibilização da renda do cliente (pm_PercRenda): ' || COALESCE((SELECT TO_CHAR(:pm_PercRenda, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro de valor mínimo para operação com moeda estrangeira. Somente Pessoa Física (pm_ValorMinimo_PF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimo_PF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'     
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T   
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote    
  AND T.CD_TP_PESSOA = 'F'   
  AND T.CD_FORMA_OPER = 8   
  AND T.VL_OPER IS NOT NULL   
  AND T.VL_OPER > (:pm_ValorMinimo_PF)   
  AND ((T.VL_RENDA_FAT IS NOT NULL AND   
        T.VL_OPER > (T.VL_RENDA_FAT * (:pm_PercRenda/100)))   
        OR   
        T.VL_RENDA_FAT IS NULL   
        )   
UNION      
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 30 - Movimentação em espécie em moeda estrangeira ou cheque de viagem |' ||   
'Objetivo: a) Movimentação de recursos em espécie em moeda estrangeira ou cheques de viagem, que apresente atipicidade em relação à atividade econômica do cliente ou incompatibilidade com a sua capacidade econômico-financeira. C.C. Bacen n.3.542/2012, Art. 1º, Inciso II |' ||   
'Conclusão: Cliente movimentou recursos em espécie em moeda estrangeira ou cheques de viagem, apresentando atipicidade em relação à sua atividade econômica ou incompatibilidade com a sua capacidade econômico-financeira |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||   
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||   
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||   
'Ocupação: ' || COALESCE((SELECT LISTAGG(O.NM_OCUP, ' / ') WITHIN GROUP (ORDER BY O.CD_OCUP desc)  
                          FROM TB_OCUP O, TB_CLIE_RENDA C   
                          WHERE T.CD_DOC_IDENTF_CLIE = C.CD_DOC_IDENTF_CLIE   
                          AND T.CD_TP_IDENTF_CLIE  = C.CD_TP_IDENTF_CLIE   
                          AND C.CD_OCUP            = O.CD_OCUP), 'Não cadastrado') || '|' ||   
'Valor Médio de Crédito da Ocupação: ' || COALESCE((SELECT LISTAGG(TO_CHAR(M.VL_MED_CREDITO, 'L999G999G999G990D99'), ' / ') WITHIN GROUP (ORDER BY C.CD_OCUP desc)  
                                                    FROM TB_MED_OCUP M, TB_CLIE_RENDA C   
                                                    WHERE T.CD_DOC_IDENTF_CLIE = C.CD_DOC_IDENTF_CLIE   
                                                    AND T.CD_TP_IDENTF_CLIE  = C.CD_TP_IDENTF_CLIE   
                                                    AND C.CD_OCUP            = M.CD_OCUP), 'Valor não cadastrado') || '|' ||   
'Parâmetro percentual de flexibilização da média mensal de crédito da ocupação (pm_PercOcupacao): ' || COALESCE((SELECT TO_CHAR(:pm_PercOcupacao, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||   
'Parâmetro de valor mínimo para operação com moeda estrangeira. Somente Pessoa Física (pm_ValorMinimo_PF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimo_PF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'     
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T, TB_CLIE_RENDA R, TB_MED_OCUP M   
WHERE  T.CD_LOTE    = :cd_lote    
   AND T.CD_SUBLOTE = :cd_sublote   
   AND T.CD_TP_PESSOA = 'F'   
   AND T.CD_FORMA_OPER = 8   
   AND T.VL_OPER IS NOT NULL   
   AND T.VL_OPER > (:pm_ValorMinimo_PF)   
   AND T.CD_DOC_IDENTF_CLIE = R.CD_DOC_IDENTF_CLIE   
   AND T.CD_TP_IDENTF_CLIE = R.CD_TP_IDENTF_CLIE   
   AND R.CD_OCUP = M.CD_OCUP   
   AND T.VL_OPER > (M.VL_MED_CREDITO * (:pm_PercOcupacao/100) )     
UNION   
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 30 - Movimentação em espécie em moeda estrangeira ou cheque de viagem |' ||   
'Objetivo: a) Movimentação de recursos em espécie em moeda estrangeira ou cheques de viagem, que apresente atipicidade em relação à atividade econômica do cliente ou incompatibilidade com a sua capacidade econômico-financeira. C.C. Bacen n.3.542/2012, Art. 1º, Inciso II |' ||   
'Conclusão: Cliente movimentou recursos em espécie em moeda estrangeira ou cheques de viagem, apresentando atipicidade em relação à sua atividade econômica ou incompatibilidade com a sua capacidade econômico-financeira |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||   
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||   
'Valor Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||    
'Parâmetro percentual de flexibilização do faturamento (pm_PercFatmt): ' || COALESCE((SELECT TO_CHAR(:pm_PercFatmt, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro de valor mínimo para operação com moeda estrangeira. Somente Pessoa Jurídica (pm_ValorMinimo_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimo_PJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'     
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T   
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote   
  AND T.CD_TP_PESSOA = 'J'   
  AND T.CD_FORMA_OPER = 8   
  AND T.VL_OPER IS NOT NULL   
  AND T.VL_OPER > (:pm_ValorMinimo_PJ)   
  AND ((T.VL_RENDA_FAT IS NOT NULL   
       AND T.VL_OPER > (T.VL_RENDA_FAT * (:pm_PercFatmt/100)))   
       OR    
       T.VL_RENDA_FAT IS NULL)   
UNION         
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 30 - Movimentação em espécie em moeda estrangeira ou cheque de viagem |' ||   
'Objetivo: a) Movimentação de recursos em espécie em moeda estrangeira ou cheques de viagem, que apresente atipicidade em relação à atividade econômica do cliente ou incompatibilidade com a sua capacidade econômico-financeira. C.C. Bacen n.3.542/2012, Art. 1º, Inciso II |' ||   
'Conclusão: Cliente movimentou recursos em espécie em moeda estrangeira ou cheques de viagem, apresentando atipicidade em relação à sua atividade econômica ou incompatibilidade com a sua capacidade econômico-financeira |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||   
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||   
'Ramo de Atividade: ' || COALESCE((SELECT TO_CHAR(NM_RAMO_ATIVID) FROM TB_RAMO_ATIVID   
                                   WHERE T.CD_RAMO_ATIVID = CD_RAMO_ATIVID),'Ramo de Atividade não cadastrado') || '|' ||   
'Valor Médio de Crédito do Ramo de Atividade: ' || COALESCE((SELECT TO_CHAR(M.VL_MED_CREDITO, 'L999G999G999G990D99') FROM TB_MED_RAMO_ATIVID M   
                                                             WHERE T.CD_RAMO_ATIVID = M.CD_RAMO_ATIVID),'Valor não cadastrado.') || '|' ||   
'Parâmetro percentual de flexibilização da média mensal de crédito por Ramo de Atividade (pm_PercRamoAtividade): ' || COALESCE((SELECT TO_CHAR(:pm_PercRamoAtividade, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||   
'Parâmetro de valor mínimo para operação com moeda estrangeira. Somente Pessoa Jurídica (pm_ValorMinimo_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimo_PJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'     
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T, TB_MED_RAMO_ATIVID M    
WHERE  T.CD_LOTE = :cd_lote    
   AND T.CD_SUBLOTE = :cd_sublote   
   AND T.CD_TP_PESSOA = 'J'   
   AND T.CD_FORMA_OPER = 8   
   AND T.VL_OPER IS NOT NULL   
   AND T.VL_OPER > (:pm_ValorMinimo_PJ)   
   AND T.CD_RAMO_ATIVID = M.CD_RAMO_ATIVID   
   AND T.VL_OPER > (M.VL_MED_CREDITO * (:pm_PercRamoAtividade/100) )   
     
     
     