SELECT T1.DT_APONTAMENTO, T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE,      
'Análise: Regra 24 - Depósito em Espécie, de forma parcelada |' ||     
'Objetivo: e) Realização de depósitos de grandes valores em espécie, de forma parcelada, especialmente em regiões geográficas de maior risco, principalmente nos mesmos caixas ou terminais de auto-atendimento próximos, destinados a uma única conta ou a várias contas em municípios ou agências distintas. C.C. Bacen n.3.542/2012, Art. 1º, Inciso I |' ||     
'Conclusão: Cliente realizou depósitos de grandes valores em espécie, de forma parcelada, em regiões de risco, destinados a uma única conta ou a várias agências distintas |' ||     
'Cliente: ' ||  MAX(T1.NM_CLIE) || '|' ||   
CASE T2.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T2.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T2.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||    
'Lote: ' || TO_CHAR(T1.CD_LOTE) || '|' ||   
'Período de consolidação: de ' || TO_CHAR((max(T1.DT_FIM)  - (:pm_QtdeDiaRecuo)),'DD/MM/YYYY') ||     
' até ' || TO_CHAR(max(T1.DT_FIM), 'DD/MM/YYYY') || '|' ||   
'Valor da Total de crédito em espécie: ' || TO_CHAR(sum(T2.VL_OPER), 'L999G999G999G990D99') || '|' ||     
'Quantidade de depósitos em espécie: ' || TO_CHAR(COUNT(*)) || '|' ||  
'Banco Cliente: ' || COALESCE(TO_CHAR(T2.CD_BANCO,'000'), 'Banco não cadastrado') || '|' ||     
'Agência Cliente: ' || COALESCE((SELECT TO_CHAR(CD_AG,'0000') || '-' || NM_AG FROM TB_AGENCIA WHERE CD_AG = T2.CD_AG), 'Agência não cadastrada') || '|' ||     
'Conta Cliente: ' || COALESCE(TO_CHAR(T2.CD_CTA,'0000000000'), 'Conta não cadastrada') || '|' ||     
'Agências onde os créditos foram realizados: ' || LISTAGG(TO_CHAR(T2.CD_AG_DESTORIG,'0000'), '/ ') WITHIN GROUP (ORDER BY T2.CD_CTA desc) || '|' ||   
'Parâmetro de quantidade de dias de Recuo para análise das transferências realizadas (pm_QtdeDiaRecuo): ' || COALESCE((SELECT TO_CHAR(:pm_QtdeDiaRecuo, '999999990') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro de comparação para valores expressivos de depósito em espécie para PF (pm_ValorAltoDepEspeciePF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorAltoDepEspeciePF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'     
AS DS_INF_ANLSE     
FROM TB_TRANS T2  
INNER JOIN VM_CLIE T1 ON T2.CD_DOC_IDENTF_CLIE = T1.CD_DOC_IDENTF_CLIE AND T2.CD_TP_IDENTF_CLIE = T1.CD_TP_IDENTF_CLIE AND T1.CD_TP_PESSOA = 'F'   
WHERE T2.DT_TRANS <  T1.DT_FIM     
  AND T2.DT_TRANS >= (T1.DT_FIM  - (:pm_QtdeDiaRecuo))     
  AND T2.CD_TP_PESSOA       = 'F'     
  AND T2.CD_NATUR_OPER      = 1     
  AND T2.CD_TP_OPER         = 4     
  AND T2.CD_FORMA_OPER      = 7     
  AND T2.FL_ANALISADO       = 1  
  AND T2.CD_BANCO IS NOT NULL  
  AND T2.CD_AG    IS NOT NULL  
  AND T2.CD_CTA   IS NOT NULL  
  AND T2.CD_AG_DESTORIG IS NOT NULL  
  AND EXISTS (SELECT 1 FROM TB_AGENCIA WHERE CD_AG = T2.CD_AG_DESTORIG AND FL_REG_CRIME = 1)     
  AND T2.FL_ANALISADO  = 1    
GROUP BY T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE, T2.CD_BANCO, T2.CD_AG, T2.CD_CTA, T1.CD_LOTE, T1.DT_APONTAMENTO   
HAVING SUM(T2.VL_OPER) > (:pm_ValorAltoDepEspeciePF)  
   
  
UNION ALL  
SELECT T1.DT_APONTAMENTO, T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE,      
'Análise: Regra 24 - Depósito em Espécie, de forma parcelada |' ||     
'Objetivo: e) Realização de depósitos de grandes valores em espécie, de forma parcelada, especialmente em regiões geográficas de maior risco, principalmente nos mesmos caixas ou terminais de auto-atendimento próximos, destinados a uma única conta ou a várias contas em municípios ou agências distintas. C.C. Bacen n.3.542/2012, Art. 1º, Inciso I |' ||     
'Conclusão: Cliente realizou depósitos de grandes valores em espécie, de forma parcelada, em regiões de risco, destinados a uma única conta ou a várias agências distintas |' ||     
'Cliente: ' ||  MAX(T1.NM_CLIE) || '|' ||   
CASE T2.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T2.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T2.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||    
'Lote: ' || TO_CHAR(T1.CD_LOTE) || '|' ||   
'Período de consolidação: de ' || TO_CHAR((max(T1.DT_FIM)  - (:pm_QtdeDiaRecuo)),'DD/MM/YYYY') ||   
' até ' || TO_CHAR(max(T1.DT_FIM), 'DD/MM/YYYY') || '|' ||   
'Valor da Total de crédito em espécie: ' || TO_CHAR(sum(T2.VL_OPER), 'L999G999G999G990D99') || '|' ||     
'Quantidade de depósitos em espécie: ' || TO_CHAR(COUNT(*)) || '|' ||  
'Banco Cliente: ' || COALESCE(TO_CHAR(T2.CD_BANCO,'000'), 'Banco não cadastrado') || '|' ||     
'Agência Cliente: ' || COALESCE((SELECT TO_CHAR(CD_AG,'0000') || '-' || NM_AG FROM TB_AGENCIA WHERE CD_AG = T2.CD_AG), 'Agência não cadastrada') || '|' ||     
'Conta Cliente: ' || COALESCE(TO_CHAR(T2.CD_CTA,'0000000000'), 'Conta não cadastrada') || '|' ||     
'Agências onde os créditos foram realizados: ' || LISTAGG(TO_CHAR(T2.CD_AG_DESTORIG,'0000000000'), '/ ') WITHIN GROUP (ORDER BY T2.CD_CTA desc) || '|' ||   
'Parâmetro de quantidade de dias de Recuo para análise das transferências realizadas (pm_QtdeDiaRecuo): ' || COALESCE((SELECT TO_CHAR(:pm_QtdeDiaRecuo, 'L999G999G990') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro de comparação para valores expressivos de depósito em espécie para PJ (pm_ValorAltoDepEspeciePJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorAltoDepEspeciePJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'     
AS DS_INF_ANLSE     
FROM TB_TRANS T2  
INNER JOIN VM_CLIE T1 ON T2.CD_DOC_IDENTF_CLIE = T1.CD_DOC_IDENTF_CLIE AND T2.CD_TP_IDENTF_CLIE = T1.CD_TP_IDENTF_CLIE AND T1.CD_TP_PESSOA = 'J'   
WHERE T2.DT_TRANS <  T1.DT_FIM     
  AND T2.DT_TRANS   >= (T1.DT_FIM  - (:pm_QtdeDiaRecuo))     
  AND T2.CD_TP_PESSOA       = 'J'     
  AND T2.CD_NATUR_OPER      = 1     
  AND T2.CD_TP_OPER         = 4     
  AND T2.CD_FORMA_OPER      = 7    
  AND T2.FL_ANALISADO       = 1   
  AND T2.CD_BANCO IS NOT NULL  
  AND T2.CD_AG    IS NOT NULL  
  AND T2.CD_CTA   IS NOT NULL  
  AND T2.CD_AG_DESTORIG IS NOT NULL  
  AND EXISTS (SELECT 1 FROM TB_AGENCIA WHERE CD_AG = T2.CD_AG_DESTORIG AND FL_REG_CRIME = 1)     
  AND T2.FL_ANALISADO  = 1    
GROUP BY T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE, T2.CD_BANCO, T2.CD_AG, T2.CD_CTA, T1.CD_LOTE, T1.DT_APONTAMENTO     
HAVING SUM(T2.VL_OPER) > (:pm_ValorAltoDepEspeciePJ)  

