SELECT T.DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 26 - Depósito em Espécie em Contas de Clientes que trabalham com valores altos |' ||   
'Objetivo: g) Realização de depósitos em espécie em contas de clientes que exerçam atividade comercial relacionada com negociação de bens de luxo ou de alto valor, tais como obras de arte, imóveis, barcos, jóias, automóveis ou aeronaves executivas. C.C. Bacen n.3.542/2012, Art. 1º, Inciso I |' ||   
'Conclusão: Depósito em espécie na conta de cliente que exerça atividade comercial relacionada com negociação de bens de luxo ou de alto valor, tais como obras de arte, imóveis, barcos, jóias, automóveis ou aeronaves executivas |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' ||  
'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
|| '|' ||   
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Natureza da Transação: Crédito |' ||    
'Tipo da Transação: Depósito |'||  
'Forma da Transação: Espécie |' ||  
'Parâmetro de valor mínimo para valor da operação. Somente Pessoa Física (pm_ValorMinimo_PF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimo_PF, 'L999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||   
'Quantidade de transações com indicação de Itens de Luxo: ' || TO_CHAR(QOCUP) || '|'  || 
'Ocupação com indicação de Itens de Luxo: ' || LISTA || '|'  
AS DS_INF_ANLSE   
FROM (SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE, T.VL_OPER, T.DT_TRANS, T.CD_AG, T.CD_CTA, CR.LISTA, CR.QOCUP 
      FROM TB_TRANS_ANLSE T   
      INNER JOIN (SELECT R.CD_DOC_IDENTF_CLIE, R.CD_TP_IDENTF_CLIE, LISTAGG(O.NM_OCUP, ', ') WITHIN GROUP (ORDER BY O.NM_OCUP desc)  LISTA, COUNT(*) QOCUP 
                  FROM TB_CLIE_RENDA R  
                  INNER JOIN TB_OCUP O ON R.CD_OCUP = O.CD_OCUP AND O.FL_OPER_ITEM_LUXO = 1 
                  WHERE EXISTS (SELECT 1 FROM TB_TRANS_ANLSE T 
                                WHERE T.CD_DOC_IDENTF_CLIE = R.CD_DOC_IDENTF_CLIE 
                                AND T.CD_TP_IDENTF_CLIE  = R.CD_TP_IDENTF_CLIE 
                                AND T.CD_LOTE = :cd_lote 
                                AND T.CD_SUBLOTE = :cd_sublote) 
                  GROUP BY R.CD_DOC_IDENTF_CLIE, R.CD_TP_IDENTF_CLIE   
                 ) CR 
      ON T.CD_DOC_IDENTF_CLIE = CR.CD_DOC_IDENTF_CLIE 
      AND T.CD_TP_IDENTF_CLIE  = CR.CD_TP_IDENTF_CLIE  
      WHERE T.CD_LOTE    = :cd_lote     
      AND T.CD_SUBLOTE = :cd_sublote    
      AND T.CD_TP_PESSOA  = 'F'   
      AND T.CD_NATUR_OPER = 1 /*credito*/   
      AND T.CD_TP_OPER    = 4 /*deposito*/   
      AND T.CD_FORMA_OPER = 7 /*especie*/    
      AND T.VL_OPER IS NOT NULL   
      AND T.VL_OPER > (:pm_ValorMinimo_PF)   
     ) T 
UNION  ALL  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 26 - Depósito em Espécie em Contas de Clientes que trabalham com valores altos |' ||   
'Objetivo: g) Realização de depósitos em espécie em contas de clientes que exerçam atividade comercial relacionada com negociação de bens de luxo ou de alto valor, tais como obras de arte, imóveis, barcos, jóias, automóveis ou aeronaves executivas. C.C. Bacen n.3.542/2012, Art. 1º, Inciso I |' ||   
'Conclusão: Depósito em espécie na conta de cliente que exerça atividade comercial relacionada com negociação de bens de luxo ou de alto valor, tais como obras de arte, imóveis, barcos, jóias, automóveis ou aeronaves executivas |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' ||  
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Natureza da Transação: ' ||    
CASE T.CD_NATUR_OPER   
	 WHEN 1 THEN 'Crédito'   
	 WHEN 2 THEN 'Débito'   
	 WHEN 3 THEN 'Evento'   
	 ELSE 'Natureza não cadastrada'   
END || '|' ||   
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||   
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||   
'Parâmetro de valor mínimo para valor da operação. Somente Pessoa Jurídica (pm_ValorMinimo_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimo_PJ, 'L999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||   
'Ramo de Atividade com indicação de Itens de Luxo: ' || COALESCE(NM_RAMO_ATIVID,'Ramo de Atividade não cadastrado') || '|'   
AS DS_INF_ANLSE   
FROM TB_TRANS_ANLSE T INNER JOIN TB_RAMO_ATIVID R   
                      ON  T.CD_RAMO_ATIVID = R.CD_RAMO_ATIVID  
WHERE T.CD_LOTE     = :cd_lote     
AND T.CD_SUBLOTE    = :cd_sublote    
AND T.CD_TP_PESSOA  = 'J'   
AND T.CD_NATUR_OPER = 1 /*credito*/   
AND T.CD_TP_OPER    = 4 /*deposito*/   
AND T.CD_FORMA_OPER = 7 /*especie*/     
AND T.VL_OPER IS NOT NULL   
AND T.VL_OPER > (:pm_ValorMinimo_PJ)     
AND R.FL_OPER_ITEM_LUXO = 1  
  