SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 71 - Compra e venda de títulos mobiliários a preços incompatíveis com o mercado |' ||   
'Objetivo: A) Operações ou conjunto de operações de compra ou de venda de títulos e valores mobiliários a preços incompatíveis com os praticados no mercado ou quando realizadas por pessoa cuja atividade declarada e perfil não se coadunem ao tipo de negociação realizada. C.C. Bacen n.3.542/2012, Art. 1º, Inciso V |' ||   
'Conclusão: Operações ou conjunto de operações de compra ou de venda de títulos e valores imobiliários a preços incompatíveis com os praticados no mercado |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||  
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' || 
'Parâmetro de comparação, que indica um valor significativo de movimentação para Pessoa Física (pm_ValorMinimoPF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  || 
'Valor Médio (Abertura/Fechamento): ' || COALESCE(TO_CHAR(((NVL(T.VL_ABERT_MERCADO, NVL(T.VL_FECHA_MERCADO,0)) + NVL(T.VL_FECHA_MERCADO,NVL(T.VL_ABERT_MERCADO,0)))/2), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||   
'Parâmetro percentual para flexibilização do valor de mercado superior (pm_PercValorMercadoSuperior_PF): ' || COALESCE((SELECT TO_CHAR(:pm_PercValorMercadoSuperior_PF, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro percentual para flexibilização do valor de mercado inferior (pm_PercValorMercadoInferior_PF): ' || COALESCE((SELECT TO_CHAR(:pm_PercValorMercadoInferior_PF, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'   
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T 
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote   
  AND T.CD_TP_PESSOA = 'F'  
  AND T.CD_TP_OPER IN (35, 36) 
  AND T.VL_OPER IS NOT NULL 
  AND T.VL_OPER >= (:pm_ValorMinimoPF) 
  AND ((NVL(T.VL_ABERT_MERCADO, NVL(T.VL_FECHA_MERCADO,0)) + NVL(T.VL_FECHA_MERCADO,NVL(T.VL_ABERT_MERCADO,0)))/2) <> 0 
  AND ((T.VL_OPER > (((NVL(T.VL_ABERT_MERCADO, NVL(T.VL_FECHA_MERCADO,0)) + NVL(T.VL_FECHA_MERCADO,NVL(T.VL_ABERT_MERCADO,0)))/2) *  
                     (SELECT :pm_PercValorMercadoSuperior_PF/100 FROM DUAL))) 
       OR 
       (T.VL_OPER < (((NVL(T.VL_ABERT_MERCADO, NVL(T.VL_FECHA_MERCADO,0)) + NVL(T.VL_FECHA_MERCADO,NVL(T.VL_ABERT_MERCADO,0)))/2) *  
                     (SELECT :pm_PercValorMercadoInferior_PF/100 FROM DUAL))) 
      ) 
UNION ALL  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 71 - Compra e venda de títulos mobiliários a preços incompatíveis com o mercado |' ||   
'Objetivo: A) Operações ou conjunto de operações de compra ou de venda de títulos e valores mobiliários a preços incompatíveis com os praticados no mercado ou quando realizadas por pessoa cuja atividade declarada e perfil não se coadunem ao tipo de negociação realizada. C.C. Bacen n.3.542/2012, Art. 1º, Inciso V |' ||   
'Conclusão: Operações ou conjunto de operações de compra ou de venda de títulos e valores imobiliários a preços incompatíveis com os praticados no mercado |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||  
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' || 
'Parâmetro de comparação, que indica um valor significativo de movimentação para Pessoa Jurídica (pm_ValorMinimoPJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  || 
'Valor Médio (Abertura/Fechamento): ' || COALESCE(TO_CHAR(((NVL(T.VL_ABERT_MERCADO, NVL(T.VL_FECHA_MERCADO,0)) + NVL(T.VL_FECHA_MERCADO,NVL(T.VL_ABERT_MERCADO,0)))/2), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||   
'Parâmetro percentual para flexibilização do valor de mercado superior (pm_PercValorMercadoSuperior_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_PercValorMercadoSuperior_PJ, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro percentual para flexibilização do valor de mercado inferior (pm_PercValorMercadoInferior_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_PercValorMercadoInferior_PJ, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'   
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T 
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote   
  AND T.CD_TP_PESSOA = 'J'  
  AND T.CD_TP_OPER IN (35, 36) 
  AND T.VL_OPER IS NOT NULL 
  AND T.VL_OPER >= (:pm_ValorMinimoPJ) 
  AND ((NVL(T.VL_ABERT_MERCADO, NVL(T.VL_FECHA_MERCADO,0)) + NVL(T.VL_FECHA_MERCADO,NVL(T.VL_ABERT_MERCADO,0)))/2) <> 0 
  AND ((T.VL_OPER > (((NVL(T.VL_ABERT_MERCADO, NVL(T.VL_FECHA_MERCADO,0)) + NVL(T.VL_FECHA_MERCADO,NVL(T.VL_ABERT_MERCADO,0)))/2) *  
                     (SELECT :pm_PercValorMercadoSuperior_PJ/100 FROM DUAL))) 
       OR 
       (T.VL_OPER < (((NVL(T.VL_ABERT_MERCADO, NVL(T.VL_FECHA_MERCADO,0)) + NVL(T.VL_FECHA_MERCADO,NVL(T.VL_ABERT_MERCADO,0)))/2) *  
                     (SELECT :pm_PercValorMercadoInferior_PJ/100 FROM DUAL))) 
      )
      
      