
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,        
to_clob('Análise: Regra 90 - Liquidação de operação de crédito, incompatível com a capacidade econômica |' ||      
'Objetivo: A) Realização de operações de crédito no País liquidadas com recursos aparentemente incompatíveis com a situação econômico-financeira do cliente. C.C. Bacen n.3.542/2012, Art. 1º, Inciso VII |' ||      
'Conclusão: Realização de operações de crédito no País liquidadas com recursos aparentemente incompatíveis com a situação econômico-financeira do cliente |' ||      
'Cliente: ' ||  T.NM_CLIE || '|' ||    
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||     
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||      
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Natureza da Transação: ' ||     
CASE T.CD_NATUR_OPER    
	 WHEN 1 THEN 'Crédito'    
	 WHEN 2 THEN 'Débito'    
	 WHEN 3 THEN 'Evento'    
	 ELSE 'Natureza não cadastrada'    
END || '|' ||    
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||    
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||    
'Contrato quitado em desacordo com o Faturamento do cliente: ' || '|' ||     
'Código do Contrato: ' || COALESCE(TO_CHAR(T.CD_CONTRATO), 'Contrato não cadastrado') || '|' ||    
'Data Liquidação do Contrato: ' || COALESCE(TO_CHAR(T.DT_LIQUID,'DD/MM/YYYY'), 'Data não cadastrada') || '|' ||    
'Valor da Parcela do Contrato: ' || COALESCE(TO_CHAR(T.VL_PCELA_CONTRATO, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|'  ||    
'Valor Renda: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||     
'Parâmetro que indica o valor mínimo para disparo da regra (pm_ValorMinimoPF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro percentual de flexibilização da renda  do cliente (pm_PercRenda): ' || COALESCE((SELECT TO_CHAR(':pm_PercRenda', '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'     
) AS DS_INF_ANLSE       
FROM TB_TRANS_ANLSE T    
WHERE T.CD_LOTE    = :cd_lote       
  AND T.CD_SUBLOTE = :cd_sublote      
  AND T.CD_TP_PESSOA = 'F'      
  AND T.CD_TP_OPER = 6    
  AND T.CD_FORMA_OPER = 6    
  AND T.CD_NATUR_OPER = 2    
  AND T.DT_LIQUID IS NOT NULL    
  AND T.CD_CONTRATO IS NOT NULL    
  AND T.VL_OPER IS NOT NULL    
  AND T.VL_OPER > (:pm_ValorMinimoPF)    
  AND T.VL_PCELA_CONTRATO IS NOT NULL    
  AND T.VL_OPER > T.VL_PCELA_CONTRATO    
  AND ((T.VL_RENDA_FAT IS NOT NULL AND    
        T.VL_OPER > (T.VL_RENDA_FAT * (:pm_PercRenda/100)))    
       OR    
       T.VL_RENDA_FAT IS NULL    
      )       
UNION ALL   
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,        
to_clob('Análise: Regra 90 - Liquidação de operação de crédito, incompatível com a capacidade econômica |' ||      
'Objetivo: A) Realização de operações de crédito no País liquidadas com recursos aparentemente incompatíveis com a situação econômico-financeira do cliente. C.C. Bacen n.3.542/2012, Art. 1º, Inciso VII |' ||      
'Conclusão: Realização de operações de crédito no País liquidadas com recursos aparentemente incompatíveis com a situação econômico-financeira do cliente |' ||      
'Cliente: ' ||  T.NM_CLIE || '|' ||    
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||      
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||      
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Natureza da Transação: ' ||     
CASE T.CD_NATUR_OPER    
	 WHEN 1 THEN 'Crédito'    
	 WHEN 2 THEN 'Débito'    
	 WHEN 3 THEN 'Evento'    
	 ELSE 'Natureza não cadastrada'    
END || '|' ||    
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||    
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||    
'Contrato quitado em desacordo com o Faturamento do cliente: ' || '|' ||    
'Código do Contrato: ' || COALESCE(TO_CHAR(T.CD_CONTRATO), 'Contrato não cadastrado') || '|' ||    
'Data Liquidação do Contrato: ' || COALESCE(TO_CHAR(T.DT_LIQUID,'DD/MM/YYYY'), 'Data não cadastrada') || '|' ||    
'Valor da Parcela do Contrato: ' || COALESCE(TO_CHAR(T.VL_PCELA_CONTRATO, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|'  ||    
'Valor Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||     
'Parâmetro que indica o valor mínimo para disparo da regra (pm_ValorMinimoPJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro percentual de flexibilização do faturamento do cliente (pm_PercFaturamento): ' || COALESCE((SELECT TO_CHAR(:pm_PercFaturamento, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'     
) AS DS_INF_ANLSE       
FROM TB_TRANS_ANLSE T    
WHERE T.CD_LOTE    = :cd_lote        
  AND T.CD_SUBLOTE = :cd_sublote      
  AND T.CD_TP_PESSOA = 'J'      
  AND T.CD_TP_OPER = 6    
  AND T.CD_FORMA_OPER = 6    
  AND T.CD_NATUR_OPER = 2    
  AND T.DT_LIQUID IS NOT NULL    
  AND T.CD_CONTRATO IS NOT NULL    
  AND T.VL_OPER IS NOT NULL    
  AND T.VL_OPER > (:pm_ValorMinimoPJ)    
  AND T.VL_PCELA_CONTRATO IS NOT NULL    
  AND T.VL_OPER > T.VL_PCELA_CONTRATO    
  AND ((T.VL_RENDA_FAT IS NOT NULL AND    
        T.VL_OPER > (T.VL_RENDA_FAT * (:pm_PercFaturamento/100)))    
       OR    
       T.VL_RENDA_FAT IS NULL    
      )    
   
UNION ALL   
   
SELECT T1.DT_APONTAMENTO, T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE,        
'Análise: Regra 90 - Liquidação de operação de crédito, incompatível com a capacidade econômica |' ||      
'Objetivo: A) Realização de operações de crédito no País liquidadas com recursos aparentemente incompatíveis com a situação econômico-financeira do cliente. C.C. Bacen n.3.542/2012, Art. 1º, Inciso VII |' ||      
'Conclusão: Realização de operações de crédito no País liquidadas com recursos aparentemente incompatíveis com a situação econômico-financeira do cliente |' ||      
'Cliente: ' ||  MAX(T2.NM_CLIE) || '|' ||    
CASE T2.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T2.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T2.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||  
'Lote: ' || TO_CHAR(:cd_lote) || '|' ||       
'Valor Renda: ' || COALESCE(TO_CHAR(MAX(T1.VL_RENDA_FAT), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||     
'Contrato quitado onde, recentemente, ocorreram outros pagamentos para esse mesmo contrato:' || '|' ||     
'Período: de ' || TO_CHAR((MAX(T1.DT_REF) - (:pm_QtdeDiasRecuo)), 'DD/MM/YYYY')    
              || ' até ' || TO_CHAR(MAX(T1.DT_REF), 'DD/MM/YYYY') || '|' ||    
'Número do Contrato: ' || COALESCE(TO_CHAR(T2.CD_CONTRATO), 'Contrato não cadastrado') || '|' ||    
'Data Liquidação do Contrato: ' || COALESCE(TO_CHAR(MAX(T1.DT_LIQUID),'DD/MM/YYYY'), 'Data não cadastrada') || '|' ||    
'Data da Transação pagamento: ' || TO_CHAR(MAX(T1.DT_REF),'DD/MM/YYYY') || '|' ||      
'Valor da Transação de pagamento: ' || TO_CHAR(MAX(T1.VL_OPER), 'L999G999G999G990D99') || '|'  ||      
'Total de pagamentos recentes do contrato: ' || TO_CHAR(sum(T2.VL_OPER), 'L999G999G999G990D99') || '|' ||    
'Pagamentos considerados: detalhes' || '|' ||    
xmlcast(  xmlagg(xmlelement(outros,    
TO_CHAR(T2.DT_TRANS, 'DD/MM/YY') || ':' || ltrim(TO_CHAR(T2.VL_OPER, 'L999G999G999G990D99'))    
|| '|')     
order by T2.CD_DOC_IDENTF_CLIE) as clob)   
|| '|' ||    
'Parâmetro que indica o valor mínimo do Somatório para disparo da regra (pm_ValorMinimoSomatorioPF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoSomatorioPF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro percentual de flexibilização da renda  do cliente (pm_PercRenda): ' || COALESCE((SELECT TO_CHAR(:pm_PercRenda, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro que indica a quantidade de dias de recuo (pm_QtdeDiasRecuo): ' || COALESCE((':pm_QtdeDiasRecuo'),'Parâmetro não cadastrado') || '|'    
AS DS_INF_ANLSE       
FROM TB_TRANS T2    
INNER JOIN (SELECT LAST_DAY(TRUNC(DT_TRANS)) DT_APONTAMENTO, CD_TRANSACAO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_CONTRATO,DT_LIQUID, DT_TRANS DT_REF, VL_RENDA_FAT, VL_OPER        
            FROM TB_TRANS_ANLSE    
            WHERE CD_LOTE  = :cd_lote       
            AND CD_SUBLOTE = :cd_sublote    
            AND CD_TP_PESSOA = 'F'      
            AND CD_TP_OPER = 6    
            AND CD_FORMA_OPER = 6    
            AND CD_NATUR_OPER = 2    
            AND DT_LIQUID IS NOT NULL    
            AND CD_CONTRATO IS NOT NULL    
            AND VL_OPER IS NOT NULL    
            ) T1   
     ON T2.CD_DOC_IDENTF_CLIE = T1.CD_DOC_IDENTF_CLIE AND T2.CD_TP_IDENTF_CLIE = T1.CD_TP_IDENTF_CLIE AND T2.CD_CONTRATO = T1.CD_CONTRATO    
WHERE T2.CD_TP_OPER = 6    
  AND T2.CD_FORMA_OPER = 6    
  AND T2.CD_NATUR_OPER = 2    
  AND T2.VL_OPER IS NOT NULL    
  AND T2.CD_TRANSACAO <> T1.CD_TRANSACAO   
  AND T2.FL_ANALISADO = 1   
  AND T2.DT_TRANS > (T1.DT_REF - (:pm_QtdeDiasRecuo))    
  AND T2.DT_TRANS <= T1.DT_REF   
  HAVING (MAX(T1.VL_RENDA_FAT) IS NOT NULL AND (SUM(T2.VL_OPER) > (MAX(T1.VL_RENDA_FAT) * (:pm_PercRenda/100))) )   
          OR     
         (MAX(T1.VL_RENDA_FAT) IS NULL AND (SUM(T2.VL_OPER) > (:pm_ValorMinimoSomatorioPF)))   
GROUP BY T1.DT_APONTAMENTO, T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE, T2.CD_CONTRATO   
   
UNION ALL   
   
SELECT T1.DT_APONTAMENTO, T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE,        
'Análise: Regra 90 - Liquidação de operação de crédito, incompatível com a capacidade econômica |' ||      
'Objetivo: A) Realização de operações de crédito no País liquidadas com recursos aparentemente incompatíveis com a situação econômico-financeira do cliente. C.C. Bacen n.3.542/2012, Art. 1º, Inciso VII |' ||      
'Conclusão: Realização de operações de crédito no País liquidadas com recursos aparentemente incompatíveis com a situação econômico-financeira do cliente |' ||      
'Cliente: ' ||  MAX(T2.NM_CLIE) || '|' ||    
CASE T2.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T2.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T2.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T2.CD_DOC_IDENTF_CLIE     
END     
|| '|' || 
'Lote: ' || TO_CHAR(:cd_lote) || '|' ||        
'Valor Faturamento: ' || COALESCE(TO_CHAR(MAX(T1.VL_RENDA_FAT), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||     
'Período: De ' || TO_CHAR((MAX(T1.DT_REF) - (:pm_QtdeDiasRecuo)), 'DD/MM/YYYY')    
              || ' até ' || TO_CHAR(MAX(T1.DT_REF), 'DD/MM/YYYY') || '|' ||    
'Número do Contrato: ' || COALESCE(TO_CHAR(T2.CD_CONTRATO), 'Contrato não cadastrado') || '|' ||    
'Data Liquidação do Contrato: ' || COALESCE(TO_CHAR(MAX(T1.DT_LIQUID),'DD/MM/YYYY'), 'Data não cadastrada') || '|' ||    
'Data da Transação pagamento: ' || TO_CHAR(MAX(T1.DT_REF),'DD/MM/YYYY') || '|' ||      
'Valor da Transação de pagamento: ' || TO_CHAR(MAX(T1.VL_OPER), 'L999G999G999G990D99') || '|'  ||      
'Total de pagamentos recentes do contrato: ' || TO_CHAR(sum(T2.VL_OPER), 'L999G999G999G990D99') || '|' ||    
'Pagamentos considerados: detalhes' || '|' ||    
xmlcast(  xmlagg(xmlelement(outros,    
TO_CHAR(T2.DT_TRANS, 'DD/MM/YY') || ':' || ltrim(TO_CHAR(T2.VL_OPER, 'L999G999G999G990D99'))    
|| '|')     
order by T2.CD_DOC_IDENTF_CLIE) as clob)   
|| '|' ||    
'Parâmetro que indica o valor mínimo do Somatório para disparo da regra (pm_ValorMinimoSomatorioPJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoSomatorioPJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro percentual de flexibilização do faturamento do cliente (pm_PercFaturamento): ' || COALESCE((SELECT TO_CHAR(:pm_PercFaturamento, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro que indica a quantidade de dias de recuo (pm_QtdeDiasRecuo): ' || COALESCE((':pm_QtdeDiasRecuo'),'Parâmetro não cadastrado') || '|'    
AS DS_INF_ANLSE       
FROM TB_TRANS T2    
INNER JOIN (SELECT LAST_DAY(TRUNC(DT_TRANS)) DT_APONTAMENTO, CD_TRANSACAO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_CONTRATO,DT_LIQUID, DT_TRANS DT_REF, VL_RENDA_FAT, VL_OPER       
            FROM TB_TRANS_ANLSE    
            WHERE CD_LOTE  = :cd_lote       
            AND CD_SUBLOTE = :cd_sublote      
            AND CD_TP_PESSOA = 'J'      
            AND CD_TP_OPER = 6    
            AND CD_FORMA_OPER = 6    
            AND CD_NATUR_OPER = 2    
            AND DT_LIQUID IS NOT NULL    
            AND CD_CONTRATO IS NOT NULL    
            AND VL_OPER IS NOT NULL    
            ) T1   
     ON T2.CD_DOC_IDENTF_CLIE = T1.CD_DOC_IDENTF_CLIE AND T2.CD_TP_IDENTF_CLIE = T1.CD_TP_IDENTF_CLIE AND T2.CD_CONTRATO = T1.CD_CONTRATO    
WHERE T2.CD_TP_OPER = 6    
  AND T2.CD_FORMA_OPER = 6    
  AND T2.CD_NATUR_OPER = 2    
  AND T2.VL_OPER IS NOT NULL    
  AND T2.CD_TRANSACAO <> T1.CD_TRANSACAO   
  AND T2.FL_ANALISADO = 1   
  AND T2.DT_TRANS > (T1.DT_REF - (:pm_QtdeDiasRecuo))    
  AND T2.DT_TRANS <= T1.DT_REF   
  HAVING (MAX(T1.VL_RENDA_FAT) IS NOT NULL AND (SUM(T2.VL_OPER) > (MAX(T1.VL_RENDA_FAT) * (:pm_PercFaturamento/100))) )   
          OR     
         (MAX(T1.VL_RENDA_FAT) IS NULL AND (SUM(T2.VL_OPER) > (:pm_ValorMinimoSomatorioPJ)))   
GROUP BY T1.DT_APONTAMENTO, T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE, T2.CD_CONTRATO   
   
     