/* e) realização de transferências unilaterais que, pela habitualidade, valor ou forma, Não se justifiquem ou apresentem atipicidade;*/ 

 
SELECT D.DT_APONTAMENTO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,    
'Análise: Regra 124 - Transferências unilaterais |' ||  
'Objetivo: E) Realização de transferências unilaterais que, pela habitualidade, valor ou forma, não se justifiquem ou apresentem atipicidade. C.C. Bacen n.3.542/2012, Art. 1º, Inciso XI. |' ||  
'Conclusão: Realização de transferências unilaterais que, pela habitualidade, valor ou forma, não se justifiquem ou apresentem atipicidade. |' ||  
'Cliente: ' ||  T1.NM_CLIE || '|' ||  
CASE T1.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T1.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||  
'Lote: ' || TO_CHAR(T1.CD_LOTE) || '|' ||  
'Valor Renda: ' || COALESCE(TO_CHAR(T1.VL_RENDA_FAT, '999999990D99'), 'Valor não cadastrado') || '|' ||   
'Análise: Detalhes do débito' || '|' ||   
'Data da Transação: ' || TO_CHAR(T1.DT_TRANS,'DD/MM/YYYY') || '|' ||  
'Valor da Transação: ' || TO_CHAR(T1.VL_OPER, 'L999G999G999G990D99') || '|'  ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T1.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T1.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T1.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T1.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||  
'Nome da pessoa de destino: ' || COALESCE(T1.NM_DESTORIG, 'Nome não cadastrado') || '|' ||  
'País da pessoa de destino: ' || T1.CD_PAIS_DESTORIG || COALESCE((SELECT '-' || NM_PAIS FROM TB_PAIS WHERE CD_PAIS = T1.CD_PAIS_DESTORIG), 'País não cadastrado') || '|' ||  
'Período de análise do perfil Consolidado: de ' || TO_CHAR(ADD_MONTHS(LAST_DAY(ADD_MONTHS(DT_FIM,-12)) + 1, -1),'DD/MM/YYYY HH24.MI.SS') || ' até ' || TO_CHAR(LAST_DAY(ADD_MONTHS(DT_FIM,-1)),'DD/MM/YYYY HH24.MI.SS') || '|' || 
'Quantidade de transferência(s) no período analisado: ' || TO_CHAR(QtdeHabitual) || '|' ||  
'Parâmetro percentual de flexibilização da renda (pm_PercRenda): ' || COALESCE((SELECT TO_CHAR(:pm_PercRenda, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||   
'Parâmetro que indica valor mínimo para apontamento da regra para Pessoa Física (pm_ValorMinimoPF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro que indica quantidade considerada habitual para Pessoa Física (pm_QtdeHabitualPF): ' || COALESCE((':pm_QtdeHabitualPF'),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE   
FROM TB_TRANS_ANLSE T1  
INNER JOIN (SELECT C.DT_APONTAMENTO, T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE, T2.NM_DESTORIG, MAX(C.DT_FIM) DT_FIM, COUNT(*) QtdeHabitual 
              FROM TB_TRANS T2  
              INNER JOIN VM_CLIE C ON T2.CD_DOC_IDENTF_CLIE = C.CD_DOC_IDENTF_CLIE AND T2.CD_TP_IDENTF_CLIE = C.CD_TP_IDENTF_CLIE 
  			  WHERE T2.CD_NATUR_OPER = 2  
  			  AND T2.CD_PAIS_DESTORIG <> 1058  
              AND T2.CD_TP_PESSOA = 'F'  
              AND T2.FL_ANALISADO = 1
  			  AND T2.DT_TRANS >= TO_DATE(ADD_MONTHS(LAST_DAY(ADD_MONTHS(C.DT_FIM,-12)) + 1, -1),'DD/MM/YY')  
  			  AND T2.DT_TRANS <= TO_DATE(LAST_DAY(ADD_MONTHS(C.DT_FIM,-1)))  
  			  HAVING COUNT(*) > (:pm_QtdeHabitualPF)  
              GROUP BY C.DT_APONTAMENTO, T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE, T2.NM_DESTORIG, C.DT_FIM 
  			 ) D 
             ON LAST_DAY(TRUNC(T1.DT_TRANS)) = D.DT_APONTAMENTO AND D.CD_DOC_IDENTF_CLIE = T1.CD_DOC_IDENTF_CLIE AND D.CD_TP_IDENTF_CLIE = T1.CD_TP_IDENTF_CLIE AND D.NM_DESTORIG = T1.NM_DESTORIG  
WHERE T1.CD_LOTE    = :cd_lote   
  AND T1.CD_SUBLOTE = :cd_sublote  
  AND T1.CD_TP_PESSOA = 'F'  
  AND T1.CD_NATUR_OPER = 2  
  AND T1.VL_OPER IS NOT NULL  
  AND T1.VL_OPER > (:pm_ValorMinimoPF)  
  AND T1.NM_DESTORIG IS NOT NULL  
  AND T1.NM_CLIE IS NOT NULL  
  AND T1.NM_CLIE <> T1.NM_DESTORIG 
  AND T1.CD_PAIS_DESTORIG IS NOT NULL  
  AND T1.CD_PAIS_DESTORIG <> 1058  
  AND ((T1.VL_RENDA_FAT IS NOT NULL AND  
        T1.VL_OPER > (T1.VL_RENDA_FAT * (:pm_PercRenda/100)))  
       OR                  
       T1.VL_RENDA_FAT IS NULL  
      )  
 
UNION ALL 
 
SELECT D.DT_APONTAMENTO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,    
'Análise: Regra 124 - Transferências unilaterais |' ||  
'Objetivo: E) Realização de transferências unilaterais que, pela habitualidade, valor ou forma, não se justifiquem ou apresentem atipicidade. C.C. Bacen n.3.542/2012, Art. 1º, Inciso XI |' ||  
'Conclusão: Realização de transferências unilaterais que, pela habitualidade, valor ou forma, não se justifiquem ou apresentem atipicidade |' ||  
'Cliente: ' ||  T1.NM_CLIE || '|' ||  
CASE T1.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T1.CD_DOC_IDENTF_CLIE   
END   
|| '|' || 
'Lote: ' || TO_CHAR(T1.CD_LOTE) || '|' ||    
'Valor Faturamento: ' || COALESCE(TO_CHAR(T1.VL_RENDA_FAT, '999999990D99'), 'Valor não cadastrado') || '|' ||   
'Análise: Detalhes do débito' || '|' ||   
'Data da Transação: ' || TO_CHAR(T1.DT_TRANS,'DD/MM/YYYY') || '|' ||  
'Valor da Transação: ' || TO_CHAR(T1.VL_OPER, 'L999G999G999G990D99') || '|'  ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T1.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T1.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T1.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T1.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||  
'Nome da pessoa de destino: ' || COALESCE(T1.NM_DESTORIG, 'Nome não cadastrado') || '|' ||  
'País da pessoa de destino: ' || T1.CD_PAIS_DESTORIG || COALESCE((SELECT '-' || NM_PAIS FROM TB_PAIS WHERE CD_PAIS = T1.CD_PAIS_DESTORIG), 'País não cadastrado') || '|' ||  
'Período de análise do perfil Consolidado: de ' || TO_CHAR(ADD_MONTHS(LAST_DAY(ADD_MONTHS(DT_FIM,-12)) + 1, -1),'DD/MM/YYYY HH24.MI.SS') || ' até ' || TO_CHAR(LAST_DAY(ADD_MONTHS(DT_FIM,-1)),'DD/MM/YYYY HH24.MI.SS') || '|' || 
'Quantidade de transferência(s) no período analisado: ' || TO_CHAR(QtdeHabitual) || '|' ||  
'Parâmetro percentual de flexibilização do faturamento (pm_PercFaturamento): ' || COALESCE((SELECT TO_CHAR(:pm_PercFaturamento, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||   
'Parâmetro que indica valor mínimo para apontamento da regra para Pessoa Jurídica (pm_ValorMinimoPJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro que indica quantidade considerada habitual para Pessoa Jurídica (pm_QtdeHabitualPJ): ' || COALESCE((':pm_QtdeHabitualPJ'),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE   
FROM TB_TRANS_ANLSE T1  
INNER JOIN (SELECT C.DT_APONTAMENTO, T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE, T2.NM_DESTORIG, MAX(C.DT_FIM) DT_FIM, COUNT(*) QtdeHabitual 
              FROM TB_TRANS T2  
              INNER JOIN VM_CLIE C ON T2.CD_DOC_IDENTF_CLIE = C.CD_DOC_IDENTF_CLIE AND T2.CD_TP_IDENTF_CLIE = C.CD_TP_IDENTF_CLIE 
  			  WHERE T2.CD_NATUR_OPER = 2  
  			  AND T2.CD_PAIS_DESTORIG <> 1058  
              AND T2.CD_TP_PESSOA = 'J'  
              AND T2.FL_ANALISADO = 1
  			  AND T2.DT_TRANS >= TO_DATE(ADD_MONTHS(LAST_DAY(ADD_MONTHS(C.DT_FIM,-12)) + 1, -1),'DD/MM/YY')  
  			  AND T2.DT_TRANS <= TO_DATE(LAST_DAY(ADD_MONTHS(C.DT_FIM,-1)))  
  			  HAVING COUNT(*) > (:pm_QtdeHabitualPJ)  
              GROUP BY C.DT_APONTAMENTO, T2.CD_DOC_IDENTF_CLIE, T2.CD_TP_IDENTF_CLIE, T2.NM_DESTORIG, C.DT_FIM 
  			 ) D 
             ON LAST_DAY(TRUNC(T1.DT_TRANS)) = D.DT_APONTAMENTO AND D.CD_DOC_IDENTF_CLIE = T1.CD_DOC_IDENTF_CLIE AND D.CD_TP_IDENTF_CLIE = T1.CD_TP_IDENTF_CLIE AND D.NM_DESTORIG = T1.NM_DESTORIG  
WHERE T1.CD_LOTE    = :cd_lote   
  AND T1.CD_SUBLOTE = :cd_sublote  
  AND T1.CD_TP_PESSOA = 'J'  
  AND T1.CD_NATUR_OPER = 2  
  AND T1.VL_OPER IS NOT NULL  
  AND T1.VL_OPER > (:pm_ValorMinimoPJ)  
  AND T1.NM_DESTORIG IS NOT NULL  
  AND T1.NM_CLIE IS NOT NULL  
  AND T1.NM_CLIE <> T1.NM_DESTORIG  
  AND T1.CD_PAIS_DESTORIG IS NOT NULL 
  AND T1.CD_PAIS_DESTORIG <> 1058  
  AND ((T1.VL_RENDA_FAT IS NOT NULL AND  
        T1.VL_OPER > (T1.VL_RENDA_FAT * (:pm_PercFaturamento/100)))  
       OR                  
       T1.VL_RENDA_FAT IS NULL  
      )  
      
 
 