SELECT LAST_DAY(TRUNC(T1.DT_TRANS)) DT_APONTAMENTO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: Regra 89 – Utilização de cartão de crédito em valor incompatível com a capacidade econômica ou perfil do cliente |' ||    
'Objetivo: A) Utilização, carga ou recarga de cartão de crédito em valor não compatível com a capacidade econômico-financeira, atividade ou perfil do usuário. C.C. Bacen n. 3.542/2012, Art. 1º, Inciso VI |' ||    
'Conclusão: Utilização de cartão de crédito em valor não compatível com o perfil do usuário |' ||    
'Cliente: ' ||  MAX(T1.NM_CLIE) || '|' ||  
CASE T1.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T1.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||     
'Agência do Cliente: ' || COALESCE(TO_CHAR(T1.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T1.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Valor Renda: ' || COALESCE(TO_CHAR(AVG(T1.VL_RENDA_FAT), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||   
'Lote: ' || TO_CHAR(MAX(T1.CD_LOTE)) || '|' || 
'Valor médio de transações nos ultimos 90 dias: ' || TO_CHAR(VL_MEDIA, 'L999G999G999G990D99') || '|' || 
'Quantidade de transações no dia ' || TO_CHAR(trunc(T1.DT_TRANS),'DD/MM/YY') || ' : ' || TO_CHAR(COUNT(*)) || '|' ||  
xmlcast(  xmlagg(xmlelement(outros,  
COALESCE((SELECT NM_TP_OPER FROM TB_TP_OPER T WHERE T.CD_TP_OPER = T1.CD_TP_OPER), 'Tipo não cadastrado') || ': ' ||   
COALESCE((SELECT NM_FORMA_OPER FROM TB_FORMA_OPER F WHERE F.CD_FORMA_OPER = T1.CD_FORMA_OPER), 'Forma não cadastrada') || ', ' ||   
COALESCE((SELECT NM_VIA_OPER FROM TB_VIA_OPER V WHERE V.CD_VIA_OPER = T1.CD_VIA_OPER), 'Via não cadastrada') || ', ' ||   
ltrim(TO_CHAR(T1.VL_OPER, 'L999G999G999G990D99'))  
|| '|')   
order by T1.CD_DOC_IDENTF_CLIE) as clob) || '|' || 
'Parâmetro percentual de flexibilização da renda do cliente (pm_PercRenda): ' || COALESCE((SELECT TO_CHAR(:pm_PercRenda, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro que indica o valor mínimo para que a regra seja apontada, para Pessoa Física (pm_valorCartaoCreditoPF): ' || COALESCE((SELECT TO_CHAR(:pm_valorCartaoCreditoPF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro percentual de flexibilização do perfil do cliente Pessoa Física (pm_PercPerfilPF): ' || COALESCE((SELECT TO_CHAR(:pm_PercPerfilPF, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'    
AS DS_INF_ANLSE     
FROM TB_TRANS_ANLSE T1   
INNER JOIN 
    (SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, A.DT_TRANS, SUM(VL_OPER) VL_MEDIA 
     FROM TB_TRANS T 
     INNER JOIN 
        (SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, TRUNC(DT_TRANS) DT_TRANS FROM TB_TRANS_ANLSE 
         WHERE CD_LOTE = :cd_lote AND CD_SUBLOTE = :cd_sublote AND CD_TP_PESSOA = 'F' AND CD_FORMA_OPER = 13 OR CD_TP_OPER = 30 
         GROUP BY  CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, TRUNC(DT_TRANS)) A 
         ON T.CD_DOC_IDENTF_CLIE = A.CD_DOC_IDENTF_CLIE  AND T.CD_TP_IDENTF_CLIE = A.CD_TP_IDENTF_CLIE AND T.DT_TRANS >= (A.DT_TRANS - 90) AND T.DT_TRANS <= (A.DT_TRANS - 1) 
     WHERE FL_ANALISADO = 1     
     GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, A.DT_TRANS) M 
ON T1.CD_DOC_IDENTF_CLIE = M.CD_DOC_IDENTF_CLIE  AND T1.CD_TP_IDENTF_CLIE = M.CD_TP_IDENTF_CLIE AND TRUNC(T1.DT_TRANS) = M.DT_TRANS    
WHERE T1.CD_LOTE    = :cd_lote      
  AND T1.CD_SUBLOTE = :cd_sublote     
  AND T1.CD_TP_PESSOA = 'F'   
  AND (T1.CD_FORMA_OPER = 13 OR T1.CD_TP_OPER = 30)  
GROUP BY trunc(T1.DT_TRANS), T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.CD_AG, T1.CD_CTA, M.VL_MEDIA   
HAVING SUM(T1.VL_OPER) > (M.VL_MEDIA * (:pm_PercPerfilPF/100))    
  AND SUM(T1.VL_OPER) > (:pm_valorCartaoCreditoPF)  
  AND (AVG(T1.VL_RENDA_FAT) IS NOT NULL AND (SUM(T1.VL_OPER) > (AVG(T1.VL_RENDA_FAT) * (:pm_PercRenda/100)))    
   OR    
   AVG(T1.VL_RENDA_FAT) IS NULL   ) 
   
UNION ALL 
SELECT LAST_DAY(TRUNC(T1.DT_TRANS)) DT_APONTAMENTO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: Regra 89 – Utilização de cartão de crédito em valor incompatível com a capacidade econômica ou perfil do cliente |' ||    
'Objetivo: A) Utilização, carga ou recarga de cartão de crédito em valor não compatível com a capacidade econômico-financeira, atividade ou perfil do usuário. C.C. Bacen n. 3.542/2012, Art. 1º, Inciso VI |' ||    
'Conclusão: Utilização de cartão de crédito em valor não compatível com o perfil do usuário |' ||    
'Cliente: ' ||  MAX(T1.NM_CLIE) || '|' ||  
CASE T1.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T1.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||     
'Agência do Cliente: ' || COALESCE(TO_CHAR(T1.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T1.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Valor Faturamento: ' || COALESCE(TO_CHAR(AVG(T1.VL_RENDA_FAT), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||   
'Lote: ' || TO_CHAR(MAX(T1.CD_LOTE)) || '|' || 
'Valor médio de transações nos ultimos 90 dias: ' || TO_CHAR(VL_MEDIA, 'L999G999G999G990D99') || '|' || 
'Quantidade de transações no dia ' || TO_CHAR(trunc(T1.DT_TRANS),'DD/MM/YY') || ' : ' || TO_CHAR(COUNT(*)) || '|' ||  
xmlcast(  xmlagg(xmlelement(outros,  
COALESCE((SELECT NM_TP_OPER FROM TB_TP_OPER T WHERE T.CD_TP_OPER = T1.CD_TP_OPER), 'Tipo não cadastrado') || ': ' ||   
COALESCE((SELECT NM_FORMA_OPER FROM TB_FORMA_OPER F WHERE F.CD_FORMA_OPER = T1.CD_FORMA_OPER), 'Forma não cadastrada') || ', ' ||   
COALESCE((SELECT NM_VIA_OPER FROM TB_VIA_OPER V WHERE V.CD_VIA_OPER = T1.CD_VIA_OPER), 'Via não cadastrada') || ', ' ||   
ltrim(TO_CHAR(T1.VL_OPER, 'L999G999G999G990D99'))  
|| '|')   
order by T1.CD_DOC_IDENTF_CLIE) as clob) || '|' || 
'Parâmetro percentual de flexibilização da renda do cliente (pm_PercFaturamento): ' || COALESCE((SELECT TO_CHAR(:pm_PercFaturamento, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro que indica o valor mínimo para que a regra seja apontada, para Pessoa Física (pm_valorCartaoCreditoPJ): ' || COALESCE((SELECT TO_CHAR(:pm_valorCartaoCreditoPJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro percentual de flexibilização do perfil do cliente Pessoa Física (pm_PercPerfilPJ): ' || COALESCE((SELECT TO_CHAR(:pm_PercPerfilPJ, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'    
AS DS_INF_ANLSE     
FROM TB_TRANS_ANLSE T1   
INNER JOIN 
    (SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, A.DT_TRANS, SUM(VL_OPER) VL_MEDIA 
     FROM TB_TRANS T 
     INNER JOIN 
        (SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, TRUNC(DT_TRANS) DT_TRANS FROM TB_TRANS_ANLSE 
         WHERE CD_LOTE = :cd_lote AND CD_SUBLOTE = :cd_sublote AND CD_TP_PESSOA = 'J' AND CD_FORMA_OPER = 13 OR CD_TP_OPER = 30 
         GROUP BY  CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, TRUNC(DT_TRANS)) A 
         ON T.CD_DOC_IDENTF_CLIE = A.CD_DOC_IDENTF_CLIE  AND T.CD_TP_IDENTF_CLIE = A.CD_TP_IDENTF_CLIE AND T.DT_TRANS >= (A.DT_TRANS - 90) AND T.DT_TRANS <= (A.DT_TRANS - 1) 
     WHERE FL_ANALISADO = 1     
     GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, A.DT_TRANS) M 
ON T1.CD_DOC_IDENTF_CLIE = M.CD_DOC_IDENTF_CLIE  AND T1.CD_TP_IDENTF_CLIE = M.CD_TP_IDENTF_CLIE AND TRUNC(T1.DT_TRANS) = M.DT_TRANS    
WHERE T1.CD_LOTE    = :cd_lote      
  AND T1.CD_SUBLOTE = :cd_sublote     
  AND T1.CD_TP_PESSOA = 'J'   
  AND (T1.CD_FORMA_OPER = 13 OR T1.CD_TP_OPER = 30)  
GROUP BY trunc(T1.DT_TRANS), T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.CD_AG, T1.CD_CTA, M.VL_MEDIA   
HAVING SUM(T1.VL_OPER) > (M.VL_MEDIA * (:pm_PercPerfilPJ/100))    
  AND SUM(T1.VL_OPER) > (:pm_valorCartaoCreditoPJ)  
  AND (AVG(T1.VL_RENDA_FAT) IS NOT NULL AND (SUM(T1.VL_OPER) > (AVG(T1.VL_RENDA_FAT) * (:pm_PercFaturamento/100)))    
   OR    
   AVG(T1.VL_RENDA_FAT) IS NULL   ) 
   
   