SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
'Análise: Regra 51 - Transferência de valor arredondado na unidade de milhar ou pouco abaixo do limite |' ||  
'Objetivo: b) Transferências de valores arredondados na unidade de milhar ou que estejam um pouco abaixo do limite para notificação de operações. C.C. Bacen n. 3.542/2012, Art. 1º, Inciso IV |' ||  
'Conclusão: Cliente realizou transferências de valores arredondados na unidade de milhar ou que estejam um pouco abaixo do limite para notificação de operações |' ||  
'Cliente: ' ||  T.NM_CLIE || '|' ||
CASE T.CD_TP_IDENTF_CLIE 
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2) 
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)  
	ELSE T.CD_DOC_IDENTF_CLIE 
END 
|| '|' || 
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||  
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||  
'Natureza da Transação: ' ||    
CASE T.CD_NATUR_OPER   
	 WHEN 1 THEN 'Crédito'   
	 WHEN 2 THEN 'Débito'   
	 WHEN 3 THEN 'Evento'   
	 ELSE 'Natureza não cadastrada'   
END || '|' || 
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT ' - ' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||  
'Agência/Conta da Transação: ' || COALESCE(TO_CHAR(T.CD_AG, '0000') || ' / ' || TO_CHAR(T.CD_CTA,'0000000000'), 'Agência/Conta não cadastrada') || '|' ||  
'Parâmetro que indica o limite de valor para notificação da operação da Faixa 1 (pm_ValorNotificacaoFaixa1): ' || COALESCE((SELECT TO_CHAR(:pm_ValorNotificacaoFaixa1, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro que indica o limite de valor para notificação da operação da Faixa 2 (pm_ValorNotificacaoFaixa2): ' || COALESCE((SELECT TO_CHAR(:pm_ValorNotificacaoFaixa2, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro percentual para flexibilização de valores pouco abaixo do limite para notificação (pm_PercAbxLimite): ' || COALESCE((SELECT TO_CHAR(:pm_PercAbxLimite, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro de valor mínimo para valor da operação (pm_ValorMinimo): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimo, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'   
AS DS_INF_ANLSE   
FROM TB_TRANS_ANLSE T  
WHERE  T.CD_LOTE    = :cd_lote   
   AND T.CD_SUBLOTE = :cd_sublote 
   AND T.CD_TP_OPER IN (5, 8, 9)  
   AND T.VL_OPER IS NOT NULL   
   AND (   
        (T.VL_OPER < (:pm_ValorNotificacaoFaixa1)  
         AND   
         ((T.VL_OPER /(:pm_ValorNotificacaoFaixa1)) * 100) >   
          (:pm_PercAbxLimite)  
        )  
        OR  
        (T.VL_OPER >= (:pm_ValorNotificacaoFaixa1)  
         AND  
         T.VL_OPER < (:pm_ValorNotificacaoFaixa2)  
         AND   
         ((T.VL_OPER/(:pm_ValorNotificacaoFaixa2)) * 100) >   
          (:pm_PercAbxLimite)  
        )  
        OR   
        (T.VL_OPER >= (:pm_ValorMinimo)  
         AND  
         (MOD(T.VL_OPER, 1000) = 0)  
        )      
       )
              
  
