/*Pagamentos ou transferências por pessoa jurídica para fornecedor distante de seu local de atuação,*/  
  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
'Análise: Regra 65 - Pagamento a fornecedor distante |' ||  
'Objetivo: P) Pagamentos ou transferências por pessoa jurídica para fornecedor distante de seu local de atuação, sem fundamentação econômico-financeira. C.C. Bacen n. 3.542/2012, Art. 1º, Inciso IV |' ||  
'Conclusão: Pagamento ou transferência a fornecedor em UF diferente do endereço do cliente |' ||  
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE 
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2) 
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)  
	ELSE T.CD_DOC_IDENTF_CLIE 
END 
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||  
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, '999999990D99') || '|'  ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||  
'CEP Agência do Cliente: ' || CASE LENGTH(TO_CHAR(T.CD_CEP_AG_CLIE))  
                                   WHEN 7 THEN '0' || SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),1,4) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),5,3)  
                                   WHEN 8 THEN SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),1,5) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),6,3)  
                                   ELSE 'CEP não cadastrado'  
                              END || '|' ||  
'CEP Agência da Operação: ' || CASE LENGTH(TO_CHAR(T.CD_CEP_AG_OPER))  
                                    WHEN 7 THEN '0' || SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),1,4) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),5,3)  
                                    WHEN 8 THEN SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),1,5) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),6,3)  
                                    ELSE 'CEP não cadastrado'  
                               END || '|'||  
'Parâmetro que indica a distância mínima entre dois CEPs (pm_Distancia): ' || COALESCE((':pm_Distancia'),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro que indica valor mínimo de PJ para outros (pm_ValorMinimo_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimo_PJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE   
FROM TB_TRANS_ANLSE T  
WHERE T.CD_LOTE    = :cd_lote   
  AND T.CD_SUBLOTE = :cd_sublote  
  AND T.CD_TP_PESSOA = 'J'  
  AND T.CD_NATUR_OPER = 2  
  AND T.CD_TP_OPER = 9  
  AND T.CD_CEP_AG_CLIE IS NOT NULL  
  AND T.CD_CEP_AG_OPER IS NOT NULL  
  AND ABS(TO_NUMBER(SUBSTR(LPAD(TO_CHAR(T.CD_CEP_AG_CLIE), 8, '0'), 1, 5)) - TO_NUMBER(SUBSTR(LPAD(TO_CHAR(T.CD_CEP_AG_OPER), 8, '0'), 1, 5))) >  
      (:pm_Distancia)   
  AND T.VL_OPER > (:pm_ValorMinimo_PJ)   
UNION  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
'Análise: Regra 65 - Pagamento a fornecedor distante |' ||  
'Objetivo: P) Pagamentos ou transferências por pessoa jurídica para fornecedor distante de seu local de atuação, sem fundamentação econômico-financeira. C.C. Bacen n. 3.542/2012, Art. 1º, Inciso IV |' ||  
'Conclusão: Pagamento ou transferência a fornecedor em UF diferente do endereço do cliente |' ||  
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE 
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2) 
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)  
	ELSE T.CD_DOC_IDENTF_CLIE 
END 
|| '|' || 
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||  
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, '999999990D99') || '|'  ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||  
'CEP Agência do Cliente: ' || CASE LENGTH(TO_CHAR(T.CD_CEP_AG_CLIE))  
                                   WHEN 7 THEN '0' || SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),1,4) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),5,3)  
                                   WHEN 8 THEN SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),1,5) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),6,3)  
                                   ELSE 'CEP não cadastrado'  
                              END || '|' ||  
'CEP Agência da Operação: ' || CASE LENGTH(TO_CHAR(T.CD_CEP_AG_OPER))  
                                    WHEN 7 THEN '0' || SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),1,4) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),5,3)  
                                    WHEN 8 THEN SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),1,5) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),6,3)  
                                    ELSE 'CEP não cadastrado'  
                               END || '|'||  
'Parâmetro que indica a distância mínima entre dois CEPs (pm_Distancia): ' || COALESCE((':pm_Distancia'),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro que indica valor mínimo de PJ para PJ (pm_ValorMinimoPJ_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPJ_PJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE   
FROM TB_TRANS_ANLSE T  
WHERE T.CD_LOTE    = :cd_lote   
  AND T.CD_SUBLOTE = :cd_sublote  
  AND T.CD_TP_PESSOA = 'J'  
  AND T.CD_NATUR_OPER = 1  
  AND T.CD_TP_OPER = 9  
  AND T.CD_TP_IDENTF_DESTORIG = 3  
  AND T.CD_CEP_AG_CLIE IS NOT NULL  
  AND T.CD_CEP_AG_OPER IS NOT NULL  
  AND ABS(TO_NUMBER(SUBSTR(LPAD(TO_CHAR(T.CD_CEP_AG_CLIE), 8, '0'), 1, 5)) - TO_NUMBER(SUBSTR(LPAD(TO_CHAR(T.CD_CEP_AG_OPER), 8, '0'), 1, 5))) >  
      (:pm_Distancia)   
  AND T.VL_OPER > (:pm_ValorMinimoPJ_PJ)   
UNION  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
'Análise: Regra 65 - Pagamento a fornecedor distante |' ||  
'Objetivo: P) Pagamentos ou transferências por pessoa jurídica para fornecedor distante de seu local de atuação, sem fundamentação econômico-financeira. C.C. Bacen n. 3.542/2012, Art. 1º, Inciso IV |' ||  
'Conclusão: Pagamento ou transferência a fornecedor em UF diferente do endereço do cliente |' ||  
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE 
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2) 
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)  
	ELSE T.CD_DOC_IDENTF_CLIE 
END 
|| '|' || 
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||  
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, '999999990D99') || '|'  ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||  
'CEP Agência do Cliente: ' || CASE LENGTH(TO_CHAR(T.CD_CEP_AG_CLIE))  
                                   WHEN 7 THEN '0' || SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),1,4) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),5,3)  
                                   WHEN 8 THEN SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),1,5) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_CLIE),6,3)  
                                   ELSE 'CEP não cadastrado'  
                              END || '|' ||  
'CEP Agência da Operação: ' || CASE LENGTH(TO_CHAR(T.CD_CEP_AG_OPER))  
                                    WHEN 7 THEN '0' || SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),1,4) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),5,3)  
                                    WHEN 8 THEN SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),1,5) || '-' || SUBSTR(TO_CHAR(T.CD_CEP_AG_OPER),6,3)  
                                    ELSE 'CEP não cadastrado'  
                               END || '|'||  
'Parâmetro que indica a distância mínima entre dois CEPs (pm_Distancia): ' || COALESCE((':pm_Distancia'),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro que indica valor mínimo de PF para PJ (pm_ValorMinimoPF_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPF_PJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE   
FROM TB_TRANS_ANLSE T  
WHERE T.CD_LOTE    = :cd_lote   
  AND T.CD_SUBLOTE = :cd_sublote  
  AND T.CD_TP_PESSOA = 'F'  
  AND T.CD_NATUR_OPER = 1  
  AND T.CD_TP_OPER = 9  
  AND T.CD_TP_IDENTF_DESTORIG = 3  
  AND T.CD_CEP_AG_CLIE IS NOT NULL  
  AND T.CD_CEP_AG_OPER IS NOT NULL  
  AND ABS(TO_NUMBER(SUBSTR(LPAD(TO_CHAR(T.CD_CEP_AG_CLIE), 8, '0'), 1, 5)) - TO_NUMBER(SUBSTR(LPAD(TO_CHAR(T.CD_CEP_AG_OPER), 8, '0'), 1, 5))) >  
      (:pm_Distancia)   
  AND T.VL_OPER > (:pm_ValorMinimoPF_PJ)   
  
  