SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,       
'Análise: Regra 20 - Transferência de Recurso em Espécie |' ||      
'Objetivo: a) Realização de depósitos, saques, pedidos de provisionamento para saque ou qualquer outro instrumento de transferência de recursos em espécie, que apresentem atipicidade em relação à atividade econômica do cliente ou incompatibilidade com a sua capacidade econômico-financeira. C.C. Bacen n.3.542/2012, Art. 1º, Inciso I |' ||      
'Conclusão: Cliente transferiu recursos em espécie, incompatível com sua capacidade econômica financeira e atípica em relação a sua atividade econômica |' ||      
'Cliente: ' ||  T.NM_CLIE || '|' ||     
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||     
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||    
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||     
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|' ||  
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||      
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||      
'Valor Renda: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||       
'Ocupação: ' ||  COALESCE(OCUPACAO, 'Ocupação não cadastrada')   || '|' ||     
'Parâmetro percentual de flexibilização da renda do cliente (pm_PercRenda): ' || COALESCE((SELECT TO_CHAR(:pm_PercRenda, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||       
'Parâmetro de valor mínimo para valor da operação. Somente Pessoa Física (pm_ValorMinimoPF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||       
'Parâmetro percentual de flexibilização da média mensal de crédito da ocupação (pm_PercOcupacao): ' || COALESCE((SELECT TO_CHAR(:pm_PercOcupacao, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'      
AS DS_INF_ANLSE    
FROM 
( 
SELECT T.CD_TRANSACAO, T.CD_AG, T.CD_CTA, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE, T.CD_LOTE, T.DT_TRANS, T.VL_OPER, T.CD_TP_OPER, T.CD_FORMA_OPER, T.VL_RENDA_FAT, 
LISTAGG(COALESCE((SELECT NM_OCUP FROM TB_OCUP P WHERE O.CD_OCUP = P.CD_OCUP),TO_CHAR(O.CD_OCUP)) || TO_CHAR(O.VL_MED_CREDITO, 'L999G999G999G990D99'), '/ ') WITHIN GROUP (ORDER BY O.CD_OCUP desc) OCUPACAO 
FROM TB_TRANS_ANLSE T  
left JOIN TB_CLIE_RENDA R ON R.CD_DOC_IDENTF_CLIE = T.CD_DOC_IDENTF_CLIE  AND R.CD_TP_IDENTF_CLIE = T.CD_TP_IDENTF_CLIE  
left JOIN TB_MED_OCUP O   ON R.CD_OCUP = O.CD_OCUP                     
WHERE T.CD_TP_PESSOA = 'F'      
AND T.CD_LOTE    = :cd_lote        
AND T.CD_SUBLOTE = :cd_sublote       
AND (T.CD_FORMA_OPER = 7 OR T.CD_TP_OPER = 17)      
AND T.VL_OPER IS NOT NULL      
AND T.VL_OPER > (:pm_ValorMinimoPF)         
AND (T.VL_OPER > (O.VL_MED_CREDITO * (SELECT :pm_PercOcupacao/100 FROM DUAL))      
     OR  
     (T.VL_RENDA_FAT IS NOT NULL AND      
       T.VL_OPER > (T.VL_RENDA_FAT * (SELECT :pm_PercRenda/100 FROM DUAL)) )      
     OR  
     T.VL_RENDA_FAT IS NULL      
    )      
GROUP BY T.CD_TRANSACAO, T.CD_AG, T.CD_CTA, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE, T.CD_LOTE, T.DT_TRANS, T.VL_OPER, T.CD_TP_OPER, T.CD_FORMA_OPER, T.VL_RENDA_FAT  
) T      

UNION ALL    
SELECT DISTINCT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,       
'Análise: Regra 20 - Transferência de Recurso em Espécie |' ||      
'Objetivo: a) Realização de depósitos, saques, pedidos de provisionamento para saque ou qualquer outro instrumento de transferência de recursos em espécie, que apresentem atipicidade em relação à atividade econômica do cliente ou incompatibilidade com a sua capacidade econômico-financeira. C.C. Bacen n.3.542/2012, Art. 1º, Inciso I |' ||       
'Conclusão: Cliente transferiu recursos em espécie, incompatível com sua capacidade econômica financeira e atípica em relação a sua atividade econômica |' ||      
'Cliente: ' ||  T.NM_CLIE || '|' ||     
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||     
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||    
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||     
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|' ||    
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||      
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||      
'Ramo de Atividade: ' || COALESCE((SELECT TO_CHAR(R.NM_RAMO_ATIVID) FROM TB_RAMO_ATIVID R      
                                   WHERE T.CD_RAMO_ATIVID = R.CD_RAMO_ATIVID),'Ramo de Atividade não cadastrado') || '|' ||      
'Valor Médio de Crédito do Ramo de Atividade: ' || COALESCE(TO_CHAR(R.VL_MED_CREDITO, 'L999G999G999G990D99'),'Valor não cadastrado.') || '|' ||      
'Valor Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||       
'Parâmetro percentual de flexibilização da média mensal de crédito do ramo de atividade (pm_PercRamoAtividade): ' || COALESCE((SELECT TO_CHAR(:pm_PercRamoAtividade, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||      
'Parâmetro de valor mínimo para valor da operação. Somente Pessoa Jurídica (pm_ValorMinimoPJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||      
'Parâmetro percentual de flexibilização do faturamento (pm_PercFatmt): ' || COALESCE((SELECT TO_CHAR(:pm_PercFatmt, '999999990D99') FROM DUAL),'Parâmetro não cadastrado.') || '|'      
AS DS_INF_ANLSE      
FROM TB_TRANS_ANLSE T  left JOIN TB_MED_RAMO_ATIVID R    
                       ON T.CD_RAMO_ATIVID = R.CD_RAMO_ATIVID    
WHERE T.CD_TP_PESSOA = 'J'      
AND T.CD_LOTE    = :cd_lote       
AND T.CD_SUBLOTE = :cd_sublote      
AND (T.CD_FORMA_OPER = 7 OR T.CD_TP_OPER = 17 )      
AND T.VL_OPER IS NOT NULL      
AND T.VL_OPER > (:pm_ValorMinimoPJ)      
AND ((R.VL_MED_CREDITO IS NOT NULL       
      AND T.VL_OPER > (R.VL_MED_CREDITO * (SELECT :pm_PercRamoAtividade/100 FROM DUAL))       
     )      
     OR      
     (T.VL_RENDA_FAT IS NOT NULL AND T.VL_OPER > (T.VL_RENDA_FAT * (SELECT :pm_PercFatmt/100 FROM DUAL)))        
     OR      
     T.VL_RENDA_FAT IS NULL      
    )   


