/* VERSAO 1 */ 

SELECT DISTINCT LAST_DAY(T.DT_APONTAMENTO) AS DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,      
'Análise: Regra 210 – Valor de crédito elevado na conta, no dia |' ||     
'Objetivo: Verifica total de crédito na conta, no dia, para pessoas físicas e pessoas jurídicas |' ||     
'Conclusão: Cliente pessoa física ou pessoa jurídica recebeu valor expressivo de créditos na conta no dia |' ||     
'Cliente: ' ||  T.NM_CLIE || '|' ||    
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||     
'Lote: ' || TO_CHAR(T.CD_LOTE) ||  '|' ||      
'Natureza: Crédito |' ||   
'Tipo: Depósito/DOC/TED/TEV |'  ||  
'Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'),'Faturamento não cadastrado') || '|' ||   
'Valor Consolidado no dia ' || TO_CHAR(T.DT_APONTAMENTO,'DD/MM/YYYY') || ': ' || TO_CHAR(T.VL_TOTAL, 'L999G999G999G990D99') || '|' || 
'Quantidade de transações : ' || TO_CHAR(QTDE) || '|' || 
'Parâmetro que indica o valor considerado elevado para crédito em conta no dia para pessoa jurídica (pm_ValorCredito_PF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorCredito_PF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro percentual aplicado sobre o Faturamento,  para verificar se o valor de créditos superou x vezes o Faturamento do cliente (pm_PercCredito_PF): ' || COALESCE((SELECT TO_CHAR(:pm_PercCredito_PF, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE    
FROM 
(SELECT T1.NM_CLIE, T1.CD_LOTE, T1.DT_APONTAMENTO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.VL_RENDA_FAT, SUM(T.VL_OPER) VL_TOTAL, COUNT(*) QTDE 
FROM TB_TRANS_ANLSE T  
INNER JOIN 
 (SELECT NM_CLIE, CD_LOTE, TRUNC(T1.DT_TRANS) DT_APONTAMENTO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.VL_RENDA_FAT 
  FROM TB_TRANS_ANLSE T1   
  WHERE T1.CD_LOTE  = :cd_lote    
    AND T1.CD_SUBLOTE = :cd_sublote  
    AND T1.CD_TP_PESSOA = 'F'   
    AND T1.CD_NATUR_OPER = 1  
    AND T1.CD_TP_OPER IN (4, 5, 8, 9)   
  GROUP BY NM_CLIE, CD_LOTE, (TRUNC(T1.DT_TRANS)), T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.VL_RENDA_FAT) T1 
ON  T.CD_DOC_IDENTF_CLIE = T1.CD_DOC_IDENTF_CLIE AND T.CD_TP_IDENTF_CLIE = T1.CD_TP_IDENTF_CLIE AND TRUNC(T.DT_TRANS) = T1.DT_APONTAMENTO  
WHERE T.CD_TP_PESSOA = 'F'   
  AND T.CD_NATUR_OPER = 1  
  AND T.CD_TP_OPER IN (4, 5, 8, 9)  
GROUP BY T1.NM_CLIE, T1.CD_LOTE, T1.DT_APONTAMENTO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.VL_RENDA_FAT ) T 
WHERE T.VL_TOTAL > (:pm_ValorCredito_PF)  
  AND ((T.VL_RENDA_FAT IS NOT NULL AND    
      T.VL_TOTAL >= (T.VL_RENDA_FAT * (:pm_PercCredito_PF/100))  
     )   
     OR   
     T.VL_RENDA_FAT IS NULL   
    )  
    
UNION ALL   
SELECT DISTINCT LAST_DAY(T.DT_APONTAMENTO) AS DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,      
'Análise: Regra 210 – Valor de crédito elevado na conta, no dia |' ||     
'Objetivo: Verifica total de crédito na conta, no dia, para pessoas físicas e pessoas jurídicas |' ||     
'Conclusão: Cliente pessoa física ou pessoa jurídica recebeu valor expressivo de créditos na conta no dia |' ||     
'Cliente: ' ||  T.NM_CLIE || '|' ||    
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||     
'Lote: ' || TO_CHAR(T.CD_LOTE) ||  '|' ||      
'Natureza: Crédito |' ||   
'Tipo: Depósito/DOC/TED/TEV |'  ||  
'Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'),'Faturamento não cadastrado') || '|' ||   
'Valor Consolidado no dia ' || TO_CHAR(T.DT_APONTAMENTO,'DD/MM/YYYY') || ': ' || TO_CHAR(T.VL_TOTAL, 'L999G999G999G990D99') || '|' || 
'Quantidade de transações : ' || TO_CHAR(QTDE) || '|' || 
'Parâmetro que indica o valor considerado elevado para crédito em conta no dia para pessoa jurídica (pm_ValorCredito_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorCredito_PJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro percentual aplicado sobre o Faturamento,  para verificar se o valor de créditos superou x vezes o Faturamento do cliente (pm_PercCredito_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_PercCredito_PJ, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE    
FROM 
(SELECT T1.NM_CLIE, T1.CD_LOTE, T1.DT_APONTAMENTO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.VL_RENDA_FAT, SUM(T.VL_OPER) VL_TOTAL, COUNT(*) QTDE 
FROM TB_TRANS_ANLSE T  
INNER JOIN 
 (SELECT NM_CLIE, CD_LOTE, TRUNC(T1.DT_TRANS) DT_APONTAMENTO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.VL_RENDA_FAT 
  FROM TB_TRANS_ANLSE T1   
  WHERE T1.CD_LOTE  = :cd_lote    
    AND T1.CD_SUBLOTE = :cd_sublote  
    AND T1.CD_TP_PESSOA = 'J'   
    AND T1.CD_NATUR_OPER = 1  
    AND T1.CD_TP_OPER IN (4, 5, 8, 9)   
  GROUP BY NM_CLIE, CD_LOTE, (TRUNC(T1.DT_TRANS)), T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.VL_RENDA_FAT) T1 
ON  T.CD_DOC_IDENTF_CLIE = T1.CD_DOC_IDENTF_CLIE AND T.CD_TP_IDENTF_CLIE = T1.CD_TP_IDENTF_CLIE AND TRUNC(T.DT_TRANS) = T1.DT_APONTAMENTO  
WHERE T.CD_TP_PESSOA = 'J'   
  AND T.CD_NATUR_OPER = 1  
  AND T.CD_TP_OPER IN (4, 5, 8, 9)  
GROUP BY T1.NM_CLIE, T1.CD_LOTE, T1.DT_APONTAMENTO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.VL_RENDA_FAT ) T 
WHERE T.VL_TOTAL > (:pm_ValorCredito_PJ)  
  AND ((T.VL_RENDA_FAT IS NOT NULL AND    
      T.VL_TOTAL >= (T.VL_RENDA_FAT * (:pm_PercCredito_PJ/100))  
     )   
     OR   
     T.VL_RENDA_FAT IS NULL   
    )  





  
