SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,     
'Análise: Regra 75 - Resgates de investimentos em curtíssimo prazo |' ||    
'Objetivo: E) Resgates de investimentos no curtíssimo prazo, independentemente do resultado auferido. C.C. Bacen n.3.542/2012, Art. 1º, Inciso V |' ||    
'Conclusão: Resgates de investimentos no curtíssimo prazo, independentemente do resultado auferido |' ||    
'Cliente: ' ||  T.NM_CLIE || '|' ||  
CASE T.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||   
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||    
'Data Início da Aplicação: ' || TO_CHAR(T.DT_INIC_APLICACAO,'DD/MM/YYYY') || '|' ||    
'Quantidade de dias para o resgate: ' || TO_CHAR(TRUNC(T.DT_TRANS) - TRUNC(DT_INIC_APLICACAO)) || '|' ||  
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||    
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||  
'Natureza da Transação: ' ||   
CASE T.CD_NATUR_OPER  
	 WHEN 1 THEN 'Crédito'  
	 WHEN 2 THEN 'Débito'  
	 WHEN 3 THEN 'Evento'  
	 ELSE 'Natureza não cadastrada'  
END || '|' ||  
'Parâmetro de comparação, em dias, que identifica Curto Prazo (pm_QtdeDiaCurtoPrazo): ' || COALESCE((':pm_QtdeDiaCurtoPrazo'),'Parâmetro não cadastrado') || '|'   
AS DS_INF_ANLSE     
FROM TB_TRANS_ANLSE T  
WHERE T.CD_LOTE    = :cd_lote      
  AND T.CD_SUBLOTE = :cd_sublote     
  AND T.CD_TP_OPER = 1  
  AND T.CD_NATUR_OPER = 1  
  AND T.DT_TRANS IS NOT NULL  
  AND T.DT_INIC_APLICACAO IS NOT NULL  
  AND ((TRUNC(T.DT_TRANS) - TRUNC(DT_INIC_APLICACAO)) < (:pm_QtdeDiaCurtoPrazo))  
  