/* b) negociações de moeda estrangeira em espécie, em municipios localizados em regiões de fronteira, */   
/* que Não apresentem compatibilidade com a natureza declarada da operação;  */   
   
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,     
'Análise: Regra 31 - Operação em moeda estrangeira em região de fronteira |' ||    
'Objetivo: b) Negociações de moeda estrangeira em espécie, em municípios localizados em regiões de fronteira, que não apresentem compatibilidade com a natureza declarada da operação. C.C. Bacen n.3.542/2012, Art. 1º, Inciso II |' ||    
'Conclusão: Cliente realizou negociação de moeda estrangeira em espécie, e a agência da sua conta está localizada em regiões de fronteira |' ||    
'Cliente: ' ||  T.NM_CLIE || '|' ||  
CASE T.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||    
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||    
'Data da Transação: '  || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||    
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||    
'Natureza da Transação: ' ||     
CASE T.CD_NATUR_OPER    
	 WHEN 1 THEN 'Crédito'    
	 WHEN 2 THEN 'Débito'    
	 WHEN 3 THEN 'Evento'    
	 ELSE 'Natureza não cadastrada'    
END || '|' ||    
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||    
'Banco da operação: ' || COALESCE(TO_CHAR(T.CD_BANCO_OPER,'000'), 'Banco da transação não cadastrado') || '|' ||      
'Agência da operação (Região de fronteira): ' || COALESCE(TO_CHAR(T.CD_AG_OPER,'0000'), 'Agência não cadastrada') || '|' ||    
'Parâmetro que indica valor elevado para transações em moeda estrangeira (pm_ValorAltoMoedaEstrangeira): ' || COALESCE((SELECT TO_CHAR(:pm_ValorAltoMoedaEstrangeira, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro percentual de flexibilização do valor médio da natureza declarada da operação (pm_PercNaturOper): ' || COALESCE((SELECT TO_CHAR(:pm_PercNaturOper, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'    
AS DS_INF_ANLSE      
FROM TB_TRANS_ANLSE T 
INNER JOIN TB_AGENCIA A ON T.CD_AG_OPER = A.CD_AG  AND T.CD_BANCO_OPER = A.CD_BANCO 
INNER JOIN TB_NATUR_DECLR_OPER N ON N.CD_NATUR_DECLR_OPER = T.CD_NATUR_DECLR_OPER 
 Where T.CD_LOTE    = :cd_lote     
   AND T.CD_SUBLOTE = :cd_sublote    
   AND T.CD_FORMA_OPER = 8     
   AND T.CD_AG_OPER IS NOT NULL   
   AND T.CD_NATUR_DECLR_OPER IS NOT NULL  
   AND T.VL_OPER    IS NOT NULL     
   AND T.VL_OPER > (:pm_ValorAltoMoedaEstrangeira)      
   AND T.VL_OPER > (VL_MEDIO_NATUR_OPER * (:pm_PercNaturOper/100))   
   AND A.Fl_FRONT = 1    
    
   