SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 70 - Movimentação expressiva para PEP |' ||   
'Objetivo: S) Movimentação habitual de recursos financeiros de ou para pessoas expostas politicamente ou pessoas de relacionamento próximo, não justificada por eventos econômicos. C.C. Bacen n. 3.542/2012, Art. 1º, Inciso IV |' ||   
'Conclusão: Movimentação expressiva de recursos financeiros de ou para pessoas expostas politicamente ou pessoas de relacionamento próximo, não justificada por eventos econômicos |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||   
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
CASE T.CD_TP_IDENTF_DESTORIG  
	WHEN 2 THEN 'Documento de Identificação do Destino/Origem relacionado como PEP (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 10, 2)  
	WHEN 3 THEN 'Documento de Identificação do Destino/Origem relacionado como PEP (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 13, 2)   
	ELSE COALESCE(TO_CHAR(T.CD_DOC_IDENTF_DESTORIG), 'Documento não cadastrado')   
END  
|| '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||    
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Valor Renda: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||   
'Parâmetro percentual de flexibilização da renda (pm_PercRenda): ' || COALESCE((SELECT TO_CHAR(:pm_PercRenda, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro que representa valor de transferências para PEP, que deve ser apontado pela regra (pm_ValorMinimoPF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'   
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T   
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote   
  AND T.CD_TP_PESSOA = 'F'   
  AND T.CD_DOC_IDENTF_DESTORIG IS NOT NULL 
  AND T.VL_OPER >= (:pm_ValorMinimoPF)   
  AND EXISTS (SELECT 1 FROM TB_PPE P   
       		  WHERE T.CD_DOC_IDENTF_DESTORIG = P.CD_DOC_IDENTF   
       		  AND T.CD_TP_IDENTF_DESTORIG = P.CD_TP_IDENTF   
      		 )   
  AND ((T.VL_RENDA_FAT IS NOT NULL AND   
        T.VL_OPER > (T.VL_RENDA_FAT *    
                     (SELECT :pm_PercRenda/100 FROM DUAL)))   
       OR   
       (T.VL_RENDA_FAT IS NULL)   
      ) 
UNION ALL  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
'Análise: Regra 70 - Movimentação expressiva para PEP |' ||   
'Objetivo: S) Movimentação habitual de recursos financeiros de ou para pessoas expostas politicamente ou pessoas de relacionamento próximo, não justificada por eventos econômicos. C.C. Bacen n. 3.542/2012, Art. 1º, Inciso IV |' ||   
'Conclusão: Movimentação expressiva de recursos financeiros de ou para pessoas expostas politicamente ou pessoas de relacionamento próximo, não justificada por eventos econômicos |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
CASE T.CD_TP_IDENTF_DESTORIG  
	WHEN 2 THEN 'Documento de Identificação do Destino/Origem relacionado como PEP (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 10, 2)  
	WHEN 3 THEN 'Documento de Identificação do Destino/Origem relacionado como PEP (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 13, 2)   
	ELSE COALESCE(TO_CHAR(T.CD_DOC_IDENTF_DESTORIG), 'Documento não cadastrado')   
END  
|| '|' ||   
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||  
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Agência do Cliente: ' || COALESCE(TO_CHAR(T.CD_AG,'0000'),'Agência não informada') || '|'  ||   
'Conta do Cliente: '   || COALESCE(TO_CHAR(T.CD_CTA,'0000000000'),'Conta não informada') || '|'  ||  
'Valor Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||   
'Parâmetro percentual de flexibilização do faturamento (pm_PercFaturamento): ' || COALESCE((SELECT TO_CHAR(:pm_PercFaturamento, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||    
'Parâmetro que representa valor de transferências para PEP, que deve ser apontado pela regra (pm_ValorMinimoPJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'   
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T   
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote   
  AND T.CD_TP_PESSOA = 'J'  
  AND T.CD_DOC_IDENTF_DESTORIG IS NOT NULL  
  AND T.VL_OPER >= (:pm_ValorMinimoPJ)   
  AND EXISTS (SELECT 1 FROM TB_PPE P   
       		  WHERE T.CD_DOC_IDENTF_DESTORIG = P.CD_DOC_IDENTF   
       		  AND T.CD_TP_IDENTF_DESTORIG = P.CD_TP_IDENTF   
      		 )   
  AND ((T.VL_RENDA_FAT IS NOT NULL AND   
        T.VL_OPER > (T.VL_RENDA_FAT *    
                     (SELECT :pm_PercFaturamento/100 FROM DUAL)))   
       OR   
       (T.VL_RENDA_FAT IS NULL)   
      )
      
      