SELECT 
P.CD_SEQ_PPE,
P.DT_ATULZ_PPE,
P.CD_DOC_IDENTF,
P.CD_TP_IDENTF,
P.NM_PPE,
P.DS_PPE_GRAU_ENVOLV,
P.SG_ORG_INTERNL,
P.CD_PAIS_ORIG,
P.NU_PASSRTE,
P.CD_FONTE_INF 
FROM TB_PPE P
JOIN TB_TRANS_ANLSE T
    ON
        (
	        (P.CD_DOC_IDENTF = T.CD_DOC_IDENTF_DESTORIG AND P.CD_TP_IDENTF = T.CD_TP_IDENTF_DESTORIG) OR
	        (P.CD_DOC_IDENTF = T.CD_DOC_IDENTF_BNEFC AND P.CD_TP_IDENTF = T.CD_TP_IDENTF_BNEFC) 
        )
      where
		P.CD_DOC_IDENTF is not NULL AND
		P.CD_TP_IDENTF  is not NULL  AND
		(
			(T.CD_DOC_IDENTF_DESTORIG is not NULL AND T.CD_TP_IDENTF_DESTORIG   is not NULL) OR
			(T.CD_DOC_IDENTF_BNEFC is not NULL AND T.CD_TP_IDENTF_BNEFC   is not NULL) 
		) AND
		T.CD_LOTE = ? AND
		T.CD_SUBLOTE = ?