SELECT COUNT(*) AS TOTAL FROM
(
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO
FROM TB_TRANS_ANLSE T
WHERE T.CD_LOTE = 2014091801
  AND VL_OPER IS NOT NULL
  AND VL_OPER > (SELECT VL_PARAM FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 11 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_vlDefinidoLei')       
  AND (( VL_RENDA_FAT IS NOT NULL AND
         VL_OPER > (T.VL_RENDA_FAT * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 11 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percRendaFat') ) ) 
         OR
         VL_RENDA_FAT IS NULL)        
  AND EXISTS (
    SELECT 1 FROM TB_PERFIL_MES_CALENDARIO P
    WHERE P.CD_VARIAVEL_PRIMEIRA = T.CD_DOC_IDENTF_CLIE
      AND P.CD_VARIAVEL_SEGUNDA  = T.CD_TP_IDENTF_CLIE )
     
  AND NOT EXISTS (
    SELECT 1 FROM TB_PERFIL_MES_CALENDARIO P
    WHERE P.CD_IDENTF_PERFIL     = 9
      AND P.CD_VARIAVEL_PRIMEIRA = T.CD_DOC_IDENTF_CLIE
      AND P.CD_VARIAVEL_SEGUNDA  = T.CD_TP_IDENTF_CLIE 
      AND P.CD_VARIAVEL_TERCEIRA = T.CD_TP_OPER 
      AND P.CD_VARIAVEL_QUARTA   = T.CD_FORMA_OPER
 	  and p.cd_ano_mes <> CASE WHEN MONTH(t.dt_trans) < 10
                               THEN CAST(YEAR(t.dt_trans) AS VARCHAR) + '0' + CAST(MONTH(t.dt_trans) AS VARCHAR)
                               ELSE CAST(YEAR(t.dt_trans) AS VARCHAR) +       CAST(MONTH(t.dt_trans) AS VARCHAR)
                          END
     )
) S; 
SELECT COUNT(1) AS TOTAL FROM TB_DETLH_APONTAMENTO WHERE CD_LOTE = 2014091801 AND CD_REGRA = 11

