select count(*) as total from
(
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE T
WHERE CD_LOTE 		= 2014091801
  AND CD_FORMA_OPER = 7  
  AND EXISTS
      (SELECT 1 FROM TB_PERFIL_MES_CALENDARIO
        WHERE CD_VARIAVEL_PRIMEIRA = T.CD_DOC_IDENTF_CLIE
          AND CD_VARIAVEL_SEGUNDA  = T.CD_TP_IDENTF_CLIE
        )
  AND NOT EXISTS
      (SELECT 1 FROM TB_PERFIL_MES_CALENDARIO
        WHERE CD_IDENTF_PERFIL = 9
          AND CD_VARIAVEL_PRIMEIRA = T.CD_DOC_IDENTF_CLIE
          AND CD_VARIAVEL_SEGUNDA  = T.CD_TP_IDENTF_CLIE
          AND CD_VARIAVEL_TERCEIRA = T.CD_FORMA_OPER
        )
UNION
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE T
WHERE CD_LOTE 		= 2014091801
  AND CD_TP_PESSOA  = 'J'
  AND CD_FORMA_OPER = 7  
  AND CD_SETOR IS NOT NULL  
  AND CD_SETOR NOT IN (SELECT * from splitstring((select DS_PARAM from tb_regra_parametro where cd_regra = 21 and cd_versao_sistema = 3 and NM_CAMPO_PARAM = 'pm_Lista_Setores')))
) as a; 
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 20