SELECT COUNT(*) AS TOTAL FROM
(
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO
FROM TB_TRANS_ANLSE T
WHERE CD_LOTE = 2014091801
        AND CD_NATUR_OPER = 1
        AND CD_TP_OPER = 4
        AND (
                DT_TRANS IS NULL OR 
                VL_OPER IS NULL OR
                NM_PSSOA_REALZ_TRANS IS NULL OR
                CD_DOC_IDENTF_REALZ_TRANS IS NULL
            )

UNION 
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO
FROM TB_TRANS_ANLSE T
WHERE CD_LOTE = 2014091801
        AND CD_TP_OPER = 17
        AND (
                DT_TRANS IS NULL OR 
                VL_OPER IS NULL OR
                NM_DESTORIG IS NULL OR
                CD_DOC_IDENTF_DESTORIG IS NULL OR
                CD_BCO_DESTORIG IS NULL OR
                CD_AG_DESTORIG IS NULL OR
                CD_CTA_DESTORIG IS NULL
            )
) S; 
SELECT COUNT(1) AS TOTAL FROM TB_DETLH_APONTAMENTO WHERE CD_LOTE = 2014091801 AND CD_REGRA = 10