select count(*) as total from
(
select CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO
FROM TB_TRANS_ANLSE t
WHERE cd_lote = 2014091801
  and CD_TP_OPER = 30
  and CD_CARTAO IS NOT NULL
  and DT_FECHA_FATURA IS NOT NULL
  and VL_FATURA IS NOT NULL
  AND  EXISTS (
   SELECT 1 FROM TB_PERFIL_INFORMACAO
   WHERE CD_IDENTF_PERFIL = 24
     AND CD_VARIAVEL_PRIMEIRA = T.CD_DOC_IDENTF_CLIE
     AND CD_VARIAVEL_SEGUNDA  = T.CD_TP_IDENTF_CLIE
     AND CD_VARIAVEL_TERCEIRA = T.CD_CARTAO
     AND CD_VARIAVEL_QUARTA = T.DT_FECHA_FATURA
     AND QT_TOTAL > 1
     AND (VL_TOTAL/QT_TOTAL) = T.VL_FATURA
   )
) s; 
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 204