select count(1) as total from
(
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO FROM TB_TRANS_ANLSE T1
WHERE CD_LOTE = 2014091801
  AND CD_TP_OPER = 6
  AND CD_PAIS_OPER = 986
  AND DT_PRIM_VCTO_CONTRATO IS NOT NULL
  AND DT_LIQUID IS NOT NULL
  AND QT_MES_CONTT IS NOT NULL
  AND  DATEDIFF(month,DT_LIQUID,DATEADD(month,(QT_MES_CONTT-1),DT_PRIM_VCTO_CONTRATO)) > (QT_MES_CONTT/2)          
) s; 
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 93