/* BANRISUL - MENSAL */ 
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4089 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Mês/Ano: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) ||  '|' ||   
'Contrato:' || CD_CONTRATO ||  '|' ||
'Origem do sistema: ' || NM_SIST_ORIG ||  '|' ||
'Valor da renda/Faturamento: ' || TO_CHAR(VL_RENDA_FAT, 'L999G999G999G990D99') || '|' ||
'Valor principal do contrato: ' || TO_CHAR(VL_PRINC_CONTRATO, 'L999G999G999G990D99') || '|' ||
'Valor consolidado de lances no mês calendário: ' || TO_CHAR(ValorConsolidadoLances, 'L999G999G999G990D99') || '|' ||
COALESCE((':DS-pm_CodGrupoProduto' || ' (' || ':NM-pm_CodGrupoProduto' || '):' || TO_CHAR(:pm_CodGrupoProduto)),'Parâmetro não cadastrado' ) || '|'   ||
CASE CD_TP_IDENTF_CLIE 
WHEN 2 THEN 
COALESCE((':DS-pm_ValorMinimoPF' || ' (' || ':NM-pm_ValorMinimoPF' || '):' || TO_CHAR(:pm_ValorMinimoPF, 'L999G999G999G990D99')),'Parâmetro não cadastrado' )  || '|' ||    
COALESCE((':DS-pm_PercLancePF'   || ' (' || ':NM-pm_PercLancePF'   || '):' || TO_CHAR(:pm_PercLancePF) || '%'),'Parâmetro não cadastrado' ) || '|'   
WHEN 3 THEN 
COALESCE((':DS-pm_ValorMinimoPJ'   || ' (' || ':NM-pm_ValorMinimoPJ'   || '):' || TO_CHAR(:pm_ValorMinimoPJ, 'L999G999G999G990D99')),'Parâmetro não cadastrado' ) || '|' ||    
COALESCE((':DS-pm_PercLancePJ'     || ' (' || ':NM-pm_PercLancePJ'     || '):' || TO_CHAR(:pm_PercLancePJ)     || '%'),'Parâmetro não cadastrado' ) || '|'  
END
AS DS_INF_ANLSE 
FROM  (SELECT T.CD_MES_ANO, T.CD_TP_PESSOA, T.CD_CONTRATO, T.NM_SIST_ORIG, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, 
       MAX(T.NM_CLIE) NM_CLIE, MAX(T.VL_RENDA_FAT) VL_RENDA_FAT, MAX(T.VL_PRINC_CONTRATO) VL_PRINC_CONTRATO, SUM(VL_OPER) ValorConsolidadoLances      
       FROM TB_TRANS T    
	   WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
       AND   T.DT_TRANS <   add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
       AND   T.FL_ANALISADO = 1  
       AND   T.CD_TP_OPER = 16 /*LANCE*/
       AND   T.CD_STTUS_CONTRATO = 1 /*ativo*/ 
       AND   T.CD_GRP_PRODUTO = (:pm_CodGrupoProduto)
       AND   T.CD_CONTRATO IS NOT NULL
	   GROUP BY T.CD_MES_ANO, T.CD_TP_PESSOA, T.CD_CONTRATO, T.NM_SIST_ORIG, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE
       ) T 
WHERE 
(CD_TP_PESSOA = 'F' AND
 VL_PRINC_CONTRATO is not null AND
 ValorConsolidadoLances >= (:pm_ValorMinimoPF) AND
 (ValorConsolidadoLances >= (VL_PRINC_CONTRATO * ((:pm_PercLancePF)/100)) )
 )   
OR
(CD_TP_PESSOA = 'J' AND
 VL_PRINC_CONTRATO is not null AND
 ValorConsolidadoLances >= (:pm_ValorMinimoPJ) AND
 (ValorConsolidadoLances >= (VL_PRINC_CONTRATO * ((:pm_PercLancePJ)/100)) )
 )  
 
