/*MENSAL*/ 
SELECT T.CD_DOC_IDENTF_CLIE,T.CD_TP_IDENTF_CLIE,     
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4022 AND CD_VERSAO_SISTEMA = 4) || 
'Cliente: ' ||  coalesce(T.NM_CLIE, 'Nome não informado') || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||     
'Ano e mês ' || TO_CHAR(cd_mes_ano)  || '|' || 
'Quantidade de formas distintas: ' || TO_CHAR(qtde) || '|' || 
'Formas: ' || FORMA || '|' || 
COALESCE((SELECT DS_CAMPO_PARAM || ' (' || NM_CAMPO_PARAM || '):' || (SELECT TO_CHAR(:pm_codMoedaBrasil) FROM DUAL)  FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4022 AND CD_VERSAO_SISTEMA = 4 AND NM_CAMPO_PARAM = 'pm_codMoedaBrasil'),'Parâmetro não cadastrado|' ) || '|' || 
COALESCE((SELECT DS_CAMPO_PARAM || ' (' || NM_CAMPO_PARAM || '):' || (SELECT TO_CHAR(:pm_qtdeFormaDistinta) FROM DUAL)  FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4022 AND CD_VERSAO_SISTEMA = 4 AND NM_CAMPO_PARAM = 'pm_qtdeFormaDistinta'),'Parâmetro não cadastrado|' ) || '|'  
AS DS_INF_ANLSE   
FROM 
(SELECT CD_MES_ANO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE  
,LISTAGG( COALESCE((SELECT NM_FORMA_OPER FROM TB_FORMA_OPER F WHERE F.CD_FORMA_OPER = T.CD_FORMA_OPER), TO_CHAR(T.CD_FORMA_OPER)) , ', ')  
 WITHIN GROUP (ORDER BY T.CD_FORMA_OPER) FORMA, COUNT(*) QTDE 
 FROM 
 (SELECT A.CD_MES_ANO, A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.CD_LOTE, a.CD_FORMA_OPER 
FROM TB_TRANS A 
WHERE FL_ANALISADO = 1  
  AND DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
  AND DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
  AND CD_TP_OPER in ( 
     25, /*Emissão de cartão pré-pago*/ 
     26 )/*Recarga de cartão pré-pago*/ 
  AND CD_MOEDA <> (:pm_codMoedaBrasil)    
GROUP BY A.CD_MES_ANO, A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE,  A.CD_LOTE, a.CD_FORMA_OPER  
) T 
GROUP BY CD_MES_ANO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE 
HAVING COUNT(*) >= (:pm_qtdeFormaDistinta) 
) T  