SELECT T.CD_DOC_IDENTF_CLIE,T.CD_TP_IDENTF_CLIE,     
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4037 AND CD_VERSAO_SISTEMA = 4) || 
'Cliente: ' ||  coalesce(T.NM_CLIE, 'Nome não informado') || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||     
'Mês/Ano: ' || SUBSTR(T.CD_MES_ANO, 5, 2) || '/' || SUBSTR(T.CD_MES_ANO, 1, 4) || '|' ||   
'Valor do faturamento do cliente: ' || TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99') || '|' || 
'Setor do cliente: Comércio '  || '|' ||
'Sócio(s) : |' || SOCIOS || '|' || 
COALESCE((':DS-pm_RamoAtividade' || ' (' || ':NM-pm_RamoAtividade' || '):' || ':LS-pm_RamoAtividade' ),'Parâmetro não cadastrado|' ) || '|' ||    
COALESCE((':DS-pm_holding' || ' (' || ':NM-pm_holding' || '):' || ':pm_holding' ),'Parâmetro não cadastrado|' ) || '|'  ||
COALESCE((':DS-pm_Setor_Com' || ' (' || ':NM-pm_Setor_Com' || '):' || ':LS-pm_Setor_Com'),'Parâmetro não cadastrado|' ) || '|' ||    
COALESCE((':DS-pm_PercParticipacaoPF' || ' (' || ':NM-pm_PercParticipacaoPF' || '):' || ':pm_PercParticipacaoPF' || '%'),'Parâmetro não cadastrado|' ) || '|'  ||
COALESCE((':DS-pm_PercParticipacaoPJ' || ' (' || ':NM-pm_PercParticipacaoPJ' || '):' || ':pm_PercParticipacaoPJ' || '%'),'Parâmetro não cadastrado|' ) || '|' ||    
COALESCE((':DS-pm_PercFaturamentoPFcom' || ' (' || ':NM-pm_PercFaturamentoPFcom' || '):' || ':pm_PercFaturamentoPFcom' || '%'),'Parâmetro não cadastrado|' ) || '|' || 
COALESCE((':DS-pm_PercFaturamentoPJcom' || ' (' || ':NM-pm_PercFaturamentoPJcom' || '):' || ':pm_PercFaturamentoPJcom' || '%'),'Parâmetro não cadastrado|' ) || '|'  
AS DS_INF_ANLSE   
FROM 
( 
SELECT A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.CD_MES_ANO, A.VL_RENDA_FAT, A.CD_SETOR, 
xmlcast(  xmlagg(xmlelement(SOCIOS, 
('CPF/CNPJ ' || C.CD_DOC_IDENTF_SOCIO) || 
': Renda/Faturamento ' || COALESCE(LTRIM(TO_CHAR(C.VL_RENDA_FAT_SOCIO, 'L999G999G999G990D99')), 'não informado') || 
', Percentual de participação ' || to_char(C.PC_PARTC_SOCIO) || '%' || 
', Ramo de atividade ' || coalesce(coalesce((select nm_ramo_ativid from TB_RAMO_ATIVID R where r.CD_RAMO_ATIVID = c.CD_RAMO_ATIVID_SOCIO), to_char(c.CD_RAMO_ATIVID_SOCIO)),'não informado') || 
' | ')  order by CD_DOC_IDENTF_SOCIO) as clob) SOCIOS 
FROM TB_CADEIA_SOCTRIA C   
INNER JOIN 
(SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, MAX(NM_CLIE) NM_CLIE, CD_MES_ANO, MAX(VL_RENDA_FAT) VL_RENDA_FAT, CD_SETOR  
 FROM TB_TRANS T    
 WHERE T.DT_TRANS >= to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS <  add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)   
   AND T.FL_ANALISADO = 1   
   AND CD_TP_PESSOA = 'J' 
   AND CD_SETOR IS NOT NULL
   AND CD_SETOR IN (SELECT TRIM(regexp_substr(':LS-pm_Setor_Com', '[^,]+', 1, level)) VAL FROM DUAL CONNECT BY level <= regexp_count(':LS-pm_Setor_Com',',')+1)  
 group by CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_MES_ANO, CD_SETOR
 ) A  
ON C.CD_DOC_IDENTF_SOCIEDD = A.CD_DOC_IDENTF_CLIE AND C.CD_TP_IDENTF_SOCIEDD = A.CD_TP_IDENTF_CLIE  
WHERE 
  (   C.CD_TP_IDENTF_SOCIO = 2 /*PF*/
  AND C.PC_PARTC_SOCIO IS NOT NULL 
  AND C.PC_PARTC_SOCIO >= (:pm_PercParticipacaoPF)   
  AND (
      (VL_RENDA_FAT_SOCIO IS NULL AND A.VL_RENDA_FAT IS NOT NULL)
       OR
      (VL_RENDA_FAT_SOCIO IS NOT NULL AND A.VL_RENDA_FAT IS NOT NULL AND
       VL_RENDA_FAT_SOCIO <= (A.VL_RENDA_FAT * (C.PC_PARTC_SOCIO/100) * (:pm_PercFaturamentoPFcom/100)))
     )
   ) /* FIM BLOCO PF*/ 
  OR
    (   C.CD_TP_IDENTF_SOCIO = 3 /*PJ*/
    AND (
      (CD_RAMO_ATIVID_SOCIO IS NOT NULL AND
       :pm_holding = 1 AND C.CD_RAMO_ATIVID_SOCIO NOT IN (SELECT TRIM(regexp_substr(':LS-pm_RamoAtividade', '[^,]+', 1, level)) VAL FROM DUAL CONNECT BY level <= regexp_count(':LS-pm_RamoAtividade',',')+1))
      or
      (:pm_holding = 0)
      )
    AND C.PC_PARTC_SOCIO IS NOT NULL 
    AND C.PC_PARTC_SOCIO >= (:pm_PercParticipacaoPJ)  
    AND (
      (VL_RENDA_FAT_SOCIO IS NULL AND A.VL_RENDA_FAT IS NOT NULL)
       OR
      (VL_RENDA_FAT_SOCIO IS NOT NULL AND A.VL_RENDA_FAT IS NOT NULL AND
       VL_RENDA_FAT_SOCIO <= (A.VL_RENDA_FAT * (C.PC_PARTC_SOCIO/100) * (:pm_PercFaturamentoPJcom/100)))
     )
   ) /* FIM BLOCO PJ*/
group by A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.CD_MES_ANO, A.VL_RENDA_FAT, A.CD_SETOR 
) T 

UNION ALL

SELECT T.CD_DOC_IDENTF_CLIE,T.CD_TP_IDENTF_CLIE,     
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4037 AND CD_VERSAO_SISTEMA = 4) || 
'Cliente: ' ||  coalesce(T.NM_CLIE, 'Nome não informado') || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||     
'Mês/Ano: ' || SUBSTR(T.CD_MES_ANO, 5, 2) || '/' || SUBSTR(T.CD_MES_ANO, 1, 4) || '|' ||  
'Valor do faturamento do cliente: ' || TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99') || '|' || 
'Setor do cliente: Indústria '  || '|' ||
'Sócio(s) : |' || SOCIOS || '|' || 
COALESCE((':DS-pm_RamoAtividade' || ' (' || ':NM-pm_RamoAtividade' || '):' || ':LS-pm_RamoAtividade' ),'Parâmetro não cadastrado|' ) || '|' ||    
COALESCE((':DS-pm_holding' || ' (' || ':NM-pm_holding' || '):' || ':pm_holding' ),'Parâmetro não cadastrado|' ) || '|'  ||
COALESCE((':DS-pm_Setor_Ind' || ' (' || ':NM-pm_Setor_Ind' || '):' || ':LS-pm_Setor_Ind' ),'Parâmetro não cadastrado|' ) || '|' ||    
COALESCE((':DS-pm_PercParticipacaoPF' || ' (' || ':NM-pm_PercParticipacaoPF' || '):' || ':pm_PercParticipacaoPF' || '%'),'Parâmetro não cadastrado|' ) || '|'  ||
COALESCE((':DS-pm_PercParticipacaoPJ' || ' (' || ':NM-pm_PercParticipacaoPJ' || '):' || ':pm_PercParticipacaoPJ' || '%'),'Parâmetro não cadastrado|' ) || '|' ||    
COALESCE((':DS-pm_PercFaturamentoPFind' || ' (' || ':NM-pm_PercFaturamentoPFind' || '):' || ':pm_PercFaturamentoPFind' || '%'),'Parâmetro não cadastrado|' ) || '|' || 
COALESCE((':DS-pm_PercFaturamentoPJind' || ' (' || ':NM-pm_PercFaturamentoPJind' || '):' || ':pm_PercFaturamentoPJind' || '%'),'Parâmetro não cadastrado|' ) || '|'  
AS DS_INF_ANLSE   
FROM 
( 
SELECT A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.CD_MES_ANO, A.VL_RENDA_FAT, A.CD_SETOR, 
xmlcast(  xmlagg(xmlelement(SOCIOS, 
('CPF/CNPJ ' || C.CD_DOC_IDENTF_SOCIO) || 
': Renda/Faturamento ' || COALESCE(LTRIM(TO_CHAR(C.VL_RENDA_FAT_SOCIO, 'L999G999G999G990D99')), 'não informado') || 
', Percentual de participação ' || to_char(C.PC_PARTC_SOCIO) || '%' || 
', Ramo de atividade ' || coalesce(coalesce((select nm_ramo_ativid from TB_RAMO_ATIVID R where r.CD_RAMO_ATIVID = c.CD_RAMO_ATIVID_SOCIO), to_char(c.CD_RAMO_ATIVID_SOCIO)),'não informado') || 
' | ')  order by CD_DOC_IDENTF_SOCIO) as clob) SOCIOS  
FROM TB_CADEIA_SOCTRIA C   
INNER JOIN 
(SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, MAX(NM_CLIE) NM_CLIE, CD_MES_ANO, MAX(VL_RENDA_FAT) VL_RENDA_FAT, CD_SETOR 
 FROM TB_TRANS T
 WHERE T.DT_TRANS >= to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)   
   AND T.FL_ANALISADO = 1 
   AND CD_TP_PESSOA = 'J' 
   AND CD_SETOR IS NOT NULL
   AND CD_SETOR IN (SELECT TRIM(regexp_substr(':LS-pm_Setor_Ind', '[^,]+', 1, level)) VAL FROM DUAL CONNECT BY level <= regexp_count(':LS-pm_Setor_Ind',',')+1)  
 group by CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_MES_ANO, CD_SETOR 
 ) A  
ON C.CD_DOC_IDENTF_SOCIEDD = A.CD_DOC_IDENTF_CLIE AND C.CD_TP_IDENTF_SOCIEDD = A.CD_TP_IDENTF_CLIE  
WHERE 
  (   C.CD_TP_IDENTF_SOCIO = 2 /*PF*/
  AND C.PC_PARTC_SOCIO IS NOT NULL 
  AND C.PC_PARTC_SOCIO >= (:pm_PercParticipacaoPF)   
  AND (
      (VL_RENDA_FAT_SOCIO IS NULL AND A.VL_RENDA_FAT IS NOT NULL)
       OR
      (VL_RENDA_FAT_SOCIO IS NOT NULL AND A.VL_RENDA_FAT IS NOT NULL AND
       VL_RENDA_FAT_SOCIO <= (A.VL_RENDA_FAT * (C.PC_PARTC_SOCIO/100) * (:pm_PercFaturamentoPFind/100)))
     )
   ) /* FIM BLOCO PF*/ 
  OR
    (   C.CD_TP_IDENTF_SOCIO = 3 /*PJ*/
    AND (
      (CD_RAMO_ATIVID_SOCIO IS NOT NULL AND
       :pm_holding = 1 AND C.CD_RAMO_ATIVID_SOCIO NOT IN (SELECT TRIM(regexp_substr(':LS-pm_RamoAtividade', '[^,]+', 1, level)) VAL FROM DUAL CONNECT BY level <= regexp_count(':LS-pm_RamoAtividade',',')+1))
      or
      (:pm_holding = 0)
      )    
    AND C.PC_PARTC_SOCIO IS NOT NULL 
    AND C.PC_PARTC_SOCIO >= (:pm_PercParticipacaoPJ)  
    AND (
      (VL_RENDA_FAT_SOCIO IS NULL AND A.VL_RENDA_FAT IS NOT NULL)
       OR
      (VL_RENDA_FAT_SOCIO IS NOT NULL AND A.VL_RENDA_FAT IS NOT NULL AND
       VL_RENDA_FAT_SOCIO <= (A.VL_RENDA_FAT * (C.PC_PARTC_SOCIO/100) * (:pm_PercFaturamentoPJind/100)))
     )
   ) /* FIM BLOCO PJ*/
group by A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.CD_MES_ANO, A.VL_RENDA_FAT, A.CD_SETOR
) T 

UNION ALL

SELECT T.CD_DOC_IDENTF_CLIE,T.CD_TP_IDENTF_CLIE,     
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4037 AND CD_VERSAO_SISTEMA = 4) || 
'Cliente: ' ||  coalesce(T.NM_CLIE, 'Nome não informado') || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||     
'Mês/Ano: ' || SUBSTR(T.CD_MES_ANO, 5, 2) || '/' || SUBSTR(T.CD_MES_ANO, 1, 4) || '|' ||    
'Valor do faturamento do cliente: ' || TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99') || '|' || 
'Setor do cliente: Serviço ' || '|' ||
'Sócio(s) : |' || SOCIOS || '|' || 
COALESCE((':DS-pm_RamoAtividade' || ' (' || ':NM-pm_RamoAtividade' || '):' || ':LS-pm_RamoAtividade' ),'Parâmetro não cadastrado|' ) || '|' ||    
COALESCE((':DS-pm_holding' || ' (' || ':NM-pm_holding' || '):' || ':pm_holding' ),'Parâmetro não cadastrado|' ) || '|'  ||
COALESCE((':DS-pm_Setor_Serv' || ' (' || ':NM-pm_Setor_Serv' || '):' || ':LS-pm_Setor_Serv' ),'Parâmetro não cadastrado|' ) || '|' ||    
COALESCE((':DS-pm_PercParticipacaoPF' || ' (' || ':NM-pm_PercParticipacaoPF' || '):' || ':pm_PercParticipacaoPF' || '%'),'Parâmetro não cadastrado|' ) || '|'  ||
COALESCE((':DS-pm_PercParticipacaoPJ' || ' (' || ':NM-pm_PercParticipacaoPJ' || '):' || ':pm_PercParticipacaoPJ' || '%'),'Parâmetro não cadastrado|' ) || '|' ||    
COALESCE((':DS-pm_PercFaturamentoPFser' || ' (' || ':NM-pm_PercFaturamentoPFser' || '):' || ':pm_PercFaturamentoPFser' || '%'),'Parâmetro não cadastrado|' ) || '|' || 
COALESCE((':DS-pm_PercFaturamentoPJser' || ' (' || ':NM-pm_PercFaturamentoPJser' || '):' || ':pm_PercFaturamentoPJser '|| '%'),'Parâmetro não cadastrado|' ) || '|'  
AS DS_INF_ANLSE   
FROM 
( 
SELECT A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.CD_MES_ANO, A.VL_RENDA_FAT, A.CD_SETOR, 
xmlcast(  xmlagg(xmlelement(SOCIOS, 
('CPF/CNPJ ' || C.CD_DOC_IDENTF_SOCIO) || 
': Renda/Faturamento ' || COALESCE(LTRIM(TO_CHAR(C.VL_RENDA_FAT_SOCIO, 'L999G999G999G990D99')), 'não informado') || 
', Percentual de participação ' || to_char(C.PC_PARTC_SOCIO) || '%' || 
', Ramo de atividade ' || coalesce(coalesce((select nm_ramo_ativid from TB_RAMO_ATIVID R where r.CD_RAMO_ATIVID = c.CD_RAMO_ATIVID_SOCIO), to_char(c.CD_RAMO_ATIVID_SOCIO)),'não informado') || 
' | ')  order by CD_DOC_IDENTF_SOCIO) as clob) SOCIOS  
FROM TB_CADEIA_SOCTRIA C   
INNER JOIN 
(SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, MAX(NM_CLIE) NM_CLIE, CD_MES_ANO, MAX(VL_RENDA_FAT) VL_RENDA_FAT, CD_SETOR 
 FROM TB_TRANS T
 WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)   
   AND T.FL_ANALISADO = 1  
   AND CD_TP_PESSOA = 'J' 
   AND CD_SETOR IS NOT NULL
   AND CD_SETOR IN (SELECT TRIM(regexp_substr(':LS-pm_Setor_Serv', '[^,]+', 1, level)) VAL FROM DUAL CONNECT BY level <= regexp_count(':LS-pm_Setor_Serv',',')+1)  
 group by CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_MES_ANO, CD_SETOR 
 ) A  
ON C.CD_DOC_IDENTF_SOCIEDD = A.CD_DOC_IDENTF_CLIE AND C.CD_TP_IDENTF_SOCIEDD = A.CD_TP_IDENTF_CLIE  
WHERE 
  (   C.CD_TP_IDENTF_SOCIO = 2 /*PF*/
  AND C.PC_PARTC_SOCIO IS NOT NULL 
  AND C.PC_PARTC_SOCIO >= (:pm_PercParticipacaoPF)   
  AND (
      (VL_RENDA_FAT_SOCIO IS NULL AND A.VL_RENDA_FAT IS NOT NULL)
       OR
      (VL_RENDA_FAT_SOCIO IS NOT NULL AND A.VL_RENDA_FAT IS NOT NULL AND
       VL_RENDA_FAT_SOCIO <= (A.VL_RENDA_FAT * (C.PC_PARTC_SOCIO/100) * (:pm_PercFaturamentoPFser/100)))
     )
   ) /* FIM BLOCO PF*/ 
  OR
    (   C.CD_TP_IDENTF_SOCIO = 3 /*PJ*/
   AND (
      (CD_RAMO_ATIVID_SOCIO IS NOT NULL AND
       :pm_holding = 1 AND C.CD_RAMO_ATIVID_SOCIO NOT IN (SELECT TRIM(regexp_substr(':LS-pm_RamoAtividade', '[^,]+', 1, level)) VAL FROM DUAL CONNECT BY level <= regexp_count(':LS-pm_RamoAtividade',',')+1))
      or
      (:pm_holding = 0)
      )  
    AND C.PC_PARTC_SOCIO IS NOT NULL 
    AND C.PC_PARTC_SOCIO >= (:pm_PercParticipacaoPJ)  
    AND (
      (VL_RENDA_FAT_SOCIO IS NULL AND A.VL_RENDA_FAT IS NOT NULL)
       OR
      (VL_RENDA_FAT_SOCIO IS NOT NULL AND A.VL_RENDA_FAT IS NOT NULL AND
       VL_RENDA_FAT_SOCIO <= (A.VL_RENDA_FAT * (C.PC_PARTC_SOCIO/100) * (:pm_PercFaturamentoPJser/100)))
     )
   ) /* FIM BLOCO PJ*/
group by A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.CD_MES_ANO, A.VL_RENDA_FAT, A.CD_SETOR 
) T 


 
 