/* BANRISUL - MENSAL  */  
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4114 AND CD_VERSAO_SISTEMA = 4) ||   
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' ||  
CASE T.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||     
'Mês Calendário: ' || SUBSTR(T.CD_MES_ANO, 5, 2) || '/' || SUBSTR(T.CD_MES_ANO, 1, 4) || '|' ||  
'Valor Consolidado de Crédito de origem fora do Brasil:' || COALESCE(TO_CHAR(T.TOTAL_CREDITO, 'L999G999G999G990D99'), 'Não cadastrado') || '|' ||  
COALESCE((':DS-pm_CodBrasil' || ' (' || ':NM-pm_CodBrasil' || '):' || :pm_CodBrasil),'Parâmetro não cadastrado' ) || '|' ||   
CASE T.CD_TP_PESSOA  
     WHEN 'F' THEN COALESCE((':DS-pm_ValorConsolidadoCreditoPF' || ' (' || ':NM-pm_ValorConsolidadoCreditoPF' || '):' || TO_CHAR(:pm_ValorConsolidadoCreditoPF, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|'    
	 WHEN 'J' THEN COALESCE((':DS-pm_ValorConsolidadoCreditoPJ' || ' (' || ':NM-pm_ValorConsolidadoCreditoPJ' || '):' || TO_CHAR(:pm_ValorConsolidadoCreditoPJ, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|'    
END  
AS DS_INF_ANLSE  
FROM (SELECT T.CD_DOC_IDENTF_CLIE,  T.CD_TP_IDENTF_CLIE, T.CD_TP_PESSOA, T.NM_CLIE, T.CD_MES_ANO, SUM(T.VL_OPER) TOTAL_CREDITO   
      FROM TB_TRANS T   
      WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
        AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
        AND T.FL_ANALISADO = 1  
        AND T.CD_NATUR_OPER = 1 /* CREDITO */ 
	    AND T.CD_PAIS_DESTORIG <> (:pm_CodBrasil)  
	  GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_TP_PESSOA, T.NM_CLIE, T.CD_MES_ANO  
	 ) T  
WHERE ((T.CD_TP_PESSOA = 'F'  
        AND T.TOTAL_CREDITO >= (:pm_ValorConsolidadoCreditoPF)  
       ) 
	   OR  
	   (T.CD_TP_PESSOA = 'J'  
        AND T.TOTAL_CREDITO >= (:pm_ValorConsolidadoCreditoPJ)  
       ) 
	  ) 
UNION ALL  
SELECT DISTINCT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4114 AND CD_VERSAO_SISTEMA = 4) ||   
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' ||  
CASE T.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||     
'Mês Calendário: ' || SUBSTR(T.CD_MES_ANO, 5, 2) || '/' || SUBSTR(T.CD_MES_ANO, 1, 4) || '|' ||  
'Valor Consolidado de Débitos para fora do Brasil:' || COALESCE(TO_CHAR(T.TOTAL_DEBITO, 'L999G999G999G990D99'), 'Não cadastrado') || '|' ||  
COALESCE((':DS-pm_CodBrasil' || ' (' || ':NM-pm_CodBrasil' || '):' || :pm_CodBrasil),'Parâmetro não cadastrado' ) || '|' ||   
CASE T.CD_TP_PESSOA  
     WHEN 'F' THEN COALESCE((':DS-pm_ValorConsolidadoDebitoPF' || ' (' || ':NM-pm_ValorConsolidadoDebitoPF' || '):' || TO_CHAR(:pm_ValorConsolidadoDebitoPF, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|'    
	 WHEN 'J' THEN COALESCE((':DS-pm_ValorConsolidadoDebitoPJ' || ' (' || ':NM-pm_ValorConsolidadoDebitoPJ' || '):' || TO_CHAR(:pm_ValorConsolidadoDebitoPJ, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|'    
END  
AS DS_INF_ANLSE  
FROM (SELECT T.CD_DOC_IDENTF_CLIE,  T.CD_TP_IDENTF_CLIE, T.CD_TP_PESSOA, T.NM_CLIE, T.CD_MES_ANO, SUM(T.VL_OPER) TOTAL_DEBITO   
      FROM TB_TRANS T   
      WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
        AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
        AND T.FL_ANALISADO = 1  
        AND T.CD_NATUR_OPER = 2 /* DEBITO */ 
	    AND T.CD_PAIS_DESTORIG <> (:pm_CodBrasil)  
	  GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_TP_PESSOA, T.NM_CLIE, T.CD_MES_ANO  
	 ) T  
WHERE ((T.CD_TP_PESSOA = 'F'  
        AND T.TOTAL_DEBITO >= (:pm_ValorConsolidadoDebitoPF)  
       ) 
	   OR  
	   (T.CD_TP_PESSOA = 'J'  
        AND T.TOTAL_DEBITO >= (:pm_ValorConsolidadoDebitoPJ)  
       ) 
	  ) 
 
