/* BANRISUL - MENSAL */ 
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4087 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Mês/Ano: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) ||  '|' ||   
'Quantidade de contratos de consórcio ativos adquiridos no mês calendário: ' || COALESCE(TO_CHAR(T.QTDE_CONTRATOS_MES),'Não encontrado') || '|' || 
'Contratos de consórcio ativos adquiridos no mês calendário: ' || COALESCE(T.CONTRATOS_MES,'Não encontrado') || '|' || 
'Quantidade de contratos de consórcio ativos, desconsiderando os contratos ativos adquiridos no mês calendário: ' || COALESCE(TO_CHAR(T.QTDE_CONTRATOS_ATIVOS),'Não encontrado') || '|' || 
'Contratos de consórcio ativos, desconsiderando os contratos ativos adquiridos no mês calendário: ' || COALESCE(T.CONTRATOS_ATIVOS,'Não encontrado') || '|' || 
COALESCE((':DS-pm_CodGrupoProduto' || ' (' || ':NM-pm_CodGrupoProduto' || '):' || TO_CHAR(:pm_CodGrupoProduto)),'Parâmetro não cadastrado' ) || '|'   || 
CASE CD_TP_IDENTF_CLIE 
WHEN 2 THEN 
COALESCE((':DS-pm_QtdeCotasPF' || ' (' || ':NM-pm_QtdeCotasPF' || '):' || TO_CHAR(:pm_QtdeCotasPF)),'Parâmetro não cadastrado' ) || '|' ||    
COALESCE((':DS-pm_PercCotasPF' || ' (' || ':NM-pm_PercCotasPF' || '):' || TO_CHAR(:pm_PercCotasPF) || '%'),'Parâmetro não cadastrado' ) || '|' ||  
COALESCE((':DS-pm_QtdeMinimaMesPF' || ' (' || ':NM-pm_QtdeMinimaMesPF' || '):' || TO_CHAR(:pm_QtdeMinimaMesPF)),'Parâmetro não cadastrado' ) || '|'   
WHEN 3 THEN 
COALESCE((':DS-pm_QtdeCotasPJ' || ' (' || ':NM-pm_QtdeCotasPJ' || '):' || TO_CHAR(:pm_QtdeCotasPJ)),'Parâmetro não cadastrado' ) || '|' ||    
COALESCE((':DS-pm_PercCotasPJ' || ' (' || ':NM-pm_PercCotasPJ' || '):' || TO_CHAR(:pm_PercCotasPJ) || '%'),'Parâmetro não cadastrado' ) || '|' ||  
COALESCE((':DS-pm_QtdeMinimaMesPJ' || ' (' || ':NM-pm_QtdeMinimaMesPJ' || '):' || TO_CHAR(:pm_QtdeMinimaMesPJ)),'Parâmetro não cadastrado' ) || '|'  
END
AS DS_INF_ANLSE 
FROM (SELECT T.CD_MES_ANO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE,  
      SUM(CASE WHEN TO_CHAR(C.DT_CAD_CONTRATO,'YYYYMM') = T.CD_MES_ANO THEN 1 ELSE 0 END) QTDE_CONTRATOS_MES,
	  SUM(CASE WHEN TO_CHAR(C.DT_CAD_CONTRATO,'YYYYMM') < T.CD_MES_ANO THEN 1 ELSE 0 END) QTDE_CONTRATOS_ATIVOS, 
      TO_CHAR(XMLCAST(XMLAGG(XMLELEMENT(outros, CASE WHEN TO_CHAR(C.DT_CAD_CONTRATO,'YYYYMM') = T.CD_MES_ANO THEN LTRIM(C.CD_CONTRATO) || ' / ' ELSE '' END) ORDER BY C.CD_CONTRATO) as clob))  CONTRATOS_MES,  
      TO_CHAR(XMLCAST(XMLAGG(XMLELEMENT(outros, CASE WHEN TO_CHAR(C.DT_CAD_CONTRATO,'YYYYMM') < T.CD_MES_ANO THEN LTRIM(C.CD_CONTRATO) || ' / ' ELSE '' END) ORDER BY C.CD_CONTRATO) as clob))  CONTRATOS_ATIVOS  
      FROM TB_CONTRATO C   
      INNER JOIN (SELECT T.CD_MES_ANO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, MAX(T.NM_CLIE) NM_CLIE  
                  FROM TB_TRANS T  
                  WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
                  AND   T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
                  AND   T.FL_ANALISADO = 1
                  AND   T.CD_TP_OPER IN (79, 83) 
                  AND   T.CD_STTUS_CONTRATO = 1 /*ativo*/ 
                  AND   T.CD_GRP_PRODUTO = (:pm_CodGrupoProduto)
		      	  GROUP BY T.CD_MES_ANO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE  
                 ) T 
      ON C.CD_DOC_IDENTF_CLIE = T.CD_DOC_IDENTF_CLIE 
      AND C.CD_TP_IDENTF_CLIE = T.CD_TP_IDENTF_CLIE 
      AND C.CD_STTUS_CONTRATO = 1 /*ativo*/ 
      AND C.CD_GRP_PRODUTO = (:pm_CodGrupoProduto)
	  AND (C.DT_LIQUID_CONTRATO IS NULL OR C.DT_LIQUID_CONTRATO >= ADD_MONTHS((TO_DATE(TO_CHAR(:cd_lote), 'yyyy/mm')), 1))  
      AND C.DT_CAD_CONTRATO IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM TB_TRANS T1 /* PARA DESCONSIDERAR TRANSFERENICAS NO MÊS POSTERIOR */ 
                      WHERE T1.CD_DOC_IDENTF_CLIE = C.CD_DOC_IDENTF_CLIE 
                      AND T1.CD_TP_IDENTF_CLIE = C.CD_TP_IDENTF_CLIE
                      AND T1.CD_TP_OPER IN (79,83) /* AQUISIÇÃO OU TRANSFERENCIA DE TITULARIDADE */  
                      AND T1.CD_CONTRATO = C.CD_CONTRATO 
                      AND T1.NM_SIST_ORIG = C.NM_SIST_ORIG 
                      AND T1.DT_TRANS >= ADD_MONTHS((TO_DATE(TO_CHAR(:cd_lote), 'yyyy/mm')), 1) 
                     )     
	  GROUP BY T.CD_MES_ANO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE  
	 ) T 
WHERE (T.CD_TP_IDENTF_CLIE = 2 
       AND T.QTDE_CONTRATOS_MES >= (:pm_QtdeCotasPF) 
       AND ((T.QTDE_CONTRATOS_ATIVOS IS NOT NULL 
             AND (T.QTDE_CONTRATOS_MES/(T.QTDE_CONTRATOS_ATIVOS + T.QTDE_CONTRATOS_MES)) >= (:pm_PercCotasPF/100))

            OR
            (T.QTDE_CONTRATOS_ATIVOS IS NULL 
             AND T.QTDE_CONTRATOS_MES >= (:pm_QtdeMinimaMesPF))
           )
      )
OR (T.CD_TP_IDENTF_CLIE = 3 
    AND T.QTDE_CONTRATOS_MES >= (:pm_QtdeCotasPJ) 
    AND ((T.QTDE_CONTRATOS_ATIVOS IS NOT NULL 
          AND (T.QTDE_CONTRATOS_MES/(T.QTDE_CONTRATOS_ATIVOS + T.QTDE_CONTRATOS_MES)) >= (:pm_PercCotasPJ/100))
         OR 
         (T.QTDE_CONTRATOS_ATIVOS IS NULL 
         AND T.QTDE_CONTRATOS_MES >= (:pm_QtdeMinimaMesPJ))
        )
   )



