/*MENSAL*/ 
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, 
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4059 AND CD_VERSAO_SISTEMA = 4) ||'Cliente: ' || T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE 
     WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2) 
     WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2) 
     ELSE T.CD_DOC_IDENTF_CLIE 
END 
 || '|' ||  
'Mês calendário: ' || TO_CHAR(CD_MES_ANO,'YYYY-MM') || '|' || 
'Valor consolidado de crédito no mesmo POS: ' || TO_CHAR(VL_TOTAL, 'L999G999G999G990D99' ) || '|' || 
'terminal de pagamento (Point of Sale - POS): ' || TO_CHAR( NU_POS) || '|' || 
'Quantidade de transações: ' || TO_CHAR(QT_TOTAL) || '|' || 
COALESCE((SELECT DS_CAMPO_PARAM || ' (' || NM_CAMPO_PARAM || '):' || (SELECT TO_CHAR(:pm_percFaturamento) FROM DUAL) || '%'  FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4059 AND CD_VERSAO_SISTEMA = 4 AND NM_CAMPO_PARAM = 'pm_percFaturamento'),'Parâmetro não cadastrado|' ) || '|'  
AS DS_INF_ANLSE   
FROM 
(SELECT CD_MES_ANO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, MAX(VL_RENDA_FAT) VL_RENDA_FAT, SUM(VL_OPER) VL_TOTAL, COUNT(*) QT_TOTAL, NU_POS 
FROM TB_TRANS T 
WHERE DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
  AND DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
  AND FL_ANALISADO = 1   
  AND CD_TP_PESSOA = 'J' 
  AND CD_NATUR_OPER = 1  /*credito-engloba doação*/ 
  AND CD_VIA_OPER = 4 /*POS*/ 
GROUP BY CD_MES_ANO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, NU_POS ) T 
WHERE (T.VL_RENDA_FAT IS NOT NULL AND T.VL_TOTAL >= (T.VL_RENDA_FAT * ((:pm_percFaturamento) /100))
     OR
     T.VL_RENDA_FAT IS NULL)

