/* BANRISUL - MENSAL */   
/* CLIENTE */  
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,     
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4102 AND CD_VERSAO_SISTEMA = 4) ||    
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||      
'Mês/Ano: ' || SUBSTR(T.CD_MES_ANO, 5, 2) || '/' || SUBSTR(T.CD_MES_ANO, 1, 4) || '|' ||   
'Valor consolidado (crédito + débito) no mês calendário: ' || COALESCE(TO_CHAR(T.VL_TOTAL,'L999G999G999G990D99'), 'Não identificado') || '|' ||  
'Fonte: Lista CSNU - DTEC-flex|' ||   
COALESCE((':DS-pm_ValorConsolidado' || ' (' || ':NM-pm_ValorConsolidado' || '):' || TO_CHAR(:pm_ValorConsolidado, 'L999G999G999G990D99')),'Parâmetro não cadastrado' ) || '|'   
AS DS_INF_ANLSE   
FROM (SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO, MAX(T.NM_CLIE) NM_CLIE, SUM(T.VL_OPER) VL_TOTAL     
      FROM TB_TRANS T      
      WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
        AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
        AND T.FL_ANALISADO = 1   
        AND T.CD_NATUR_OPER IN (1,2)  
      GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO   
      HAVING SUM(T.VL_OPER) >= (:pm_ValorConsolidado)  
     ) T   
WHERE EXISTS (SELECT 1 FROM TB_NOTICIA_CLIE N      
              WHERE N.FL_ARMAS_DESTRUICAO_MASSA = 1  
		      AND (UPPER(N.NM_TP_SUSP) <> 'GOVERNO' AND UPPER(N.NM_TP_SUSP) <> 'SOCIOAMBIENTAL' AND UPPER(N.NM_TP_SUSP) <> 'LISTAS DIVERSAS')   
              AND N.NM_FONTE_NOTICIA LIKE '%LISTA - %'  
		      AND (N.CD_DOC_IDENTF_CLIE = T.CD_DOC_IDENTF_CLIE AND N.CD_TP_IDENTF_CLIE  = T.CD_TP_IDENTF_CLIE)  
             )     
AND NOT EXISTS (SELECT 1 FROM TB_CONTEUDO_LISTA_AUXILIAR CLA      
                WHERE CLA.DS_CONTEUDO LIKE '%' || T.CD_DOC_IDENTF_CLIE || '%'   
                AND CLA.CD_LISTA_AUXILIAR = 100 /*Lista branca*/    
               )    
UNION ALL   
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,     
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4102 AND CD_VERSAO_SISTEMA = 4) ||    
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||      
'Mês/Ano: ' || SUBSTR(T.CD_MES_ANO, 5, 2) || '/' || SUBSTR(T.CD_MES_ANO, 1, 4) || '|' ||  
'Valor consolidado (crédito + débito) no mês calendário: ' || COALESCE(TO_CHAR(T.VL_TOTAL,'L999G999G999G990D99'), 'Não identificado') || '|' ||  
'Fonte: Listas auxiliares de Armas|' ||  
COALESCE((':DS-pm_ValorConsolidado' || ' (' || ':NM-pm_ValorConsolidado' || '):' || TO_CHAR(:pm_ValorConsolidado, 'L999G999G999G990D99')),'Parâmetro não cadastrado' ) || '|'   
AS DS_INF_ANLSE   
FROM (SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO, MAX(T.NM_CLIE) NM_CLIE, SUM(T.VL_OPER) VL_TOTAL     
      FROM TB_TRANS T      
      WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
        AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)    
        AND T.FL_ANALISADO = 1   
        AND T.CD_NATUR_OPER IN (1,2)  
      GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO  
      HAVING SUM(T.VL_OPER) >= (:pm_ValorConsolidado)  
     ) T  
WHERE EXISTS (SELECT 1 FROM TB_CONTEUDO_LISTA_AUXILIAR CLA      
              WHERE CLA.DS_CONTEUDO LIKE '%' || T.CD_DOC_IDENTF_CLIE || '%'   
              AND CLA.CD_LISTA_AUXILIAR = 109 /*Lista Armas Identificacao*/    
             )  
OR (T.NM_CLIE  IS NOT NULL 
    AND 
    EXISTS (SELECT 1 FROM TB_CONTEUDO_LISTA_AUXILIAR CLA      
           WHERE CLA.DS_CONTEUDO LIKE '%' || T.NM_CLIE || '%'   
           AND CLA.CD_LISTA_AUXILIAR = 110 /*Lista Armas NOME*/    
          ) 
      )
