SELECT T.CD_DOC_IDENTF_CLIE,T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4005 AND CD_VERSAO_SISTEMA = 4) ||
'Cliente: ' ||  coalesce(T.NM_CLIE, 'Nome não informado') || '|' ||  
CASE T.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||    
'Mês de consolidação: ' || TO_CHAR(CD_MES_ANO)  || '|' ||
'Valor consolidado: ' || TO_CHAR(VL_TOTAL, 'L999G999G999G990D99') || '|' ||
'Quantidade de transações: ' || TO_CHAR(QT_TOTAL) || '|' ||
CASE CD_TP_IDENTF_CLIE 
WHEN 2 THEN
COALESCE((':DS-pm_QtdeMovtoEspecie_PF' || ' (' || ':NM-pm_QtdeMovtoEspecie_PF' || '):' || :pm_QtdeMovtoEspecie_PF),'Parâmetro não cadastrado') || '|' ||
COALESCE((':DS-pm_ValorMovtoEspecie_PF' || ' (' || ':NM-pm_ValorMovtoEspecie_PF' || '):' || TO_CHAR(:pm_ValorMovtoEspecie_PF, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|'   
WHEN 3 THEN
COALESCE((':DS-pm_QtdeMovtoEspecie_PJ' || ' (' || ':NM-pm_QtdeMovtoEspecie_PJ' || '):' || :pm_QtdeMovtoEspecie_PJ),'Parâmetro não cadastrado') || '|' ||
COALESCE((':DS-pm_ValorMovtoEspecie_PJ' || ' (' || ':NM-pm_ValorMovtoEspecie_PJ' || '):' || TO_CHAR(:pm_ValorMovtoEspecie_PJ, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|'   
END
AS DS_INF_ANLSE  
FROM
(SELECT CD_MES_ANO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, SUM(VL_OPER) VL_TOTAL, COUNT(*) QT_TOTAL
FROM TB_TRANS T
 WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
   AND CD_TP_OPER = 7 /*saque*/
   AND CD_FORMA_OPER = 7 /*especie*/
   AND FL_ANALISADO = 1  
 GROUP BY CD_MES_ANO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE
 ) T
WHERE
(CD_TP_IDENTF_CLIE = 2 AND
 QT_TOTAL >= (:pm_QtdeMovtoEspecie_PF) AND
 VL_TOTAL >= (:pm_ValorMovtoEspecie_PF))
OR
(CD_TP_IDENTF_CLIE = 3 AND
 QT_TOTAL >= (:pm_QtdeMovtoEspecie_PJ) AND
 VL_TOTAL >= (:pm_ValorMovtoEspecie_PJ))



  