select count(*) as total from
(SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE
WHERE CD_LOTE = 2014091801
  AND (CD_TP_OPER IN (4, 17)
       OR 
      (CD_TP_OPER = 7 AND CD_FORMA_OPER = 7))
  AND (NM_DESTORIG IS NULL
       OR
       CD_DOC_IDENTF_DESTORIG IS NULL)
union 
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE
WHERE CD_LOTE = 2014091801
  AND CD_TP_OPER IN (4, 5, 8, 9)
  AND (CD_DOC_TRANSACAO IS NULL OR
       CD_BCO_DESTORIG IS NULL OR
       CD_AG_DESTORIG IS NULL OR
       CD_CTA_DESTORIG IS NULL)   
union
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO
FROM TB_TRANS_ANLSE
WHERE CD_LOTE = 2014091801
  AND CD_TP_OPER = 7
  AND CD_FORMA_OPER = 12
  AND (CD_PAIS_RESID = 1058  AND (NM_BNEFC_CARTAO IS NULL OR CD_DOC_IDENTF_BNEFC IS NULL))
       OR 
      (CD_PAIS_RESID <> 1058  AND (NM_BNEFC_CARTAO IS NULL OR CD_DOC_IDENTF_BNEFC IS NULL OR CD_PAIS_PASSRTE_BNEFC IS NULL))
union
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE
WHERE CD_LOTE = 2014091801
  AND (CD_TP_OPER = 4 OR
       CD_TP_OPER = 17 OR
       (CD_TP_OPER = 7 AND CD_FORMA_OPER = 12) OR
       (CD_TP_OPER = 7 AND CD_FORMA_OPER = 7) 
        )
   AND (DT_TRANS IS NULL OR VL_OPER IS NULL)
ORDER BY 1); 
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 10