select count(*) as total from
(
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO FROM TB_TRANS_ANLSE T1
WHERE CD_LOTE = 2014091801
  AND CD_TP_OPER = 6
  AND CD_PAIS_OPER = 1058
  AND DT_PRIM_VCTO_CONTRATO IS NOT NULL
  AND DT_LIQUID IS NOT NULL
  AND ( ((TRUNC(DT_PRIM_VCTO_CONTRATO) + TRUNC(QT_MES_CONTT)-1) - trunc(DT_LIQUID))) <  
            (SELECT VL_PARAM FROM TB_REGRA_PARAMETRO WHERE CD_REGRA  = 51 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_QMes_PrazoCurto')

  			); 
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 51