select count(*) as total from
(
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE 
FROM TB_TRANS_ANLSE 
WHERE CD_TP_OPER   = 6
  AND CD_LOTE = 2014091801
  AND VL_OPER IS NOT NULL
  AND VL_PCELA_CONTRATO IS NOT NULL
  AND VL_RENDA_FAT IS NOT NULL
  AND VL_OPER > (VL_PCELA_CONTRATO * 
   (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA  = 49 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percPcela'))
  AND VL_OPER > (VL_RENDA_FAT * 
    (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA  = 49 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percRendaFat'))
  AND DT_LIQUID IS NOT NULL
  AND CD_PAIS_OPER = 1058
);   
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 49