select count(*) as total from
(SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE
WHERE CD_TP_OPER IN (4,5,8,9)
  AND 
  (
  		(
		CD_AG_DESTORIG IS NULL
		OR CD_CTA_DESTORIG IS NULL
		OR CD_DOC_IDENTF_DESTORIG IS NULL)
  	OR (
  		CD_FORMA_OPER = 2
  		AND FL_CHEQUE_ENDOSSO = 0
  		OR NM_CHEQUE_ENDOSSO IS NULL)
  )
  AND CD_LOTE = 2014091801  
union  
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE
WHERE CD_TP_PESSOA = 'F'
  AND VL_OPER IS NOT NULL
  AND VL_RENDA_FAT IS NOT NULL
  AND VL_OPER > ( VL_RENDA_FAT * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percRenda') )
  AND CD_LOTE = 2014091801  
union
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE t
WHERE CD_TP_PESSOA = 'F'
  AND exists (select * from TB_CLIE_RENDA where CD_DOC_IDENTF_CLIE = t.CD_DOC_IDENTF_CLIE and CD_TP_IDENTF_CLIE = t.CD_TP_IDENTF_CLIE)
  AND exists (select * from TB_MED_OCUP o
  			where t.VL_OPER > (o.VL_MED_CREDITO * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percOcupacao') )
  			and exists (select * from TB_CLIE_RENDA where CD_OCUP = o.CD_OCUP) )
  AND CD_LOTE = 2014091801
union
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE
WHERE CD_TP_PESSOA = 'J'
  AND (VL_OPER > (VL_RENDA_FAT * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percFat') ) )
  AND CD_LOTE = 2014091801
union
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE t
WHERE CD_TP_PESSOA = 'J'	
  AND CD_NATUR_OPER = 2
  AND exists (select * from TB_MED_RAMO_ATIVID where CD_RAMO_ATIVID = t.CD_RAMO_ATIVID and 
  			VL_OPER > (VL_RENDA_FAT * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percRamo_Ativid') ) )
  AND CD_LOTE = 2014091801
); 
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 4