select count(1) as total from
(SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE
WHERE CD_TP_OPER IN (5, 8, 9)
  AND (CD_AG_DESTORIG IS NULL OR 
       CD_CTA_DESTORIG IS NULL OR
       CD_DOC_IDENTF_DESTORIG IS NULL)
  AND CD_LOTE = 2014091801
union
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE
WHERE CD_TP_OPER = 4
     AND CD_NATUR_OPER = 2
     AND CD_FORMA_OPER = 2
     AND FL_CHEQUE_ENDOSSO = 0
	AND CD_LOTE = 2014091801
order by 1);
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 1