SELECT
CD_IDENTF_PERFIL,
DS_PERFIL,
NM_VARIAVEL_PRIMEIRA,
NM_VARIAVEL_SEGUNDA,
NM_VARIAVEL_TERCEIRA,
NM_VARIAVEL_QUARTA,
NM_FILTRO_ADICIONAL,
QT_DIA_RECUO,
CD_TP_PERFIL,
FL_ATIVO
FROM TB_VARIAVEL_PERFIL
WHERE FL_ATIVO = 1 and CD_TP_PERFIL = ? ORDER BY CD_IDENTF_PERFIL