/*DIARIO*/
SELECT LAST_DAY(TRUNC(T.DT_SAQUE)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE,T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4023 AND CD_VERSAO_SISTEMA = 4) ||
'Cliente: ' ||  coalesce(T.NM_CLIE, 'Nome não informado') || '|' ||  
CASE T.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE)  || '|' || 
'Data da recarga: '  || TO_CHAR((DT_RECARGA)) || '|' || 
'Valor da recarga: ' || TO_CHAR(VL_RECARGA, 'L999G999G999G990D99') || '|' || 
'Data do saque: '    || TO_CHAR((DT_SAQUE)) || '|' || 
'Valor do saque: '   || TO_CHAR(VL_SAQUE, 'L999G999G999G990D99') || '|' || 
COALESCE((SELECT DS_CAMPO_PARAM || ' (' || NM_CAMPO_PARAM || '):' || (SELECT TO_CHAR(:pm_percRecarga) FROM DUAL)  FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4023 AND CD_VERSAO_SISTEMA = 4 AND NM_CAMPO_PARAM = 'pm_percRecarga'),'Parâmetro não cadastrado|' ) || '|' 
AS DS_INF_ANLSE  
FROM
(
SELECT  A.CD_TRANSACAO, A.CD_LOTE, A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.DT_TRANS DT_SAQUE, A.VL_OPER VL_SAQUE, T.DT_TRANS DT_RECARGA, T.VL_OPER VL_RECARGA, T.CD_TRANSACAO
FROM TB_TRANS T
INNER JOIN
(SELECT CD_TRANSACAO, DT_TRANS, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, CD_LOTE, VL_OPER
 FROM TB_TRANS_ANLSE 
 WHERE CD_LOTE = :cd_lote AND CD_SUBLOTE = :cd_sublote
  AND CD_TP_OPER    = 7 /*saque*/
  AND CD_FORMA_OPER = 11 /*cartão pré-pago*/
  AND CD_VIA_OPER   = 1 /*atm*/
 ) A 
 ON   TRUNC(T.DT_TRANS) = TRUNC(A.DT_TRANS)
  AND T.DT_TRANS < A.DT_TRANS
  AND T.CD_DOC_IDENTF_CLIE = A.CD_DOC_IDENTF_CLIE
  AND T.CD_TP_IDENTF_CLIE  = A.CD_TP_IDENTF_CLIE
WHERE T.FL_ANALISADO = 1 
  AND T.CD_TP_OPER = 26 /*Recarga de cartão pré-pago*/
  AND A.VL_OPER <= (T.VL_OPER * (1 + (:pm_percRecarga/100)))
  AND A.VL_OPER >= (T.VL_OPER * (:pm_percRecarga/100))
  ) T
 
 
 