INSERT INTO TB_EVENTO
(CD_EVENTO,CD_TP_IDENTF_CLIE,CD_DOC_IDENTF_CLIE,DT_APONTAMENTO,DT_EVENTO,CD_STTUS_EVENTO,CD_USU,FL_CADSTR_DESATULZ,CD_LOTE_APONTAMENTO)
VALUES
(SQ_EVENTO.NEXTVAL,?,?,?,?,0,0,0,?)
