SELECT 
DT_APONTAMENTO,
CD_DOC_IDENTF_CLIE,
CD_TP_IDENTF_CLIE,
CD_STTUS_EVENTO_ATUAL,
VL_APONTAMENTO,
VL_PONTO_CORTE,
DT_ATUALZ_CALCULO,
FL_CARENCIA,
FL_PONTO_CORTE,
FL_SUSP_LD,
CD_LOTE 
FROM TB_APONTAMENTO
WHERE 
	CD_STTUS_EVENTO_ATUAL NOT IN (
		SELECT CD_STTUS_EVENTO FROM TB_STTUS_EVENTO WHERE FL_FIM_INVTGA = 1 AND CD_STTUS_EVENTO NOT IN (1,30)
	)