SELECT 
CD_IDENTF_SIMULA,
CD_DOC_IDENTF_CLIE,
CD_TP_IDENTF_CLIE,
VL_APONTAMENTO,
VL_PONTO_CORTE,
FL_SUSP_LD,
CD_LOTE 
FROM TB_APONTAMENTO_SIMULA a
WHERE 
CD_IDENTF_SIMULA = ? AND 
EXISTS (
	SELECT 1 FROM TB_TRANS_ANLSE 
	WHERE 
		CD_DOC_IDENTF_CLIE = a.CD_DOC_IDENTF_CLIE AND 
		CD_TP_IDENTF_CLIE = a.CD_TP_IDENTF_CLIE AND 
		CD_LOTE = ?
	)