SELECT 
COUNT(1)
FROM TB_APONTAMENTO_SIMULA a
WHERE 
CD_IDENTF_SIMULA = ? AND 
EXISTS (
	SELECT 1 FROM TB_TRANS_ANLSE 
	WHERE 
		CD_DOC_IDENTF_CLIE = a.CD_DOC_IDENTF_CLIE AND 
		CD_TP_IDENTF_CLIE = a.CD_TP_IDENTF_CLIE AND 
		CD_LOTE = ?
	)