INSERT INTO TB_APONTAMENTO_HIST
(DT_APONTAMENTO,CD_DOC_IDENTF_CLIE,CD_TP_IDENTF_CLIE,CD_STTUS_EVENTO_ATUAL,VL_APONTAMENTO,VL_PONTO_CORTE,DT_ATUALZ_CALCULO,FL_CARENCIA,FL_PONTO_CORTE,FL_SUSP_LD,CD_USU,CD_LOTE,DT_HISTORICO,DT_ULTM_PARECER)
SELECT DT_APONTAMENTO,CD_DOC_IDENTF_CLIE,CD_TP_IDENTF_CLIE,CD_STTUS_EVENTO_ATUAL,VL_APONTAMENTO,VL_PONTO_CORTE,DT_ATUALZ_CALCULO,FL_CARENCIA,FL_PONTO_CORTE,FL_SUSP_LD,CD_USU,CD_LOTE,SYSTIMESTAMP AS DT_HISTORICO,DT_ULTM_PARECER 
FROM TB_APONTAMENTO
WHERE CD_STTUS_EVENTO_ATUAL = 2 AND DT_APONTAMENTO < TO_DATE(':cd_lote','YYYYMM');

INSERT INTO TB_DETLH_APONTAMENTO_HIST
(ID_DETLH_APONTAMENTO,DT_APONTAMENTO,CD_DOC_IDENTF_CLIE,CD_TP_IDENTF_CLIE,CD_CLASSE_REGRA,CD_REGRA,CD_VERSAO_SISTEMA,CD_TRANSACAO,DS_INF_ANLSE,DT_DISP_REGRA,CD_LOTE,DT_HISTORICO,VL_PONTO,CD_LOTE_APONTAMENTO)
SELECT ID_DETLH_APONTAMENTO,DT_APONTAMENTO,CD_DOC_IDENTF_CLIE,CD_TP_IDENTF_CLIE,CD_CLASSE_REGRA,CD_REGRA,CD_VERSAO_SISTEMA,CD_TRANSACAO,DS_INF_ANLSE,DT_DISP_REGRA,CD_LOTE,SYSTIMESTAMP AS DT_HISTORICO,VL_PONTO,CD_LOTE_APONTAMENTO 
FROM TB_DETLH_APONTAMENTO D
WHERE EXISTS (
	SELECT 1 FROM TB_APONTAMENTO A
	WHERE A.DT_APONTAMENTO = D.DT_APONTAMENTO
		AND A.CD_DOC_IDENTF_CLIE = D.CD_DOC_IDENTF_CLIE
		AND A.CD_TP_IDENTF_CLIE = D.CD_TP_IDENTF_CLIE
		AND A.CD_LOTE = D.CD_LOTE_APONTAMENTO
		AND A.CD_STTUS_EVENTO_ATUAL = 2 AND A.DT_APONTAMENTO < TO_DATE(':cd_lote','YYYYMM')
);

INSERT INTO TB_EVENTO_HIST
(CD_EVENTO,DT_APONTAMENTO,CD_DOC_IDENTF_CLIE,CD_TP_IDENTF_CLIE,TX_MSG,CD_USU,CD_STTUS_EVENTO,TX_ARQUIVO_COMPL,NM_ARQUIVO_COMPL,DT_EVENTO,FL_CADSTR_DESATULZ,FL_RECUSA_ATULZ_CADSTR,NM_MIME_TYPE_ARQ_COMPL,DT_HISTORICO,CD_LOTE_APONTAMENTO)
SELECT CD_EVENTO,DT_APONTAMENTO,CD_DOC_IDENTF_CLIE,CD_TP_IDENTF_CLIE,TX_MSG,CD_USU,CD_STTUS_EVENTO,TX_ARQUIVO_COMPL,NM_ARQUIVO_COMPL,DT_EVENTO,FL_CADSTR_DESATULZ,FL_RECUSA_ATULZ_CADSTR,NM_MIME_TYPE_ARQ_COMPL,SYSTIMESTAMP AS DT_HISTORICO,CD_LOTE_APONTAMENTO 
FROM TB_EVENTO E
WHERE EXISTS (
	SELECT 1 FROM TB_APONTAMENTO A
	WHERE A.DT_APONTAMENTO = E.DT_APONTAMENTO
		AND A.CD_DOC_IDENTF_CLIE = E.CD_DOC_IDENTF_CLIE
		AND A.CD_TP_IDENTF_CLIE = E.CD_TP_IDENTF_CLIE
		AND A.CD_LOTE = E.CD_LOTE_APONTAMENTO
		AND A.CD_STTUS_EVENTO_ATUAL = 2 AND A.DT_APONTAMENTO < TO_DATE(':cd_lote','YYYYMM')
);

DELETE FROM TB_EVENTO E WHERE EXISTS (
	SELECT 1 FROM TB_APONTAMENTO A
	WHERE A.DT_APONTAMENTO = E.DT_APONTAMENTO
		AND A.CD_DOC_IDENTF_CLIE = E.CD_DOC_IDENTF_CLIE
		AND A.CD_TP_IDENTF_CLIE = E.CD_TP_IDENTF_CLIE
		AND A.CD_LOTE = E.CD_LOTE_APONTAMENTO
		AND A.CD_STTUS_EVENTO_ATUAL = 2 AND A.DT_APONTAMENTO < TO_DATE(':cd_lote','YYYYMM')
);

DELETE FROM TB_DETLH_APONTAMENTO D WHERE EXISTS (
	SELECT 1 FROM TB_APONTAMENTO A
	WHERE A.DT_APONTAMENTO = D.DT_APONTAMENTO
		AND A.CD_DOC_IDENTF_CLIE = D.CD_DOC_IDENTF_CLIE
		AND A.CD_TP_IDENTF_CLIE = D.CD_TP_IDENTF_CLIE
		AND A.CD_LOTE = D.CD_LOTE_APONTAMENTO
		AND A.CD_STTUS_EVENTO_ATUAL = 2 AND A.DT_APONTAMENTO < TO_DATE(':cd_lote','YYYYMM')
);

DELETE FROM TB_APONTAMENTO WHERE CD_STTUS_EVENTO_ATUAL = 2 AND DT_APONTAMENTO < TO_DATE(':cd_lote','YYYYMM');