SELECT
C.CD_DOC_IDENTF_CLIE,
C.CD_TP_IDENTF_CLIE,
C.CD_TP_PESSOA,
C.NM_CLIE,
C.CD_CEP_RESID,
C.NM_ENDER_RESID,
C.NM_CID_RESID,
C.SG_UF_RESID,
C.CD_PAIS_RESID,
C.NM_MAE,
C.NM_PAI,
C.NM_CONJUGE
FROM TB_CAD_CLIE C
JOIN TB_TRANS_ANLSE T 
	ON 
		 T.NM_ENDER_RESID    IS NOT NULL AND
		 T.CD_CEP_RESID        IS NOT NULL AND
		 C.NM_ENDER_RESID    IS NOT NULL AND
		 C.CD_CEP_RESID        IS NOT NULL AND
		 C.CD_DOC_IDENTF_CLIE + CAST(C.CD_TP_IDENTF_CLIE AS VARCHAR) <> T.CD_DOC_IDENTF_CLIE + CAST(T.CD_TP_IDENTF_CLIE AS VARCHAR) AND
		 C.NM_ENDER_RESID       = T.NM_ENDER_RESID AND
		 C.CD_CEP_RESID           = T.CD_CEP_RESID AND
		 T.CD_LOTE = ? AND
		 T.CD_SUBLOTE = ?
GROUP BY
C.CD_DOC_IDENTF_CLIE,
C.CD_TP_IDENTF_CLIE,
C.CD_TP_PESSOA,
C.NM_CLIE,
C.CD_CEP_RESID,
C.NM_ENDER_RESID,
C.NM_CID_RESID,
C.SG_UF_RESID,
C.CD_PAIS_RESID,
C.NM_MAE,
C.NM_PAI,
C.NM_CONJUGE