
select count(*) as total from
( 
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO
FROM TB_TRANS_ANLSE
WHERE CD_TP_PESSOA = 'F'
  AND VL_OPER is not null
  AND VL_RENDA_FAT is not null
  AND VL_OPER > ( VL_RENDA_FAT * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percRenda') )
  AND CD_LOTE = 2014091801    
union
SELECT DISTINCT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_TRANSACAO
FROM TB_TRANS_ANLSE T, TB_CLIE_RENDA R, TB_MED_OCUP M
WHERE T.CD_LOTE = 2014091801
  AND T.CD_TP_PESSOA = 'F'
  AND T.CD_DOC_IDENTF_CLIE = R.CD_DOC_IDENTF_CLIE
  AND T.CD_TP_IDENTF_CLIE = R.CD_TP_IDENTF_CLIE
  AND R.CD_OCUP = M.CD_OCUP
  AND T.VL_OPER > (M.VL_MED_CREDITO * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percOcupacao') )  
union
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO
FROM TB_TRANS_ANLSE
WHERE CD_TP_PESSOA = 'J'
  AND (VL_OPER > (VL_RENDA_FAT * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percFat') ) )
  AND CD_LOTE = 2014091801
union
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_TRANSACAO
FROM TB_TRANS_ANLSE T, TB_MED_RAMO_ATIVID M
WHERE T.CD_LOTE = 2014091801
  AND T.CD_TP_PESSOA = 'J'
  AND T.CD_RAMO_ATIVID = M.CD_RAMO_ATIVID
  AND T.VL_OPER > (M.VL_MED_CREDITO * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percRamo_Ativid') )  
  ) s;
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 4

