select count(1) as total from
(
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE
WHERE CD_TP_CLIE = 2 
  AND CD_TP_OPER IN (5,8,9)
  AND (CD_AG_DESTORIG IS NULL
       OR CD_CTA_DESTORIG IS NULL
       OR CD_DOC_IDENTF_DESTORIG IS NULL
       OR NM_CLIE IS NULL)
  AND CD_LOTE = 2014091801
union
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO 
FROM TB_TRANS_ANLSE
WHERE CD_TP_CLIE = 2 
  AND CD_FORMA_OPER = 2 
  AND (FL_CHEQUE_ENDOSSO = 0
       OR NM_CHEQUE_ENDOSSO IS NULL)
  AND CD_LOTE = 2014091801
) s;        
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 3