/*c) negociações de moeda estrangeira em espécie ou cheques de viagem denominados em moeda estrangeira, que Não apresentem compatibilidade com a natureza declarada da operação;*/  
  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4016 AND CD_VERSAO_SISTEMA = 4) ||     
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Natureza da Transação: ' ||    
CASE T.CD_NATUR_OPER   
	 WHEN 1 THEN 'Crédito'   
	 WHEN 2 THEN 'Débito'   
	 WHEN 3 THEN 'Evento'   
	 ELSE 'Natureza não cadastrada'   
END || '|' ||   
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||   
'Valor Médio da natureza declarada ' || COALESCE(N.DS_NATUR_DECLR_OPER, TO_CHAR(t.CD_NATUR_DECLR_OPER)) || ': ' || TO_CHAR(VL_MEDIO_NATUR_OPER, 'L999G999G999G990D99') || '|' || 
COALESCE((':DS-pm_ValorMinimo' || ' (' || ':NM-pm_ValorMinimo' || '):' || TO_CHAR(:pm_ValorMinimo, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' ||
COALESCE((':DS-pm_PercNaturOper' || ' (' || ':NM-pm_PercNaturOper' || '):' || :pm_PercNaturOper || '%'),'Parâmetro não cadastrado') || '|'
AS DS_INF_ANLSE     
FROM TB_TRANS_ANLSE T 
INNER JOIN TB_NATUR_DECLR_OPER N ON T.CD_NATUR_DECLR_OPER = N.CD_NATUR_DECLR_OPER
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote   
  AND T.CD_FORMA_OPER = 8   
  AND T.VL_OPER IS NOT NULL   
  AND T.VL_OPER > (:pm_ValorMinimo)    
  AND N.VL_MEDIO_NATUR_OPER IS NOT NULL   
  AND T.VL_OPER >= (N.VL_MEDIO_NATUR_OPER * (:pm_PercNaturOper/100))   

      