SELECT LAST_DAY(T.DT_DEBITO) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,  
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4067 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' || T.NM_CLIE || '|' ||  
CASE T.CD_TP_IDENTF_CLIE  
     WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
     WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)  
     ELSE T.CD_DOC_IDENTF_CLIE  
END  
 || '|' ||   
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Valor do crédito em ' || TO_CHAR(DT_CREDITO) || ': ' || TO_CHAR(VL_CREDITO, 'L999G999G999G990D99')   || '|' ||  
'Valor do débito em ' || TO_CHAR(DT_DEBITO) || ': '  || TO_CHAR(VL_DEBITO, 'L999G999G999G990D99')   || '|' ||  
COALESCE((':DS-pm_PercFaixaInferior' || ' (' || ':NM-pm_PercFaixaInferior' || '):' || :pm_PercFaixaInferior || '%'),'Parâmetro não cadastrado' ) || '|' ||   
COALESCE((':DS-pm_PercFaixaSuperior' || ' (' || ':NM-pm_PercFaixaSuperior' || '):' || :pm_PercFaixaSuperior || '%'),'Parâmetro não cadastrado' ) || '|'    
AS DS_INF_ANLSE    
FROM (SELECT D.CD_DOC_IDENTF_CLIE, D.CD_TP_IDENTF_CLIE, D.NM_CLIE, D.CD_LOTE, D.DT_DEBITO, D.VL_DEBITO, C.DT_CREDITO, C.VL_CREDITO  
      FROM (SELECT D.CD_LOTE, D.CD_DOC_IDENTF_CLIE, D.CD_TP_IDENTF_CLIE, TO_CHAR(D.DT_TRANS,'DD/MM/YYYY') DT_DEBITO, MAX(D.NM_CLIE) NM_CLIE, SUM(D.VL_OPER) VL_DEBITO  
            FROM TB_TRANS_ANLSE D   
            WHERE D.CD_LOTE = :cd_lote  
            AND D.CD_SUBLOTE = :cd_sublote  
            AND D.CD_NATUR_OPER = 2  
            GROUP BY D.CD_LOTE, D.CD_DOC_IDENTF_CLIE, D.CD_TP_IDENTF_CLIE, TO_CHAR(D.DT_TRANS,'DD/MM/YYYY') 
           ) D 
      INNER JOIN (SELECT C.CD_DOC_IDENTF_CLIE, C.CD_TP_IDENTF_CLIE, TO_CHAR(C.DT_TRANS,'DD/MM/YYYY') DT_CREDITO, SUM(C.VL_OPER) VL_CREDITO   
                  FROM TB_TRANS_ANLSE C   
                  WHERE C.CD_NATUR_OPER = 1   
                  GROUP BY C.CD_DOC_IDENTF_CLIE, C.CD_TP_IDENTF_CLIE, TO_CHAR(C.DT_TRANS,'DD/MM/YYYY')   
                 ) C 
      ON D.CD_DOC_IDENTF_CLIE = C.CD_DOC_IDENTF_CLIE     
      AND D.CD_TP_IDENTF_CLIE = C.CD_TP_IDENTF_CLIE                                 
      AND C.DT_CREDITO = D.DT_DEBITO     
      WHERE C.VL_CREDITO IS NOT NULL  
      AND D.VL_DEBITO IS NOT NULL  
      AND D.VL_DEBITO >= (C.VL_CREDITO  * (:pm_PercFaixaInferior/100))  
      AND D.VL_DEBITO <= (C.VL_CREDITO * (:pm_PercFaixaSuperior/100))  
     ) T  
