/* BANRISUL - DIÁRIA */ 
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4091 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da Quitação do Contrato: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Sistema de Origem do Contrato: ' || COALESCE(T.NM_SIST_ORIG, 'Não cadastrado') || '|' || 
'Contrato: ' || COALESCE(T.CD_CONTRATO, 'Não cadastrado') || '|' || 
'Status do Contrato: Contemplado |' ||
'Data da Aquisição ou Transferência do Contrato contemplado: ' || TO_CHAR(T1.DT_TRANS,'DD/MM/YYYY') || '|' ||  
COALESCE((':DS-pm_QtdeDias' || ' (' || ':NM-pm_QtdeDias' || '):' || :pm_QtdeDias),'Parâmetro não cadastrado' ) || '|'  ||  
COALESCE((':DS-pm_CodGrupoProduto' || ' (' || ':NM-pm_CodGrupoProduto' || '):' || :pm_CodGrupoProduto),'Parâmetro não cadastrado' ) || '|'     
AS DS_INF_ANLSE      
FROM TB_TRANS T1 
INNER JOIN (SELECT T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE, T.CD_CONTRATO, T.NM_SIST_ORIG, T.CD_TP_OPER, T.DT_TRANS  
            FROM TB_TRANS_ANLSE T   
            WHERE T.CD_TP_OPER = 82 /*Quitação do contrato*/ 
            AND T.CD_GRP_PRODUTO = (:pm_CodGrupoProduto)	 
            AND T.CD_STTUS_CONTRATO = 1 /*ativo*/
            AND T.CD_LOTE    = :cd_lote 
            AND T.CD_SUBLOTE = :cd_sublote  
            AND EXISTS (SELECT 1 FROM TB_CONTRATO C WHERE C.CD_CONTRATO = T.CD_CONTRATO AND C.NM_SIST_ORIG = T.NM_SIST_ORIG AND C.CD_SIT_CONSORCIO = 1) 
            GROUP BY T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE, T.CD_CONTRATO, T.NM_SIST_ORIG, T.CD_TP_OPER, T.DT_TRANS   
           ) T 
ON  T1.CD_DOC_IDENTF_CLIE = T.CD_DOC_IDENTF_CLIE   
AND T1.CD_TP_IDENTF_CLIE  = T.CD_TP_IDENTF_CLIE      
AND T1.CD_CONTRATO        = T.CD_CONTRATO          
AND T1.NM_SIST_ORIG       = T.NM_SIST_ORIG       
AND T1.DT_TRANS < T.DT_TRANS     
AND (TRUNC(T.DT_TRANS) - TRUNC(T1.DT_TRANS)) <= (:pm_QtdeDias)  
AND T1.CD_STTUS_CONTRATO = 1 /*ativo*/
AND T1.CD_TP_OPER IN (79, 83) /*Proposta de Adesão (Aquisição) ou Transferência de Titularidade */ 
AND T1.FL_ANALISADO = 1 


