SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4115 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||  
'Tipo da Transação: ' || COALESCE((SELECT NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Descrição não cadastrada') || '|' || 
'Data da Transação: ' || COALESCE(TO_CHAR(T.DT_TRANS,'DD/MM/YYYY'),'Não cadastrada') || '|' || 
'Valor da Transação:' || COALESCE(TO_CHAR(T.VL_OPER, 'L999G999G999G990D99'), 'Não cadastrado') || '|' || 
'Endereço do Cliente: ' || COALESCE(T.NM_ENDER_RESID,'Não cadastrado') || '|' || 
'CEP do Cliente: ' || COALESCE(TO_CHAR(T.CD_CEP_RESID),'Não cadastrado') || '|' || 
'Telefone do Cliente: ' || COALESCE(TO_CHAR(T.CD_FONE_CLIE),'Não cadastrado') || '|' || 
'Período de avaliação: De '|| COALESCE(TO_CHAR(T.DT_TRANS - (SELECT VL_PARAM FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4115 AND CD_VERSAO_SISTEMA = 4 AND NM_CAMPO_PARAM = 'pm_QtdeDias'),'DD/MM/YYYY'), 'Não cadastrada')  
|| ' até ' || COALESCE(TO_CHAR(T.DT_TRANS,'DD/MM/YYYY'),'Não cadastrada') || '|' || 
'Quantidade de clientes encontrados no período analisado:' || COALESCE(TO_CHAR(T.QTDE_TRANS, '999G999G999G990D99'), 'Não identificado') || '|' || 
'Representante do cliente: ' || COALESCE(TO_CHAR(T.CD_DOC_IDENTF_REPRE || ' - ' || T.NM_REPRE),'Não possui representante') || '|' || 
'Lista com os demais clientes que realizaram transações com os mesmos critérios:' || T.LISTA_DOC || '|' || 
COALESCE((':DS-pm_CodBrasil' || ' (' || ':NM-pm_CodBrasil' || '):' || :pm_CodBrasil),'Parâmetro não cadastrado' ) || '|' ||  
COALESCE((':DS-pm_PercValorInferior' || ' (' || ':NM-pm_PercValorInferior' || '):' || :pm_PercValorInferior || '%'),'Parâmetro não cadastrado' ) || '|' ||  
COALESCE((':DS-pm_PercValorSuperior' || ' (' || ':NM-pm_PercValorSuperior' || '):' || :pm_PercValorSuperior || '%'),'Parâmetro não cadastrado' ) || '|' ||  
COALESCE((':DS-pm_QtdeTransacoes' || ' (' || ':NM-pm_QtdeTransacoes' || '):' || :pm_QtdeTransacoes),'Parâmetro não cadastrado' ) || '|' ||  
COALESCE((':DS-pm_QtdeDias' || ' (' || ':NM-pm_QtdeDias' || '):' || :pm_QtdeDias),'Parâmetro não cadastrado' ) || '|'  
AS DS_INF_ANLSE 
FROM (SELECT T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.DT_TRANS, T.CD_TP_OPER, T.VL_OPER, T.NM_ENDER_RESID, 
	  T.CD_FONE_CLIE, T.CD_CEP_RESID, T.NM_CLIE, T.CD_DOC_IDENTF_REPRE, T.NM_REPRE, COUNT(*) QTDE_TRANS, 
      xmlcast(xmlagg(xmlelement(outros, TO_CHAR(T1.CD_DOC_IDENTF_CLIE) || '/End ' || COALESCE(T1.NM_ENDER_RESID,'Não informado') || 
      '/CEP ' || COALESCE(TO_CHAR(T1.CD_CEP_RESID),'Não informado') || '/Fone ' || COALESCE(TO_CHAR(T1.CD_FONE_CLIE),'Não informado') || ', ') order by T1.CD_DOC_IDENTF_CLIE) as clob) LISTA_DOC  
      FROM TB_TRANS T1 
      INNER JOIN (SELECT T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.DT_TRANS, T.CD_TP_OPER, T.VL_OPER, T.NM_ENDER_RESID, 
                  T.CD_FONE_CLIE, T.CD_CEP_RESID, T.NM_CLIE, TR.CD_DOC_IDENTF_REPRE, TR.NM_REPRE   
	              FROM TB_TRANS_ANLSE T  
			      LEFT JOIN TB_TRANSMISSAO_ORDEM TR 
			      ON T.CD_DOC_IDENTF_CLIE = TR.CD_DOC_IDENTF_CLIE 
			      AND T.CD_TP_IDENTF_CLIE = TR.CD_TP_IDENTF_CLIE 
			      WHERE T.CD_LOTE = :cd_lote 
                  AND T.CD_SUBLOTE = :cd_sublote 
			      AND T.DT_TRANS IS NOT NULL 
			      AND T.VL_OPER IS NOT NULL 
			      AND ((T.CD_PAIS_DESTORIG IS NOT NULL AND 
			            T.CD_PAIS_DESTORIG <> (:pm_CodBrasil)) 
			           OR
			           (T.CD_PAIS_OPER IS NOT NULL AND
				        T.CD_PAIS_OPER <> (:pm_CodBrasil))  
				      )
		         ) T 
      ON T1.DT_TRANS IS NOT NULL  
	  AND T1.DT_TRANS >= TO_DATE(T.DT_TRANS - (:pm_QtdeDias))  
	  AND T1.DT_TRANS <= T.DT_TRANS 
      AND T1.CD_DOC_IDENTF_CLIE <> T.CD_DOC_IDENTF_CLIE 
	  AND T1.VL_OPER >= (T.VL_OPER * (:pm_PercValorInferior/100))
	  AND T1.VL_OPER <= (T.VL_OPER * (:pm_PercValorSuperior/100))
      AND ((T1.CD_PAIS_DESTORIG IS NOT NULL AND 
	        T1.CD_PAIS_DESTORIG <> (:pm_CodBrasil)) 
	       OR
	       (T1.CD_PAIS_OPER IS NOT NULL AND
	        T1.CD_PAIS_OPER <> (:pm_CodBrasil))  
	       )
	  AND ((T1.NM_ENDER_RESID IS NOT NULL AND T.NM_ENDER_RESID IS NOT NULL AND 
	        T1.CD_CEP_RESID   IS NOT NULL AND T.CD_CEP_RESID   IS NOT NULL AND 
	        T1.NM_ENDER_RESID = T.NM_ENDER_RESID AND T1.CD_CEP_RESID = T.CD_CEP_RESID) 
	       OR
	       (T1.CD_FONE_CLIE IS NOT NULL AND T.CD_FONE_CLIE IS NOT NULL AND
	        T1.CD_FONE_CLIE = T.CD_FONE_CLIE 
           )
	       OR
		   (T.CD_DOC_IDENTF_REPRE IS NOT NULL AND 
		    EXISTS(SELECT 1 FROM TB_TRANSMISSAO_ORDEM TR 
		           WHERE TR.CD_DOC_IDENTF_REPRE = T.CD_DOC_IDENTF_REPRE
		           AND TR.CD_DOC_IDENTF_CLIE <> T.CD_DOC_IDENTF_CLIE) 
           )
	   )  
       GROUP BY T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.DT_TRANS, T.CD_TP_OPER, T.VL_OPER, T.NM_ENDER_RESID, 
	   T.CD_FONE_CLIE, T.CD_CEP_RESID, T.NM_CLIE, T.CD_DOC_IDENTF_REPRE, T.NM_REPRE 
      ) T 
WHERE T.QTDE_TRANS >= (:pm_QtdeTransacoes) 

