/* BANRISUL - DIARIA - FALTA CAMPO CD_TP_CREDOR, CD_PAIS_CONTRATO E CD_DOC_IDENTF_CREDOR */ 
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4124 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da Transação: ' || COALESCE(TO_CHAR(T.DT_TRANS,'DD/MM/YYYY'),'Não cadastrada') || '|' || 
'Tipo da Transação: Operação de Crédito|' || 
'Tipo do Credor: Instituição Financeira Internacional| ' || 
COALESCE((':DS-pm_CodBrasil' || ' (' || ':NM-pm_CodBrasil' || '):' || :pm_CodBrasil),'Parâmetro não cadastrado' ) || '|'     
AS DS_INF_ANLSE 
FROM (SELECT T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.DT_TRANS, MAX(T.NM_CLIE) NM_CLIE  
      FROM TB_TRANS_ANLSE T 
      WHERE T.CD_LOTE = :cd_lote 
      AND T.CD_SUBLOTE = :cd_sublote
      AND T.CD_TP_OPER = 20 /* Operação de crédito */ 
	  AND T.CD_TP_CREDOR = 2 /* Instituição financeira internacional */ 
	  AND T.CD_DOC_IDENTF_CREDOR IS NULL 
	  AND T.CD_PAIS_CONTRATO <> (:pm_CodBrasil)
	  GROUP BY T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.DT_TRANS  
	 ) T 


