SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4006 AND CD_VERSAO_SISTEMA = 4) || 
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Banco: ' || COALESCE((SELECT NM_BANCO FROM TB_BANCO B WHERE B.CD_BANCO = T.CD_BANCO),TO_CHAR(T.CD_BANCO)) || '|' ||   
'Agência: ' || COALESCE((SELECT NM_AG FROM TB_AGENCIA A WHERE A.CD_AG = T.CD_AG),TO_CHAR(T.CD_AG)) || '|' ||  
'Conta: ' || TO_CHAR(T.CD_CTA) || '|' ||
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Período de análise: de ' || to_char((t.DT_TRANS - (SELECT VL_PARAM FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 4006 AND CD_VERSAO_SISTEMA = 4 AND NM_CAMPO_PARAM = 'pm_QtdeDiaRecuo'))) || ' até ' || TO_CHAR(trunc(T.DT_TRANS)) || '|' ||   
'Valor total: ' || TO_CHAR(T.VL_TOTAL, 'L999G999G999G990D99') || '|'  ||    
'Quantidade de transação: ' || TO_CHAR(T.QT_TOTAL) || '|'  ||    
'Agência da Transação: ' || COALESCE(COALESCE((SELECT NM_AG FROM TB_AGENCIA A WHERE A.CD_AG = T.CD_AG_OPER),TO_CHAR(T.CD_AG_OPER)),'Agência da transação não cadastrada') || '|' ||   
'CEP da agência da Transação: ' || COALESCE(COALESCE((SELECT NM_AG FROM TB_AGENCIA A WHERE A.CD_AG = T.CD_CEP_AG_OPER),TO_CHAR(T.CD_CEP_AG_OPER)),'Cep da agência da transação não cadastrado') || '|' ||   

COALESCE((':DS-pm_QtdeDiaRecuo' || ' (' || ':NM-pm_QtdeDiaRecuo' || '):' || :pm_QtdeDiaRecuo),'Parâmetro não cadastrado') || '|' ||
COALESCE((':DS-pm_ValorDepEspecie_PF' || ' (' || ':NM-pm_ValorDepEspecie_PF' || '):' || TO_CHAR(:pm_ValorDepEspecie_PF, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' ||
COALESCE((':DS-pm_ValorDepEspecie_PJ' || ' (' || ':NM-pm_ValorDepEspecie_PJ' || '):' || TO_CHAR(:pm_ValorDepEspecie_PJ, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' 
AS DS_INF_ANLSE   
FROM (
SELECT A.DT_TRANS, A.NM_CLIE, A.CD_LOTE, A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.CD_BANCO, A.CD_AG, A.CD_CTA, A.CD_AG_OPER, A.CD_CEP_AG_OPER, SUM(T.VL_OPER) VL_TOTAL, COUNT(*) QT_TOTAL 
FROM TB_TRANS T
INNER JOIN 
(SELECT TRUNC(T.DT_TRANS) DT_TRANS, T.NM_CLIE, T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_BANCO, T.CD_AG, T.CD_CTA, T.CD_AG_OPER, T.CD_CEP_AG_OPER
 FROM TB_TRANS_ANLSE T    
 WHERE T.CD_LOTE       = :cd_lote     
   AND T.CD_SUBLOTE    = :cd_sublote    
   AND T.CD_FORMA_OPER = 7   
   AND T.CD_NATUR_OPER = 1  
   AND T.CD_AG_OPER   IS NOT NULL   
   AND T.VL_OPER      IS NOT NULL 
 GROUP BY T.DT_TRANS, T.NM_CLIE, T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_BANCO, T.CD_AG, T.CD_CTA, T.CD_AG_OPER, T.CD_CEP_AG_OPER
 ) A
 ON T.CD_DOC_IDENTF_CLIE = A.CD_DOC_IDENTF_CLIE AND 
    T.CD_TP_IDENTF_CLIE  = A.CD_TP_IDENTF_CLIE  AND
    T.DT_TRANS >= (A.DT_TRANS - (:pm_QtdeDiaRecuo)) AND
    T.DT_TRANS <= A.DT_TRANS
WHERE A.CD_AG_OPER = T.CD_AG_OPER
   OR A.CD_CEP_AG_OPER = T.CD_CEP_AG_OPER 
GROUP BY A.DT_TRANS, A.NM_CLIE, A.CD_LOTE, A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.CD_BANCO, A.CD_AG, A.CD_CTA, A.CD_AG_OPER, A.CD_CEP_AG_OPER
) T  
WHERE
(CD_TP_IDENTF_CLIE = 2 AND
 VL_TOTAL > (:pm_ValorDepEspecie_PF))
OR
(CD_TP_IDENTF_CLIE = 3 AND
 VL_TOTAL > (:pm_ValorDepEspecie_PJ))
