/* BANRISUL - DIÁRIO */ 
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4093 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' || 
'Tipo da Transação: ' || COALESCE((SELECT NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Descrição não cadastrada') || '|' || 
'Sistema de Origem do Contrato: ' || COALESCE(T.NM_SIST_ORIG, 'Não cadastrado') || '|' || 
'Contrato: ' || COALESCE(T.CD_CONTRATO, 'Não cadastrado') || '|'  || 
'Cidade de Residência: ' || COALESCE(T.NM_CID_RESID, 'Não cadastrado') || '|'  || 
'Cidade da Transação: ' || COALESCE(T.NM_CID_OPER, 'Não cadastrado') || '|'  || 
COALESCE((':DS-pm_CodGrupoProduto' || ' (' || ':NM-pm_CodGrupoProduto' || '):' || :pm_CodGrupoProduto),'Parâmetro não cadastrado' ) || '|'     
AS DS_INF_ANLSE      
FROM TB_TRANS_ANLSE T   
WHERE T.CD_LOTE  = :cd_lote 
AND T.CD_SUBLOTE = :cd_sublote  
AND T.CD_TP_OPER = 66 /*Pagamento de Parcela de Consorcio*/ 
AND T.CD_GRP_PRODUTO = (:pm_CodGrupoProduto)	      	  
AND T.NM_CID_RESID IS NOT NULL 
AND T.NM_CID_OPER IS NOT NULL 
AND T.NM_CID_RESID <> T.NM_CID_OPER 

