/* 4090 */ 
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,     
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4090 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||     
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da Antecipação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||  
'Valor da Renda: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Não cadastrado') || '|' || 
'Valor total das antecipações no mês calendário: ' || COALESCE(TO_CHAR(T.VALOR_TOTAL, 'L999G999G999G990D99'), 'Não cadastrado') || '|' || 
'Quantidade de parcelas antecipadas no mês calendário: ' || COALESCE(TO_CHAR(T.QTDE_PARCELAS_ANTECIPADAS), 'Não cadastrado') || '|' || 
COALESCE((':DS-pm_PercRenda' || ' (' || ':NM-pm_PercRenda' || '):' || TO_CHAR(:pm_PercRenda) || '%'),'Parâmetro não cadastrado' ) || '|' || 
COALESCE((':DS-pm_ValorMinimoPF' || ' (' || ':NM-pm_ValorMinimoPF' || '):' || TO_CHAR(:pm_ValorMinimoPF, 'L999G999G999G990D99')),'Parâmetro não cadastrado' ) || '|' || 
COALESCE((':DS-pm_QtdeMesesPagosPF' || ' (' || ':NM-pm_QtdeMesesPagosPF' || '):' || :pm_QtdeMesesPagosPF),'Parâmetro não cadastrado' ) || '|' ||  
COALESCE((':DS-pm_QtdeMesesFaltantesPF' || ' (' || ':NM-pm_QtdeMesesFaltantesPF' || '):' || :pm_QtdeMesesFaltantesPF),'Parâmetro não cadastrado' ) || '|' ||   
COALESCE((':DS-pm_CodGrupoProduto' || ' (' || ':NM-pm_CodGrupoProduto' || '):' || :pm_CodGrupoProduto),'Parâmetro não cadastrado' ) || '|'     
AS DS_INF_ANLSE 
FROM (SELECT T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE, T.VL_RENDA_FAT, T.DT_TRANS, SUM(T1.QT_PARCELA_ANTECIPADA) QTDE_PARCELAS_ANTECIPADAS, SUM(T1.VL_OPER) VALOR_TOTAL  
      FROM TB_TRANS T1     
      INNER JOIN (SELECT T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.DT_TRANS, MAX(T.NM_CLIE) NM_CLIE,  
                  MAX(T.VL_RENDA_FAT) VL_RENDA_FAT  
                  FROM TB_TRANS_ANLSE T   
                  WHERE T.CD_LOTE = :cd_lote 
                  AND   T.CD_SUBLOTE = :cd_sublote   
                  AND   T.CD_TP_PESSOA = 'F'  
                  AND   T.CD_TP_OPER = 73 /* ANTECIPACAO DE PARCELA */  
                  AND   T.FL_CANCEL_CONTRATO = 0 /* CONTRATO ATIVO */  
                  AND   T.DT_LIQUID IS NULL  
                  AND   T.QT_MES_CONTT IS NOT NULL  
                  AND   T.QT_MES_PAGO IS NOT NULL  
                  AND   T.CD_GRP_PRODUTO = (:pm_CodGrupoProduto) 	      	   
                  AND   ((T.QT_MES_PAGO/T.QT_MES_CONTT) * 100) <= (:pm_PercMesesFaltantesPF) 
                  GROUP BY T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.DT_TRANS  
                 ) T  
      ON T1.CD_DOC_IDENTF_CLIE = T.CD_DOC_IDENTF_CLIE  
      AND T1.CD_TP_IDENTF_CLIE = T.CD_TP_IDENTF_CLIE 
      AND T1.CD_TP_OPER = 73  
      AND T1.DT_TRANS >= TO_DATE(TO_CHAR(T.DT_TRANS, 'YYYYMM') || '01', 'yy-mm-dd')   
      AND T1.DT_TRANS <= LAST_DAY(T.DT_TRANS)   
      AND T1.CD_GRP_PRODUTO = (:pm_CodGrupoProduto)    
      AND T1.CD_TP_OPER = 73 /* ANTECIPACAO DE PARCELA */  
      AND T1.FL_CANCEL_CONTRATO = 0 /* CONTRATO ATIVO */	   
      GROUP BY T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE, T.VL_RENDA_FAT, T.DT_TRANS     
     ) T  
WHERE T.QTDE_PARCELAS_ANTECIPADAS > (:pm_QtdeMesesPagosPF) 
AND ((T.VL_RENDA_FAT IS NOT NULL  
      AND T.VALOR_TOTAL > (T.VL_RENDA_FAT * (:pm_PercRenda/100)) 
     ) 
     OR 
     (T.VL_RENDA_FAT IS NULL   
      AND T.VALOR_TOTAL > (:pm_ValorMinimoPF) 
     ) 
    )  
UNION ALL  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4090 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da Antecipação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||  
'Valor do Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Não cadastrado') || '|' || 
'Valor total das antecipações no mês calendário: ' || COALESCE(TO_CHAR(T.VALOR_TOTAL, 'L999G999G999G990D99'), 'Não cadastrado') || '|' || 
'Quantidade de parcelas antecipadas no mês calendário: ' || COALESCE(TO_CHAR(T.QTDE_PARCELAS_ANTECIPADAS), 'Não cadastrado') || '|' || 
COALESCE((':DS-pm_PercFaturamento' || ' (' || ':NM-pm_PercFaturamento' || '):' || TO_CHAR(:pm_PercFaturamento) || '%'),'Parâmetro não cadastrado' ) || '|' || 
COALESCE((':DS-pm_ValorMinimoPJ' || ' (' || ':NM-pm_ValorMinimoPJ' || '):' || TO_CHAR(:pm_ValorMinimoPJ, 'L999G999G999G990D99')),'Parâmetro não cadastrado' ) || '|' || 
COALESCE((':DS-pm_QtdeMesesPagosPJ' || ' (' || ':NM-pm_QtdeMesesPagosPJ' || '):' || :pm_QtdeMesesPagosPJ),'Parâmetro não cadastrado' ) || '|' ||   
COALESCE((':DS-pm_QtdeMesesFaltantesPJ' || ' (' || ':NM-pm_QtdeMesesFaltantesPJ' || '):' || :pm_QtdeMesesFaltantesPJ),'Parâmetro não cadastrado' ) || '|'  ||  
COALESCE((':DS-pm_CodGrupoProduto' || ' (' || ':NM-pm_CodGrupoProduto' || '):' || :pm_CodGrupoProduto),'Parâmetro não cadastrado' ) || '|'     
AS DS_INF_ANLSE 
FROM (SELECT T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE, T.VL_RENDA_FAT, T.DT_TRANS, SUM(T1.QT_PARCELA_ANTECIPADA) QTDE_PARCELAS_ANTECIPADAS, SUM(T1.VL_OPER) VALOR_TOTAL  
      FROM TB_TRANS T1     
      INNER JOIN (SELECT T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.DT_TRANS, MAX(T.NM_CLIE) NM_CLIE,  
                  MAX(T.VL_RENDA_FAT) VL_RENDA_FAT  
                  FROM TB_TRANS_ANLSE T   
                  WHERE T.CD_LOTE = :cd_lote 
                  AND   T.CD_SUBLOTE = :cd_sublote   
                  AND   T.CD_TP_PESSOA = 'J'  
                  AND   T.CD_TP_OPER = 73 /* ANTECIPACAO DE PARCELA */  
                  AND   T.FL_CANCEL_CONTRATO = 0 /* CONTRATO ATIVO */  
                  AND   T.DT_LIQUID IS NULL  
                  AND   T.QT_MES_CONTT IS NOT NULL  
                  AND   T.QT_MES_PAGO IS NOT NULL  
                  AND   T.CD_GRP_PRODUTO = (:pm_CodGrupoProduto)        	   
                  AND   ((T.QT_MES_PAGO/T.QT_MES_CONTT) * 100) <= (:pm_PercMesesFaltantesPJ) 
                  GROUP BY T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.DT_TRANS    
                 ) T  
      ON T1.CD_DOC_IDENTF_CLIE = T.CD_DOC_IDENTF_CLIE  
      AND T1.CD_TP_IDENTF_CLIE = T.CD_TP_IDENTF_CLIE 
      AND T1.CD_TP_OPER = 73  
      AND T1.DT_TRANS >= TO_DATE(TO_CHAR(T.DT_TRANS, 'YYYYMM') || '01', 'yy-mm-dd')   
      AND T1.DT_TRANS <= LAST_DAY(T.DT_TRANS)  
      AND T1.CD_GRP_PRODUTO = (:pm_CodGrupoProduto)   
      AND T1.CD_TP_OPER = 73 /* ANTECIPACAO DE PARCELA */  
      AND T1.FL_CANCEL_CONTRATO = 0 /* CONTRATO ATIVO */
      GROUP BY T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE, T.VL_RENDA_FAT, T.DT_TRANS   
     ) T  
WHERE T.QTDE_PARCELAS_ANTECIPADAS > (:pm_QtdeMesesPagosPJ) 
AND ((T.VL_RENDA_FAT IS NOT NULL  
      AND T.VALOR_TOTAL > (T.VL_RENDA_FAT * (:pm_PercFaturamento/100)) 
     ) 
     OR 
     (T.VL_RENDA_FAT IS NULL   
      AND T.VALOR_TOTAL > (:pm_ValorMinimoPJ) 
     ) 
    ) 

