SELECT DISTINCT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || ' |Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4036 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da transação : '  ||  TO_CHAR(TRUNC(T.DT_TRANS)) || '|' ||  
'Tipo de operação: ' || COALESCE((SELECT NM_TP_OPER FROM TB_TP_OPER O WHERE O.CD_TP_OPER = T.CD_TP_OPER), TO_CHAR(T.CD_TP_OPER)) || '|' || 
'Flag Conflito Informação Pública: Sim' || '|' 
AS DS_INF_ANLSE 
from tb_trans_anlse T 
where T.CD_LOTE = :cd_lote 
  and T.CD_SUBLOTE = :cd_sublote 
  and CD_TP_OPER in (25,29,61,62,21,74,78,79,81,83,84) 
  and fl_info_publica_conflito = 1 
  
  