SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4033 AND CD_VERSAO_SISTEMA = 4) ||     
'Cliente: ' ||  (T.NM_CLIE) || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||   
'Lote: ' || TO_CHAR(CD_LOTE) ||  '|' ||  
'Porte da empresa: ' || COALESCE((SELECT NM_PORTE FROM TB_PORTE P WHERE P.CD_PORTE = T.CD_PORTE), TO_CHAR(CD_PORTE)) ||  '|' || 
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||     
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|' ||  
'Tipo da Transação: ' || COALESCE((SELECT NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), TO_CHAR(T.CD_TP_OPER)) || '|' ||      
'Forma da Transação: ' || COALESCE((SELECT NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), TO_CHAR(T.CD_FORMA_OPER)) || '|' ||      
'Via da Transação: ' || COALESCE((SELECT NM_VIA_OPER FROM TB_VIA_OPER WHERE CD_VIA_OPER = T.CD_VIA_OPER), TO_CHAR(T.CD_VIA_OPER)) || '|' ||      
'Valor Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||
COALESCE((':DS-pm_ValorLimiteME' || ' (' || ':NM-pm_ValorLimiteME' || '):' || TO_CHAR(:pm_ValorLimiteME, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' ||
COALESCE((':DS-pm_ValorLimiteEPP' || ' (' || ':NM-pm_ValorLimiteEPP' || '):' || TO_CHAR(:pm_ValorLimiteEPP, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' ||
COALESCE((':DS-pm_ValorLimiteEPM' || ' (' || ':NM-pm_ValorLimiteEPM' || '):' || TO_CHAR(:pm_ValorLimiteEPM, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' 
AS DS_INF_ANLSE 
FROM TB_TRANS_ANLSE T
WHERE T.CD_LOTE = :cd_lote
  AND T.CD_SUBLOTE = :cd_sublote
  AND (:pm_FlagParte_1) = 1
  AND CD_TP_PESSOA = 'J'
  AND CD_TP_OPER IN 
      (25, /*Emissão de cartão pré-pago*/
       61, /*Abertura de conta*/
       62, /*Atualização de conta*/
       74, /*Formalização de Contrato*/ 
       78  /*Atualização Cadastral*/)
  AND (
  (CD_PORTE = 1 /*micro*/ AND VL_RENDA_FAT > (:pm_ValorLimiteME/10))
   OR
  (CD_PORTE = 2 /*EMPRESA PEQUENO PORTE*/ AND VL_RENDA_FAT > (:pm_ValorLimiteEPP/12))
   OR
  (CD_PORTE = 3 /*EMPRESA PORTE MEDIO*/ AND VL_RENDA_FAT > (:pm_ValorLimiteEPM/12))   
   )

union

SELECT T.DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4033 AND CD_VERSAO_SISTEMA = 4) ||     
'Cliente: ' ||  (T.NM_CLIE) || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||   
'Lote: ' || TO_CHAR(CD_LOTE) ||  '|' ||  
'Porte da empresa: ' || COALESCE((SELECT NM_PORTE FROM TB_PORTE P WHERE P.CD_PORTE = T.CD_PORTE), TO_CHAR(CD_PORTE)) ||  '|' || 
'Forma de constituição: ' || COALESCE((SELECT NM_FORMA_CONSTTCAO FROM TB_FORMA_CONSTTCAO P WHERE P.CD_FORMA_CONSTTCAO = T.CD_FORMA_CONSTTCAO), TO_CHAR(CD_FORMA_CONSTTCAO)) ||  '|' || 
'Valor Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' || 
'Valor médio por constituição e porte: ' || COALESCE(TO_CHAR(T.VL_MEDIA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|'    
AS DS_INF_ANLSE 
FROM (
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.NM_CLIE, T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_FORMA_CONSTTCAO, T.CD_PORTE, T.VL_RENDA_FAT, M.VL_MEDIA_FAT
FROM TB_TRANS_ANLSE T
INNER JOIN 
  (SELECT CD_FORMA_CONSTTCAO, CD_PORTE, (SUM(VL_RENDA_FAT) / COUNT(*)) VL_MEDIA_FAT
   FROM TB_CAD_CLIE
   WHERE CD_TP_PESSOA = 'J'
     AND CD_FORMA_CONSTTCAO IS NOT NULL
     AND CD_PORTE IS NOT NULL
   GROUP BY CD_FORMA_CONSTTCAO, CD_PORTE
   ) M
ON T.CD_FORMA_CONSTTCAO = M.CD_FORMA_CONSTTCAO AND T.CD_PORTE = M.CD_PORTE

WHERE T.CD_LOTE = :cd_lote
  AND T.CD_SUBLOTE = :cd_sublote
  AND (:pm_FlagParte_2) = 1
  AND T.CD_TP_PESSOA = 'J'
  AND T.CD_TP_OPER IN 
      (25, /*Emissão de cartão pré-pago*/
       61, /*Abertura de conta*/
       62, /*Atualização de conta*/
       74, /*Formalização de Contrato*/ 
       78  /*Atualização Cadastral*/)
GROUP BY LAST_DAY(TRUNC(T.DT_TRANS)), T.NM_CLIE, T.CD_LOTE,  T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_FORMA_CONSTTCAO, T.CD_PORTE, T.VL_RENDA_FAT, M.VL_MEDIA_FAT
) T
WHERE  T.VL_RENDA_FAT > T.VL_MEDIA_FAT 

