/* a) Movimentação de recursos em espécie em moeda estrangeira ou cheques de viagem, */  
/* que apresente atipicidade em relação a atividade econômica do cliente ou incompatibilidade */  
/* com a sua capacidade econômico-financeira;*/  
  
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4015 AND CD_VERSAO_SISTEMA = 4) ||    
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||   
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||   
'Valor Renda: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||    
COALESCE((':DS-pm_PercRenda' || ' (' || ':NM-pm_PercRenda' || '):' || :pm_PercRenda || '%'),'Parâmetro não cadastrado') || '|' ||
COALESCE((':DS-pm_ValorMinimo_PF' || ' (' || ':NM-pm_ValorMinimo_PF' || '):' || TO_CHAR(:pm_ValorMinimo_PF, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' 
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T   
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote    
  AND T.CD_TP_PESSOA = 'F'   
  AND T.CD_FORMA_OPER = 8   
  AND T.VL_OPER IS NOT NULL   
  AND T.VL_OPER > (:pm_ValorMinimo_PF)   
  AND ((T.VL_RENDA_FAT IS NOT NULL AND   
        T.VL_OPER > (T.VL_RENDA_FAT * (:pm_PercRenda/100)))   
        OR   
        T.VL_RENDA_FAT IS NULL   
        )   
UNION      
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4015 AND CD_VERSAO_SISTEMA = 4) ||  
'Conclusão: Cliente movimentou recursos em espécie em moeda estrangeira ou cheques de viagem, apresentando atipicidade em relação à sua atividade econômica ou incompatibilidade com a sua capacidade econômico-financeira |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||   
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||   
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||   
'Ocupação: ' || ocup || '|' ||
COALESCE((':DS-pm_PercOcupacao' || ' (' || ':NM-pm_PercOcupacao' || '):' || :pm_PercOcupacao || '%'),'Parâmetro não cadastrado') || '|' ||
COALESCE((':DS-pm_ValorMinimo_PF' || ' (' || ':NM-pm_ValorMinimo_PF' || '):' || TO_CHAR(:pm_ValorMinimo_PF, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' 
AS DS_INF_ANLSE   
FROM
(SELECT T.CD_LOTE, T.NM_CLIE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.DT_TRANS, T.VL_OPER, T.CD_TP_OPER, T.CD_FORMA_OPER,
 LISTAGG('Valor médio da ocupação ' || COALESCE(O.NM_OCUP, TO_CHAR(R.CD_OCUP)) || TO_CHAR(coalesce(M.VL_MED_CREDITO,0), 'L999G999G999G990D99') , ' , ') WITHIN GROUP (ORDER BY R.CD_OCUP desc)  OCUP
 FROM TB_TRANS_ANLSE T
 INNER JOIN TB_CLIE_RENDA R ON T.CD_DOC_IDENTF_CLIE = R.CD_DOC_IDENTF_CLIE AND T.CD_TP_IDENTF_CLIE = R.CD_TP_IDENTF_CLIE   
 INNER JOIN TB_MED_OCUP M   ON  R.CD_OCUP = M.CD_OCUP 
 LEFT JOIN TB_OCUP O        ON  R.CD_OCUP = O.CD_OCUP 
 WHERE  T.CD_LOTE    = :cd_lote    
   AND T.CD_SUBLOTE = :cd_sublote   
   AND T.CD_TP_PESSOA = 'F'   
   AND T.CD_FORMA_OPER = 8   
   AND T.VL_OPER IS NOT NULL   
   AND T.VL_OPER > (:pm_ValorMinimo_PF)        
   AND T.VL_OPER > (M.VL_MED_CREDITO * (:pm_PercOcupacao/100) )   
 GROUP BY T.CD_LOTE, T.NM_CLIE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.DT_TRANS, T.VL_OPER, T.CD_TP_OPER, T.CD_FORMA_OPER
 ) T  
   
UNION   
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4015 AND CD_VERSAO_SISTEMA = 4) ||  
'Objetivo: a) Movimentação de recursos em espécie em moeda estrangeira ou cheques de viagem, que apresente atipicidade em relação à atividade econômica do cliente ou incompatibilidade com a sua capacidade econômico-financeira. C.C. Bacen n.3.542/2012, Art. 1º, Inciso II |' ||   
'Conclusão: Cliente movimentou recursos em espécie em moeda estrangeira ou cheques de viagem, apresentando atipicidade em relação à sua atividade econômica ou incompatibilidade com a sua capacidade econômico-financeira |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||   
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||   
'Valor Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||    
COALESCE((':DS-pm_PercFaturamento' || ' (' || ':NM-pm_PercFaturamento' || '):' || :pm_PercFaturamento || '%'),'Parâmetro não cadastrado') || '|' ||
COALESCE((':DS-pm_ValorMinimo_PJ' || ' (' || ':NM-pm_ValorMinimo_PJ' || '):' || TO_CHAR(:pm_ValorMinimo_PJ, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' 
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T   
WHERE T.CD_LOTE    = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote   
  AND T.CD_TP_PESSOA = 'J'   
  AND T.CD_FORMA_OPER = 8   
  AND T.VL_OPER IS NOT NULL   
  AND T.VL_OPER > (:pm_ValorMinimo_PJ)   
  AND ((T.VL_RENDA_FAT IS NOT NULL   
       AND T.VL_OPER > (T.VL_RENDA_FAT * (:pm_PercFaturamento/100)))   
       OR    
       T.VL_RENDA_FAT IS NULL)   
UNION         
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4015 AND CD_VERSAO_SISTEMA = 4) ||  
'Conclusão: Cliente movimentou recursos em espécie em moeda estrangeira ou cheques de viagem, apresentando atipicidade em relação à sua atividade econômica ou incompatibilidade com a sua capacidade econômico-financeira |' ||   
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||   
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|'  ||   
'Tipo da Transação: ' || T.CD_TP_OPER || COALESCE((SELECT '-' || NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Tipo não cadastrado') || '|' ||   
'Forma da Transação: ' || T.CD_FORMA_OPER || COALESCE((SELECT '-' || NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), 'Forma não cadastrada') || '|' ||   
'Ramo de Atividade: ' || COALESCE((SELECT TO_CHAR(NM_RAMO_ATIVID) FROM TB_RAMO_ATIVID   
                                   WHERE T.CD_RAMO_ATIVID = CD_RAMO_ATIVID),'Ramo de Atividade não cadastrado') || '|' ||   
'Valor Médio de Crédito do Ramo de Atividade: ' || TO_CHAR(M.VL_MED_CREDITO, 'L999G999G999G990D99')  || '|' ||   
COALESCE((':DS-pm_PercRamoAtividade' || ' (' || ':NM-pm_PercRamoAtividade' || '):' || :pm_PercRamoAtividade || '%'),'Parâmetro não cadastrado') || '|' ||
COALESCE((':DS-pm_ValorMinimo_PJ' || ' (' || ':NM-pm_ValorMinimo_PJ' || '):' || TO_CHAR(:pm_ValorMinimo_PJ, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' 
AS DS_INF_ANLSE    
FROM TB_TRANS_ANLSE T
INNER JOIN TB_MED_RAMO_ATIVID M ON T.CD_RAMO_ATIVID = M.CD_RAMO_ATIVID
WHERE  T.CD_LOTE = :cd_lote    
   AND T.CD_SUBLOTE = :cd_sublote   
   AND T.CD_TP_PESSOA = 'J'   
   AND T.CD_FORMA_OPER = 8   
   AND T.VL_OPER IS NOT NULL   
   AND M.VL_MED_CREDITO IS NOT NULL
   AND T.VL_OPER > (:pm_ValorMinimo_PJ)        
   AND T.VL_OPER > 
     (M.VL_MED_CREDITO * (:pm_PercRamoAtividade/100) )
