SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,  
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4028 AND CD_VERSAO_SISTEMA = 4) ||
'Cliente: ' ||  T.NM_CLIE || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||   
'Lote: ' || TO_CHAR(CD_LOTE) ||  '|' ||   
'Data da Transação: ' || TO_CHAR(T.DT_TRANS,'DD/MM/YYYY') || '|' ||     
'Valor da Transação: ' || TO_CHAR(T.VL_OPER, 'L999G999G999G990D99') || '|' ||  
'Tipo da Transação: ' || COALESCE((SELECT NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), TO_CHAR(T.CD_TP_OPER)) || '|' ||      
'Forma da Transação: ' || COALESCE((SELECT NM_FORMA_OPER FROM TB_FORMA_OPER WHERE CD_FORMA_OPER = T.CD_FORMA_OPER), TO_CHAR(T.CD_FORMA_OPER)) || '|' ||      
'Via da Transação: ' || COALESCE((SELECT NM_VIA_OPER FROM TB_VIA_OPER WHERE CD_VIA_OPER = T.CD_VIA_OPER), TO_CHAR(T.CD_VIA_OPER)) || '|' ||      
'Valor Renda: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'), 'Valor não cadastrado') || '|'    

AS DS_INF_ANLSE  
FROM TB_TRANS_ANLSE T
WHERE T.CD_LOTE = :cd_lote    
  AND T.CD_SUBLOTE = :cd_sublote
  AND (
    (T.CD_TP_OPER IN (
      5, /*DOC*/
      8, /*TED*/
      9 )/*transferencia*/
     AND CD_DOC_IDENTF_DESTORIG IS NULL
     ) 
  OR
   (CD_TP_OPER  = 20 /*Operação de crédito*/
    AND 
    CD_DOC_IDENTF_BNEFC IS NULL)
 )

