/* BANRISUL - DIARIA */ 
SELECT LAST_DAY(TRUNC(T.DT_TRANS)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4144 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da Transação: ' || COALESCE(TO_CHAR(T.DT_TRANS,'DD/MM/YYYY'),'Não cadastrada') || '|' || 
'Tipo da Transação: ' || COALESCE((SELECT NM_TP_OPER FROM TB_TP_OPER WHERE CD_TP_OPER = T.CD_TP_OPER), 'Descrição não cadastrada') || '|' || 
'Valor da Transação: ' || COALESCE(TO_CHAR(T.VL_OPER, 'L999G999G999G990D99'), 'Não cadastrado') || '|' || 
'Sistema de Origem do Contrato: ' || COALESCE(T.NM_SIST_ORIG, 'Não cadastrado') || '|' || 
'Contrato: ' || COALESCE(T.CD_CONTRATO, 'Não cadastrado') || '|' ||  
CASE T.CD_TP_IDENTF_BNEFC  
     WHEN 2 THEN 'Documento do Benecifiário do Contrato Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_BNEFC, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_BNEFC, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_BNEFC, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_BNEFC, 10, 2) 
     WHEN 3 THEN 'Documento do Benecifiário do Contrato (CNPJ): ' || SUBSTR(T.CD_DOC_IDENTF_BNEFC, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_BNEFC, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_BNEFC, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_BNEFC, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_BNEFC, 13, 2) 
     ELSE T.CD_DOC_IDENTF_BNEFC 
END 
 || '|' || 
'Produto (Ativo não financeiro):' ||  (SELECT COALESCE(P.NM_PRODUTO, 'Código:' || T.CD_PRODUTO || ' - Descrição não cadastrada') FROM TB_PRODUTO P WHERE P.CD_PRODUTO = T.CD_PRODUTO) || '|' 
AS DS_INF_ANLSE 
FROM TB_TRANS_ANLSE T   
WHERE T.CD_LOTE = :cd_lote 
AND T.CD_SUBLOTE = :cd_sublote
AND T.CD_TP_OPER = 67 /*Solicitação de Crédito*/ 
AND T.CD_PRODUTO IS NOT NULL 
AND EXISTS (SELECT 1 FROM TB_PRODUTO P  
            WHERE P.CD_PRODUTO = T.CD_PRODUTO
			AND P.FL_ATIVO_FINANCEIRO = 0) 
AND T.CD_CONTRATO IS NOT NULL 
AND T.NM_SIST_ORIG IS NOT NULL 
AND T.CD_DOC_IDENTF_BNEFC IS NOT NULL 
AND T.CD_DOC_IDENTF_BNEFC <> T.CD_DOC_IDENTF_CLIE 


