SELECT LAST_DAY(TRUNC(T.DT_DIA)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE,T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4010 AND CD_VERSAO_SISTEMA = 4) ||
'Cliente: ' ||  coalesce(T.NM_CLIE, 'Nome não informado') || '|' ||  
CASE T.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||    
'Lote: ' || to_char(T.CD_LOTE) || '|' || 
'Dia de consolidação: ' || TO_CHAR(T.DT_DIA,'DD/MM/YYYY') || '|' ||   
'Valor consolidada no dia: ' || TO_CHAR(T.VL_TOTAL, 'L999G999G999G990D99') || '|'  ||   
'Quantidade de transações: ' || TO_CHAR(T.QT_TOTAL) || '|'  ||   
'Natureza da transação: Crédito' ||
'Tipo da transação: Depósito |'||  
'Forma da transação: Espécie |' ||
COALESCE((':DS-pm_ValorMinimo_PF' || ' (' || ':NM-pm_ValorMinimo_PF' || '):' || TO_CHAR(:pm_ValorMinimo_PF, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' 
AS DS_INF_ANLSE  
FROM
(SELECT A.DT_DIA, A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.CD_LOTE, SUM(T.VL_OPER) VL_TOTAL, COUNT(*) QT_TOTAL
FROM TB_TRANS_ANLSE T
INNER JOIN
(SELECT TRUNC(DT_TRANS) DT_DIA, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, CD_LOTE
 FROM TB_TRANS_ANLSE A
 WHERE CD_LOTE = :cd_lote  
  AND CD_SUBLOTE = :cd_sublote
  AND CD_TP_PESSOA  = 'F'
  AND CD_NATUR_OPER = 1  /*credito*/
  AND CD_TP_OPER    = 4  /*depósito*/
  AND CD_FORMA_OPER = 7  /*especie*/
  AND NOT EXISTS
    (SELECT 1 FROM TB_CLIE_RENDA C 
     INNER JOIN TB_OCUP O ON O.CD_OCUP = C.CD_OCUP
     WHERE A.CD_DOC_IDENTF_CLIE = C.CD_DOC_IDENTF_CLIE 
       AND A.CD_TP_IDENTF_CLIE  = C.CD_TP_IDENTF_CLIE
       AND O.FL_OPER_ESPECIE = 1
     )  
   GROUP BY TRUNC(DT_TRANS), CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, CD_LOTE
) A
 ON   TRUNC(T.DT_TRANS)    = A.DT_DIA
  AND T.CD_DOC_IDENTF_CLIE = A.CD_DOC_IDENTF_CLIE
  AND T.CD_TP_IDENTF_CLIE  = A.CD_TP_IDENTF_CLIE
WHERE T.CD_TP_PESSOA  = 'F'
  AND T.CD_NATUR_OPER = 1  /*credito*/
  AND T.CD_TP_OPER    = 4  /*depósito*/
  AND T.CD_FORMA_OPER = 7  /*especie*/  
GROUP BY A.DT_DIA, A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.CD_LOTE ) T
WHERE VL_TOTAL > (:pm_ValorMinimo_PF)

UNION ALL

SELECT LAST_DAY(TRUNC(T.DT_DIA)) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE,T.CD_TP_IDENTF_CLIE,    
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || '| Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4010 AND CD_VERSAO_SISTEMA = 4) ||
'Cliente: ' ||  coalesce(T.NM_CLIE, 'Nome não informado') || '|' ||  
CASE T.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||    
'Lote: ' || to_char(T.CD_LOTE) || '|' || 
'Dia de consolidação: ' || TO_CHAR(T.DT_DIA,'DD/MM/YYYY') || '|' ||   
'Valor consolidada no dia: ' || TO_CHAR(T.VL_TOTAL, 'L999G999G999G990D99') || '|'  ||   
'Quantidade de transações: ' || TO_CHAR(T.QT_TOTAL) || '|'  ||   
'Natureza da transação: Crédito' ||
'Tipo da transação: Depósito |'||  
'Forma da transação: Espécie |' ||
'Ramo de atividade: ' || NM_RAMO_ATIVID || '|'  || 
COALESCE((':DS-pm_ValorMinimo_PJ' || ' (' || ':NM-pm_ValorMinimo_PJ' || '):' || TO_CHAR(:pm_ValorMinimo_PJ, 'L999G999G999G990D99')),'Parâmetro não cadastrado') || '|' 
AS DS_INF_ANLSE  
FROM
(SELECT A.DT_DIA, A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.CD_LOTE, SUM(T.VL_OPER) VL_TOTAL, COUNT(*) QT_TOTAL, A.NM_RAMO_ATIVID
FROM TB_TRANS_ANLSE T
INNER JOIN
(SELECT TRUNC(DT_TRANS) DT_DIA, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, CD_LOTE, NM_RAMO_ATIVID
 FROM TB_TRANS_ANLSE A
 INNER JOIN TB_RAMO_ATIVID R ON R.CD_RAMO_ATIVID = A.CD_RAMO_ATIVID
 WHERE CD_LOTE = :cd_lote  
  AND CD_SUBLOTE = :cd_sublote
  AND CD_TP_PESSOA  = 'J'
  AND CD_NATUR_OPER = 1  /*credito*/
  AND CD_TP_OPER    = 4  /*depósito*/
  AND CD_FORMA_OPER = 7  /*especie*/
  AND R.FL_OPER_ESPECIE = 0 
  GROUP BY TRUNC(DT_TRANS), CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, CD_LOTE, NM_RAMO_ATIVID
) A
 ON   TRUNC(T.DT_TRANS)    = A.DT_DIA
  AND T.CD_DOC_IDENTF_CLIE = A.CD_DOC_IDENTF_CLIE
  AND T.CD_TP_IDENTF_CLIE  = A.CD_TP_IDENTF_CLIE
WHERE T.CD_TP_PESSOA  = 'J'
  AND T.CD_NATUR_OPER = 1  /*credito*/
  AND T.CD_TP_OPER    = 4  /*depósito*/
  AND T.CD_FORMA_OPER = 7  /*especie*/  
GROUP BY A.DT_DIA, A.CD_DOC_IDENTF_CLIE, A.CD_TP_IDENTF_CLIE, A.NM_CLIE, A.CD_LOTE, A.NM_RAMO_ATIVID ) T
WHERE VL_TOTAL > (:pm_ValorMinimo_PJ)




