select count(*) as total from
(
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO
FROM TB_TRANS_ANLSE t
WHERE CD_LOTE = 2014091801 
  AND CD_TP_OPER = 39
  AND  EXISTS (
   SELECT 1 FROM TB_PERFIL_INFORMACAO
   WHERE CD_IDENTF_PERFIL = 20
     AND CD_VARIAVEL_PRIMEIRA = T.CD_DOC_IDENTF_CLIE
     AND CD_VARIAVEL_SEGUNDA  = T.CD_TP_IDENTF_CLIE
     AND CD_VARIAVEL_TERCEIRA = T.CD_CONTRATO
     AND QT_TOTAL > (SELECT VL_PARAM FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 200 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_QtdeEstorno')
   )
) s; 
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 200 ;