select count(*) as total from
(
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO
FROM TB_TRANS_ANLSE t
WHERE CD_LOTE = 2014091801 
  AND CD_TP_PESSOA = 'J'
  AND VL_OPER is not NULL 
  AND VL_RENDA_FAT is not NULL 
  AND VL_OPER > (VL_RENDA_FAT * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 48 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percFat') ) 
union
SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_TRANSACAO
FROM TB_TRANS_ANLSE t
WHERE CD_LOTE = 2014091801 
  AND CD_TP_PESSOA = 'J'
  AND VL_OPER is not NULL 
  AND CD_RAMO_ATIVID is not NULL 
  AND exists (
  	select 1 from TB_MED_RAMO_ATIVID
  	where CD_RAMO_ATIVID = t.CD_RAMO_ATIVID
	  AND VL_MED_CREDITO is not null
	  AND t.VL_OPER > (VL_MED_CREDITO * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 48 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percRamo_Ativid') ) 
  )  	
) s; 
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 48
