select count(*) as total from
(
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_TRANSACAO
FROM TB_TRANS_ANLSE T, TB_CLIE_RENDA R, TB_MED_OCUP M
WHERE T.CD_LOTE = 2014091801
  AND T.CD_TP_PESSOA = 'F'
  AND T.CD_TP_OPER = 31
  AND T.CD_DOC_IDENTF_CLIE = R.CD_DOC_IDENTF_CLIE
  AND T.CD_TP_IDENTF_CLIE = R.CD_TP_IDENTF_CLIE
  AND T.VL_PCELA_CONTRATO IS NOT NULL
  AND T.VL_RENDA_FAT IS NOT NULL
  AND T.VL_PCELA_CONTRATO > (VL_RENDA_FAT * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 91 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percRenda'))  
  AND R.CD_OCUP = M.CD_OCUP
  AND T.VL_PCELA_CONTRATO > (M.VL_MED_CREDITO * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 91 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percOcup') )
UNION
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_TRANSACAO 
FROM TB_TRANS_ANLSE T, TB_MED_RAMO_ATIVID M
WHERE T.CD_LOTE = 2014091801
  AND T.CD_TP_PESSOA = 'J'
  AND T.CD_TP_OPER = 31
  AND T.VL_PCELA_CONTRATO IS NOT NULL
  AND T.VL_RENDA_FAT IS NOT NULL
  AND T.VL_PCELA_CONTRATO > (VL_RENDA_FAT * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 91 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percFatmt'))  
  AND T.CD_RAMO_ATIVID = M.CD_RAMO_ATIVID
  AND T.VL_PCELA_CONTRATO > (M.VL_MED_CREDITO * (SELECT VL_PARAM/100 FROM TB_REGRA_PARAMETRO WHERE CD_REGRA = 91 AND CD_VERSAO_SISTEMA = 3 AND NM_CAMPO_PARAM = 'pm_percRamoAtivid') )
  ) s; 
select count(1) as total from tb_detlh_apontamento where cd_lote = 2014091801 and cd_regra = 91