MERGE TB_EVENTO AS e
USING (SELECT ?, ?, ?) AS s (CD_TP_IDENTF_CLIE,CD_DOC_IDENTF_CLIE,DT_APONTAMENTO)
ON (s.CD_TP_IDENTF_CLIE = e.CD_TP_IDENTF_CLIE AND s.CD_DOC_IDENTF_CLIE = e.CD_DOC_IDENTF_CLIE AND s.DT_APONTAMENTO = e.DT_APONTAMENTO)
WHEN NOT MATCHED THEN
INSERT
(CD_TP_IDENTF_CLIE,CD_DOC_IDENTF_CLIE,DT_APONTAMENTO,DT_EVENTO,CD_STTUS_EVENTO,CD_USU,FL_CADSTR_DESATULZ)
VALUES
(s.CD_TP_IDENTF_CLIE,s.CD_DOC_IDENTF_CLIE,s.DT_APONTAMENTO,SYSDATETIMEOFFSET(),0,0,0);