SELECT 
DT_APONTAMENTO,
CD_DOC_IDENTF_CLIE,
CD_TP_IDENTF_CLIE,
CD_STTUS_EVENTO_ATUAL,
VL_APONTAMENTO,
VL_PONTO_CORTE,
DT_ATUALZ_CALCULO,
FL_CARENCIA,
FL_PONTO_CORTE,
FL_SUSP_LD,
CD_LOTE 
FROM TB_APONTAMENTO a
WHERE 
	CD_STTUS_EVENTO_ATUAL = 2 AND
EXISTS (
	SELECT 1 FROM TB_TRANS_ANLSE 
	WHERE 
		CD_DOC_IDENTF_CLIE = a.CD_DOC_IDENTF_CLIE AND 
		CD_TP_IDENTF_CLIE = a.CD_TP_IDENTF_CLIE AND 
		CD_LOTE = ?
	)