select 
LAST_DAY(T.DT_TRANS) DT_APONTAMENTO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
(SELECT 'Análise: Regra ' || TO_CHAR(CD_REGRA) || ' - ' || NM_REGRA || ' |Objetivo: ' || DS_REGRA || '|' FROM TB_REGRA WHERE CD_REGRA = 4035 AND CD_VERSAO_SISTEMA = 4) ||  
'Cliente: ' ||  COALESCE(T.NM_CLIE, 'Nome não informado') || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||    
'Lote: ' || TO_CHAR(T.CD_LOTE) || '|' || 
'Data da transação : '  ||  TO_CHAR(T.DT_TRANS) || '|' ||  
'IP da Transação Cliente 1: ' || COALESCE(T.NU_IP_OPER, 'Não cadastrado') || '|' || 
'Email do Cliente 1: ' || COALESCE(T.DS_EMAIL_CLIE, 'Não cadastrado') || '|' || 
'IP da Transação Cliente 2: ' || COALESCE(T2.NU_IP_OPER, 'Não cadastrado') || '|' || 
'Email do Cliente 2: ' || COALESCE(T2.DS_EMAIL_CLIE, 'Não cadastrado') || '|' ||
'Quantidade: ' || COUNT(1) || '|' || 
'Valor: ' || SUM(VL_OPER) || '|' || 
COALESCE((':DS-pm_QtdeDias' || ' (' || ':NM-pm_QtdeDias' || '):' || :pm_QtdeDias),'Parâmetro não cadastrado' ) || '|'
AS DS_INF_ANLSE 
from tb_trans_anlse T , 
(select trunc(DT_TRANS) DT_TRANS, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, DS_EMAIL_CLIE, NU_IP_OPER from tb_trans_anlse 
	where CD_TP_PESSOA = 'F' 
	and 
	CD_LOTE = :cd_lote        
	and  
	CD_SUBLOTE = :cd_sublote 
	and 
	CD_TP_OPER in (25,61,62,74,78)) T2 
where 
T.CD_LOTE = :cd_lote         
and 
T.CD_SUBLOTE = :cd_sublote 
and 
CD_TP_PESSOA = 'F' 
and 
CD_TP_OPER in (25,61,62,74,78) 
and 
T.DT_TRANS >= TO_DATE(T2.DT_TRANS - (:pm_QtdeDias)) 
and 
T.DT_TRANS <= T2.DT_TRANS 
and 
T.CD_DOC_IDENTF_CLIE <> T2.CD_DOC_IDENTF_CLIE 
and  
((T.DS_EMAIL_CLIE is not null and T2.DS_EMAIL_CLIE is not null and T.DS_EMAIL_CLIE = T2.DS_EMAIL_CLIE) or (T.NU_IP_OPER is not null and T2.NU_IP_OPER is not null and T2.NU_IP_OPER = T2.NU_IP_OPER)) 
GROUP BY T.DT_TRANS, T.CD_LOTE, T.CD_DOC_IDENTF_CLIE, T.cd_tp_identf_clie, T.NM_CLIE, T.DS_EMAIL_CLIE, T.NU_IP_OPER, T2.CD_DOC_IDENTF_CLIE, T2.cd_tp_identf_CLIE, T2.DS_EMAIL_CLIE, T2.NU_IP_OPER 