SELECT
P.CD_ANO_MES,
P.CD_IDENTF_PERFIL,
P.CD_VARIAVEL_PRIMEIRA,
P.CD_VARIAVEL_SEGUNDA,
P.CD_VARIAVEL_TERCEIRA,
P.CD_VARIAVEL_QUARTA,
P.VL_TOTAL,
P.QT_TOTAL,
P.VL_MEDIO_DIARIO,
P.VL_DESVIO_DIARIO,
P.DT_PERFIL
FROM TB_PERFIL_MES_CALENDARIO P