SELECT 
	CD_DOC_IDENTF_CLIE,
	CD_TP_IDENTF_CLIE,
	CD_OCUP,
	CD_SEQ_OCUP,
	CD_DOC_IDENTF_TRAB,
	CD_TP_IDENTF_TRAB,
	CD_CEP_TRAB,
	CD_PAIS_TRAB,
	CD_TP_PESSOA,
	CD_TP_PESSOA_TRAB,
	SG_UF_TRAB,
	NM_CID_TRAB,
	NM_ENDER_TRAB,
	NM_FANT,
	NM_EMP_TRAB,
	VL_RENDA,
	FL_RENDA_COMPROV,
	DT_INIC_ATIVID,
	DT_FIM_ATIVID,
	DT_ULTM_ATULZ_CADSTRL,
	CD_FONE_COM,
	CD_LOTE 
FROM TB_CLIE_RENDA a
WHERE EXISTS (
	SELECT 1 FROM TB_TRANS_ANLSE
	WHERE
		a.CD_DOC_IDENTF_CLIE = CD_DOC_IDENTF_CLIE AND
		a.CD_TP_IDENTF_CLIE = CD_TP_IDENTF_CLIE AND
		CD_LOTE = ? AND
		CD_SUBLOTE = ?
	) and DT_FIM_ATIVID IS NULL