SELECT T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,    
'Análise: Regra 58 - Mudança repentina e injustificada na forma de movimentação do cliente |' ||    
'Objetivo: i) Mudança repentina e injustificada na forma de movimentação de recursos ou nos tipos de transação utilizados. C.C. Bacen n. 3.542/2012, Art. 1º, Inciso IV |' ||    
'Conclusão: Mudança repentina e injustificada na forma de movimentação de recursos ou nos tipos de transação utilizados |' ||    
'Cliente: ' ||  (T1.NM_CLIE) || '|' ||    
CASE T1.CD_TP_IDENTF_CLIE    
    WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)    
    WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)     
    ELSE T1.CD_DOC_IDENTF_CLIE    
END || '|' ||  
'Mês/Ano: ' || SUBSTR(T1.CD_MES_ANO,5,2) || '/' || SUBSTR(T1.CD_MES_ANO,1,4) ||  '|' ||  
'Agência: ' || TO_CHAR(T1.CD_AG,'0000') || ' - ' || COALESCE((SELECT NM_AG FROM TB_AGENCIA WHERE CD_AG = T1.CD_AG),'Nome não cadastrado') || '|' ||    
'Conta: ' || TO_CHAR(T1.CD_CTA,'0000000000') || '|' ||  
'Data de Abertura da Conta: ' || TO_CHAR((T1.DT_ABERT_CTA), 'DD/MM/YYYY') || '|' ||    
'Quantidade : Detalhe das transações que estão fora do perfil do cliente' || '|' ||  
TRANS   || '|' ||  
COALESCE((':DS-pm_QtdeDiasCtaNova' || ' (' || ':NM-pm_QtdeDiasCtaNova' || '):' || :pm_QtdeDiasCtaNova),'Parâmetro não cadastrado|' ) || '|'  || 
COALESCE((':DS-pm_QtdeOcorr' || ' (' || ':NM-pm_QtdeOcorr' || '):' || :pm_QtdeOcorr),'Parâmetro não cadastrado|' ) || '|' 
AS DS_INF_ANLSE     
FROM ( 
SELECT CD_MES_ANO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_AG, CD_CTA, DT_ABERT_CTA, NM_CLIE, 
xmlcast(xmlagg(xmlelement(trans, to_char(qt_total) ||  
CASE T.CD_NATUR_OPER    
    WHEN 1 THEN ' crédito(s): '    
    WHEN 2 THEN ' débito(s) : '    
    WHEN 3 THEN ' evento(s) : '    
    ELSE ''    
END ||    
'Tipo-' || Coalesce((SELECT NM_TP_OPER FROM TB_TP_OPER O WHERE O.CD_TP_OPER = T.CD_TP_OPER), TO_CHAR(T.CD_TP_OPER)) || ' / Forma-' || Coalesce( (SELECT NM_FORMA_OPER FROM TB_FORMA_OPER O WHERE O.CD_FORMA_OPER = T.CD_FORMA_OPER), TO_CHAR(T.CD_FORMA_OPER)) 
|| ' / Valor Total-' || LTRIM(TO_CHAR(VL_TOTAL,'L999G999G999G990D99')) 
|| '|')  order by T.CD_TP_OPER) as clob) TRANS 
FROM  
(SELECT CD_MES_ANO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_AG, CD_CTA, DT_ABERT_CTA, CD_NATUR_OPER, CD_TP_OPER, CD_FORMA_OPER, MAX(NM_CLIE) NM_CLIE, COUNT(*) QT_TOTAL, SUM(VL_OPER) VL_TOTAL   
 FROM TB_TRANS    
 WHERE DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)   
   AND CD_AG IS NOT NULL AND CD_CTA IS NOT NULL AND DT_ABERT_CTA IS NOT NULL  
   AND CD_FORMA_OPER IS NOT NULL AND CD_TP_OPER IS NOT NULL 
   AND FL_ANALISADO = 1  
   AND LAST_DAY(TO_DATE(CD_MES_ANO || '01', 'YYYYMMDD')) - TRUNC(DT_ABERT_CTA) >= (:pm_QtdeDiasCtaNova) 
GROUP BY CD_MES_ANO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_AG, CD_CTA, DT_ABERT_CTA, CD_NATUR_OPER, CD_TP_OPER, CD_FORMA_OPER  
) T 
WHERE NOT EXISTS (SELECT 1 FROM TB_PERFIL_MES_CALENDARIO T3 /*PERFIL*/   
                WHERE T3.CD_IDENTF_PERFIL = 1 
                AND T3.CD_VARIAVEL_PRIMEIRA = TO_CHAR(T.CD_AG)   
                AND T3.CD_VARIAVEL_SEGUNDA  = TO_CHAR(T.CD_CTA) 
                AND T3.CD_VARIAVEL_TERCEIRA = TO_CHAR(T.CD_TP_OPER) 
                AND T3.CD_VARIAVEL_QUARTA   = TO_CHAR(T.CD_FORMA_OPER)  
                AND T3.CD_ANO_MES < T.CD_MES_ANO 
               )       
AND QT_TOTAL > (:pm_QtdeOcorr)   
GROUP BY CD_MES_ANO, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_AG, CD_CTA, DT_ABERT_CTA, NM_CLIE 
) T1 
