/* a) movimentações atípicas de recursos por agentes públicos, conforme definidos no art. 2o da Lei no 8.429, de 2 de junho de 1992;*/  
/* Art. 2 Reputa-se agente público, para os efeitos desta lei, todo aquele que exerce, ainda que transitoriamente ou sem remuneração, */  
/* por eleição, nomeação, designação, contratação ou qualquer outra forma de investidura ou vinculo, mandato, cargo, emprego ou função nas */  
/* entidades mencionadas no artigo anterior. */  
  
SELECT T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,   
'Análise: Regra 101 - Movimentações atípicas por agentes públicos |' ||  
'Objetivo: A) Movimentações atípicas de recursos por agentes públicos, conforme definidos no art. 2o da Lei no 8.429, de 2 de junho de 1992. Art. 2° Reputa-se agente público, para os efeitos desta lei, todo aquele que exerce, ainda que transitoriamente ou sem remuneração, por eleição, nomeação, designação, contratação ou qualquer outra forma de investidura ou vínculo, mandato, cargo, emprego ou função nas entidades mencionadas no artigo anterior. C.C. Bacen n.3.542/2012, Art. 1º, Inciso VIII |' ||  
'Conclusão: Movimentações atípicas de recursos por agentes públicos |' ||  
'Cliente: ' ||  MAX(T1.NM_CLIE) || '|' || 
CASE T1.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T1.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Valor Renda: ' || COALESCE(TO_CHAR(MAX(T1.VL_RENDA_FAT), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||  
'Mês/Ano: ' || SUBSTR(T1.CD_MES_ANO,5,2) || '/' || SUBSTR(T1.CD_MES_ANO,1,4) ||  '|' ||  
'Valor total de crédito: ' || COALESCE(TO_CHAR(SUM(T1.VL_OPER), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||  
'Quantidade total de crédito: ' || TO_CHAR(COUNT(*)) || '|' ||  
'Parâmetro percentual de flexibilização da renda do cliente (pm_PercRenda): ' || COALESCE((SELECT TO_CHAR(:pm_PercRenda, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro que indica valor mínimo para apontamento da regra (pm_ValorMinimo): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimo, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE   
FROM TB_TRANS T1  
WHERE T1.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
  AND T1.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
  AND T1.FL_ANALISADO = 1    
  AND T1.CD_TP_PESSOA = 'F'  
  AND T1.FL_AGENTE_PUBLICO = 1   
  AND T1.CD_NATUR_OPER = 1  
GROUP BY T1.CD_MES_ANO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE  
HAVING (SUM(T1.VL_OPER) > (:pm_ValorMinimo) ) 
   AND  
    (MAX(T1.VL_RENDA_FAT) IS NOT NULL AND SUM(T1.VL_OPER) > (MAX(T1.VL_RENDA_FAT) * (:pm_PercRenda/100))  
     OR  
     MAX(T1.VL_RENDA_FAT) IS NULL  
     )  
     
