/* VERSAO 1 */

SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,      
'Análise: Regra 208 – Movimentação eletrônica (ATM) – Baixa Renda/Baixo Faturamento |' ||     
'Objetivo: Movimentação eletrônica, no ATM, no mês calendário fechado (Mês do Processamento), realizadas por cliente com baixa renda ou baixo faturamento |' ||     
'Conclusão: Cliente de baixa renda/baixo faturamento, movimentou de forma eletrônica, no ATM, no mês calendário fechado (Mês do Processamento), de forma expressiva |' ||     
'Cliente: ' ||  T.NM_CLIE || '|' ||    
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||     
'Mês/Ano de Referência: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) ||  '|' ||     
'Natureza: Crédito |' ||   
'Via: ATM |'  ||  
'Valor da Renda: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'),'Renda não informada') || '|' ||   
'Valor Consolidado: ' || TO_CHAR(T.VL_TOTAL, 'L999G999G999G990D99')|| '|' ||    
'Quantidade Consolidada: ' || TO_CHAR(T.QTDE, '999999990')|| '|' ||    
'Parâmetro que indica o valor limite para uma Renda ser considerada Baixa, para pessoa física (pm_ValorRendaBaixa): ' || COALESCE((SELECT TO_CHAR(:pm_ValorRendaBaixa, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro que indica valor consolidado de créditos em ATM, no mês calendário fechado (Mês do Processamento), para PF (pm_ValorMovtoATM_PF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMovtoATM_PF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro que indica quantidade consolidada de créditos em ATM, no mês calendário fechado (Mês do Processamento), para PF (pm_QtdeMovtoATM_PF): ' || COALESCE((SELECT TO_CHAR(:pm_QtdeMovtoATM_PF, '999999990') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE    
FROM (SELECT T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.CD_MES_ANO, MAX(T1.NM_CLIE) NM_CLIE, MAX(T1.VL_RENDA_FAT) VL_RENDA_FAT, SUM(VL_OPER) VL_TOTAL, COUNT(*) QTDE   
      FROM TB_TRANS T1  
      WHERE T1.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
      AND T1.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)     
      AND T1.FL_ANALISADO = 1  
      AND T1.CD_TP_PESSOA = 'F'   
      AND T1.CD_NATUR_OPER = 1  
      AND T1.CD_VIA_OPER = 1    
      GROUP BY T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.CD_MES_ANO) T   
     WHERE ((T.VL_RENDA_FAT IS NOT NULL AND   
             T.VL_RENDA_FAT <= (:pm_ValorRendaBaixa)   
            )  
            OR  
            T.VL_RENDA_FAT IS NULL  
           )  
     AND T.VL_TOTAL >= (:pm_ValorMovtoATM_PF)  
     AND T.QTDE >= (:pm_QtdeMovtoATM_PF) 
UNION ALL   
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,      
'Análise: Regra 208 – Movimentação eletrônica (ATM) – Baixa Renda/Baixo Faturamento |' ||     
'Objetivo: Movimentação eletrônica, no ATM, no mês calendário fechado (Mês do Processamento), realizadas por cliente com baixa renda ou baixo faturamento |' ||     
'Conclusão: Cliente de baixa renda/baixo faturamento, movimentou de forma eletrônica, no ATM, no mês calendário fechado (Mês do Processamento), de forma expressiva |' ||     
'Cliente: ' ||  T.NM_CLIE || '|' ||    
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||     
'Mês/Ano de Referência: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) ||  '|' ||     
'Natureza: Crédito |' ||   
'Via: ATM |'  ||   
'Valor do Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'),'Faturamento não informado') || '|' ||   
'Valor Consolidado: ' || TO_CHAR(T.VL_TOTAL, 'L999G999G999G990D99')|| '|' ||    
'Quantidade Consolidada: ' || TO_CHAR(T.QTDE, '999999990')|| '|' ||    
'Parâmetro que indica o valor limite para um Faturamento ser considerado Baixo, para pessoa jurídica (pm_ValorFaturamentoBaixo): ' || COALESCE((SELECT TO_CHAR(:pm_ValorFaturamentoBaixo, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro que indica valor consolidado de créditos em ATM, no mês calendário fechado (Mês do Processamento), para PJ (pm_ValorMovtoATM_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMovtoATM_PJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||  
'Parâmetro que indica quantidade consolidada de créditos em ATM, no mês calendário fechado (Mês do Processamento), para PJ (pm_QtdeMovtoATM_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_QtdeMovtoATM_PJ, '999999990') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE    
FROM (SELECT T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.CD_MES_ANO, MAX(T1.NM_CLIE) NM_CLIE, MAX(T1.VL_RENDA_FAT) VL_RENDA_FAT, SUM(VL_OPER) VL_TOTAL, COUNT(*) QTDE   
      FROM TB_TRANS T1  
      WHERE T1.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
      AND T1.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)    
      AND T1.FL_ANALISADO = 1   
      AND T1.CD_TP_PESSOA = 'J'   
      AND T1.CD_NATUR_OPER = 1  
      AND T1.CD_VIA_OPER = 1    
      GROUP BY T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.CD_MES_ANO) T   
     WHERE ((T.VL_RENDA_FAT IS NOT NULL AND   
             T.VL_RENDA_FAT <= (:pm_ValorFaturamentoBaixo)   
            )  
            OR  
            T.VL_RENDA_FAT IS NULL  
           )  
     AND T.VL_TOTAL >= (:pm_ValorMovtoATM_PJ)  
     AND T.QTDE >= (:pm_QtdeMovtoATM_PJ) 
