SELECT DISTINCT T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,    
'Análise: Regra 103 - Movimentação atípica por organizações sem fins lucrativos |' ||   
'Objetivo: C) Movimentações atípicas de recursos por organizações sem fins lucrativos. C.C. Bacen n.3.542/2012, Art. 1º, Inciso VIII |' ||   
'Conclusão: Movimentações atípicas de recursos por organizações sem fins lucrativos |' ||   
'Cliente: ' ||  max(T1.NM_CLIE) || '|' ||   
CASE T1.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T1.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||    
'Valor Faturamento: ' || COALESCE(TO_CHAR(max(T1.VL_RENDA_FAT), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||   
'Mês/Ano: ' || SUBSTR(T1.CD_MES_ANO,5,2) || '/' || SUBSTR(T1.CD_MES_ANO,1,4) ||  '|' ||    
'Ramo de atividade: ' || coalesce((select cd_ramo_ativid || '-' || nm_ramo_ativid from tb_ramo_ativid where cd_ramo_ativid = T1.cd_ramo_ativid ), t1.cd_ramo_ativid ||'-nome não cadastrado') ||  '|' || 
'Valor total de crédito: ' || COALESCE(TO_CHAR(SUM(T1.VL_OPER), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||   
'Quantidade total de crédito: ' || TO_CHAR(COUNT(*)) || '|' ||   
'Parâmetro percentual de flexibilização da renda ou do faturamento do cliente (pm_PercFaturamento): ' || COALESCE((SELECT TO_CHAR(:pm_PercFaturamento, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||   
'Parâmetro que indica valor mínimo para apontamento da regra para Pessoa Jurídica (pm_ValorMinimoPJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'   
AS DS_INF_ANLSE    
FROM TB_TRANS T1   
WHERE T1.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
  AND T1.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)     
  AND T1.FL_ANALISADO = 1 
  AND T1.CD_TP_PESSOA = 'J'   
  AND T1.CD_NATUR_OPER = 1   
  AND T1.CD_RAMO_ATIVID IS NOT NULL 
  AND EXISTS (SELECT 1 FROM TB_RAMO_ATIVID R WHERE R.CD_RAMO_ATIVID = T1.CD_RAMO_ATIVID AND FL_ORGNZ_SLUCRO = 1) 
GROUP BY T1.CD_MES_ANO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, t1.cd_ramo_ativid 
HAVING (SUM(T1.VL_OPER) > (:pm_ValorMinimoPJ) )  
   AND   
    (MAX(T1.VL_RENDA_FAT) IS NOT NULL AND SUM(T1.VL_OPER) > (MAX(T1.VL_RENDA_FAT) * (:pm_PercFaturamento/100))   
     OR   
     MAX(T1.VL_RENDA_FAT) IS NULL   
     )   
      
        