SELECT  T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: 40 - Cliente PJ com data de Fundação recente |' ||    
'Objetivo: Cliente pessoa jurídica com data de fundação menor que a quantidade de dias  parametrizado. |' ||    
'Conclusão: Cliente pessoa jurídica com data de fundação menor que a quantidade de dias parametrizado  |' ||    
'Cliente: ' ||  T1.NM_CLIE || '|' ||   
CASE T1.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T1.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||    
'Mês/Ano: ' || SUBSTR(:cd_lote,5,2) || '/' || SUBSTR(:cd_lote,1,4) ||  '|' ||   
'Data de fundação: ' || TO_CHAR(DT_NASCTO_FUND, 'DD/MM/YY') ||  '|' ||   
'Idade da conta em dias: ' || TO_CHAR(last_day(add_months(sysdate, -1)) - DT_NASCTO_FUND, '9999999999') ||  '|' ||     
'Parâmetro que indica a quantidade de dias para considerar uma data de fundação recente (pm_QtdeDiasFundacao):' || (:pm_QtdeDiasFundacao) 
AS DS_INF_ANLSE     
FROM TB_CAD_CLIE T1 
WHERE T1.CD_TP_PESSOA = 'J' 
  AND DT_NASCTO_FUND IS NOT NULL 
  AND EXISTS  
      (SELECT 1 FROM TB_TRANS T  
       WHERE T.CD_TP_PESSOA = 'J' 
         AND T.DT_NASCTO_FUND IS NOT NULL 
         AND T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
         AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
         AND T.FL_ANALISADO = 1
         AND T.CD_DOC_IDENTF_CLIE = T1.CD_DOC_IDENTF_CLIE 
         AND T.CD_TP_IDENTF_CLIE = T1.CD_TP_IDENTF_CLIE 
       ) 
  AND (last_day(add_months(sysdate, -1)) - DT_NASCTO_FUND) <= (:pm_QtdeDiasFundacao) 
   
   