SELECT  T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: 211 – Depósitos em espécie fracionados, no último mês calendário fechado. |' ||    
'Objetivo: Verificar valores incompatíveis depósitos em espécie fracionados, no último mês calendário fechado, com a renda ou faturamento do cliente, por faixas. |' ||    
'Conclusão: Depósitos em espécie fracionados, no último mês calendário fechado. Cliente com renda baixa  |' ||    
'Cliente: ' ||  T1.NM_CLIE || '|' ||   
'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)    
|| '|' ||    
'Mês/Ano: ' || SUBSTR(:cd_lote,5,2) || '/' || SUBSTR(:cd_lote,1,4) ||  '|' ||   
'Renda:' || COALESCE(TO_CHAR(VL_RENDA_FAT, 'L999G999G999G990D99'),'Renda não informado')  ||  '|' ||    
'Valor consolidado de Depósitos em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(VL_CONS, 'L999G999G999G990D99')  ||  '|' ||   
'Quantidade consolidada de Depósitos em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(QT_CONS, '999999990')  ||  '|' ||   
'Parâmetro que indica o limite para que uma renda possa ser considerada baixa (pm_ValorRendaBaixa):' || (SELECT TO_CHAR(:pm_ValorRendaBaixa, 'L999G999G999G990D99') FROM DUAL) ||  '|' || 
'Parâmetro que indica quantidade expressiva de depósitos em espécie, para renda baixa, no último mês calendário fechado, para pessoa física (pm_QtdeDepEspecieRendaBaixa):' || (SELECT TO_CHAR(:pm_QtdeDepEspecieRendaBaixa, '999999990') FROM DUAL) ||  '|' || 
'Parâmetro que indica valor expressivo de depósitos em espécie, para renda baixa, no último mês calendário fechado, para pessoa física (pm_ValorDepEspecieRendaBaixa):' || (SELECT TO_CHAR(:pm_ValorDepEspecieRendaBaixa, 'L999G999G999G990D99') FROM DUAL) 
AS DS_INF_ANLSE     
FROM  
(SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO, MAX(T.NM_CLIE) NM_CLIE, MAX(VL_RENDA_FAT) VL_RENDA_FAT, SUM(VL_OPER) VL_CONS, COUNT(*) QT_CONS 
 FROM TB_TRANS T 
 WHERE T.CD_TP_PESSOA  = 'F' 
   AND T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
   AND T.FL_ANALISADO = 1
   AND T.CD_TP_OPER    = 4 /*deposito*/ 
   AND T.CD_FORMA_OPER = 7 /*especie*/    
   AND ((T.VL_RENDA_FAT IS NOT NULL AND T.VL_RENDA_FAT <= (:pm_ValorRendaBaixa)) 
        OR 
        T.VL_RENDA_FAT IS NULL) 
   GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO    
   ) T1    
WHERE T1.QT_CONS >= (:pm_QtdeDepEspecieRendaBaixa) 
  AND T1.VL_CONS >=  (:pm_ValorDepEspecieRendaBaixa) 
 
UNION ALL 
 
SELECT  T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: 211 – Depósitos em espécie fracionados, no último mês calendário fechado. |' ||    
'Objetivo: Verificar valores incompatíveis depósitos em espécie fracionados, no último mês calendário fechado, com a renda ou faturamento do cliente, por faixas. |' ||    
'Conclusão: Depósitos em espécie fracionados, no último mês calendário fechado. Cliente com renda alta.  |' ||    
'Cliente: ' ||  T1.NM_CLIE || '|' ||   
'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)    
|| '|' ||    
'Mês/Ano: ' || SUBSTR(:cd_lote,5,2) || '/' || SUBSTR(:cd_lote,1,4) ||  '|' ||   
'Renda:' || COALESCE(TO_CHAR(VL_RENDA_FAT, 'L999G999G999G990D99'),'Renda não informada')  ||  '|' ||    
'Valor consolidado de Depósitos em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(VL_CONS, 'L999G999G999G990D99')  ||  '|' ||   
'Quantidade consolidada de Depósitos em Espécie, por cliente, no últmo mês calendário fechado:' || TO_CHAR(QT_CONS, '999999990')  ||  '|' ||   
'Parâmetro que indica o limite para que uma renda possa ser considerada baixa (pm_ValorRendaBaixa):' || (SELECT TO_CHAR(:pm_ValorRendaBaixa, 'L999G999G999G990D99') FROM DUAL) ||  '|' || 
'Parâmetro percentual para flexibilização de renda alta (pm_PercRendaAlta):' || (SELECT TO_CHAR(:pm_PercRendaAlta, '999999990D99') FROM DUAL) ||  '|' || 
'Parâmetro que indica quantidade expressiva de depósitos em espécie, para renda alta, no último mês calendário fechado, para pessoa física (pm_QtdeDepEspecieRendaAlta):' || (SELECT TO_CHAR(:pm_QtdeDepEspecieRendaAlta, '999999990') FROM DUAL) ||  '|' || 
'Parâmetro que indica valor expressivo de depósitos em espécie, para renda alta, no último mês calendário fechado), para pessoa física (pm_ValorDepEspecieRendaAlta):' || (SELECT TO_CHAR(:pm_ValorDepEspecieRendaAlta, 'L999G999G999G990D99') FROM DUAL)  
AS DS_INF_ANLSE     
FROM  
(SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO, MAX(T.NM_CLIE) NM_CLIE, MAX(VL_RENDA_FAT) VL_RENDA_FAT, SUM(VL_OPER) VL_CONS, COUNT(*) QT_CONS 
 FROM TB_TRANS T 
 WHERE T.CD_TP_PESSOA  = 'F' 
   AND T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
   AND T.FL_ANALISADO = 1
   AND T.CD_TP_OPER    = 4 /*deposito*/ 
   AND T.CD_FORMA_OPER = 7 /*especie*/    
   AND (T.VL_RENDA_FAT IS NOT NULL AND T.VL_RENDA_FAT > (:pm_ValorRendaBaixa)) 
  GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO    
   ) T1    
WHERE T1.QT_CONS >= (:pm_QtdeDepEspecieRendaAlta) 
  AND T1.VL_CONS >= (:pm_ValorDepEspecieRendaAlta) 
  AND T1.VL_CONS >= (T1.VL_RENDA_FAT * (:pm_PercRendaAlta/100)) 
 
UNION ALL 
 
SELECT  T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: 211 – Depósitos em espécie fracionados, no último mês calendário fechado. |' ||    
'Objetivo: Verificar valores incompatíveis depósitos em espécie fracionados, no último mês calendário fechado, com a renda ou faturamento do cliente, por faixas. |' ||    
'Conclusão: Depósitos em espécie fracionados, no último mês calendário fechado. Cliente com faturamento baixo.  |' ||    
'Cliente: ' ||  T1.NM_CLIE || '|' ||   
'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)     
|| '|' ||    
'Mês/Ano: ' || SUBSTR(:cd_lote,5,2) || '/' || SUBSTR(:cd_lote,1,4) ||  '|' ||   
'Faturamento:' || COALESCE(TO_CHAR(VL_RENDA_FAT, 'L999G999G999G990D99'),'Faturamento não informado')  ||  '|' ||    
'Quantidade consolidada de Depósitos em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(QT_CONS, '999999990')  ||  '|' ||   
'Valor consolidado de Depósitos em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(VL_CONS, 'L999G999G999G990D99')  ||  '|' ||   
'Parâmetro que indica o limite para que um faturamento possa ser considerado baixo (pm_ValorFaturamentoBaixo):' || (SELECT TO_CHAR(:pm_ValorFaturamentoBaixo, 'L999G999G999G990D99') FROM DUAL) ||  '|' || 
'Parâmetro que indica quantidade expressiva de depósitos em espécie, para faturamento baixo, no último mês calendário fechado, para pessoa jurídica (pm_QtdeDepEspecieFatBaixo):' || (SELECT TO_CHAR(:pm_QtdeDepEspecieFatBaixo, '999999990') FROM DUAL) ||  '|' || 
'Parâmetro que indica valor expressivo de depósitos em espécie, para faturamento baixo, no último mês calendário fechado, para pessoa jurídica (pm_ValorDepEspecieFatBaixo):' || (SELECT TO_CHAR(:pm_ValorDepEspecieFatBaixo, 'L999G999G999G990D99') FROM DUAL) 
AS DS_INF_ANLSE     
FROM  
(SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO, MAX(T.NM_CLIE) NM_CLIE, MAX(VL_RENDA_FAT) VL_RENDA_FAT, SUM(VL_OPER) VL_CONS, COUNT(*) QT_CONS 
 FROM TB_TRANS T 
 WHERE T.CD_TP_PESSOA  = 'J' 
   AND T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
   AND T.FL_ANALISADO  = 1
   AND T.CD_TP_OPER    = 4 /*deposito*/ 
   AND T.CD_FORMA_OPER = 7 /*especie*/    
   AND ((T.VL_RENDA_FAT IS NOT NULL AND T.VL_RENDA_FAT <= (:pm_ValorFaturamentoBaixo)) 
        OR 
        T.VL_RENDA_FAT IS NULL) 
   GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO    
   ) T1    
WHERE T1.QT_CONS >= (:pm_QtdeDepEspecieFatBaixo) 
  AND T1.VL_CONS >=  (:pm_ValorDepEspecieFatBaixo) 
   
UNION ALL 
 
SELECT  T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: 211 – Depósitos em espécie fracionados, no último mês calendário fechado. |' ||    
'Objetivo: Verificar valores incompatíveis depósitos em espécie fracionados, no último mês calendário fechado, com a renda ou faturamento do cliente, por faixas. |' ||    
'Conclusão: Depósitos em espécie fracionados, no último mês calendário fechado. Cliente com faturamento alto.  |' ||    
'Cliente: ' ||  T1.NM_CLIE || '|' ||   
'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)     
|| '|' ||    
'Mês/Ano: ' || SUBSTR(:cd_lote,5,2) || '/' || SUBSTR(:cd_lote,1,4) ||  '|' ||   
'Faturamento:' || COALESCE(TO_CHAR(VL_RENDA_FAT, 'L999G999G999G990D99'),'Faturamento não informado')  ||  '|' ||    
'Valor consolidado de Depósitos em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(VL_CONS, 'L999G999G999G990D99')  ||  '|' ||   
'Quantidade consolidada de Depósitos em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(QT_CONS, '999999990')  ||  '|' ||   
'Parâmetro que indica o limite para que um faturamento possa ser considerado baixo (pm_ValorFaturamentoBaixo):' || (SELECT TO_CHAR(:pm_ValorFaturamentoBaixo, 'L999G999G999G990D99') FROM DUAL) ||  '|' || 
'Parâmetro percentual para flexibilização de faturamento alto (pm_PercFaturamentoAlto):' || (SELECT TO_CHAR(:pm_PercFaturamentoAlto, '999999990D99') FROM DUAL) ||  '|' || 
'Parâmetro que indica quantidade expressiva de depósitos em espécie, para faturamento alto, no último mês calendário fechado, para pessoa jurídica. (pm_QtdeDepEspecieFatAlto):' || (SELECT TO_CHAR(:pm_QtdeDepEspecieFatAlto, '999999990') FROM DUAL) ||  '|' || 
'Parâmetro que indica valor expressivo de depósitos em espécie, para faturamento alto, no último mês calendário fechado, para pessoa jurídica (pm_ValorDepEspecieFatAlto):' || (SELECT TO_CHAR(:pm_ValorDepEspecieFatAlto, 'L999G999G999G990D99') FROM DUAL) 
AS DS_INF_ANLSE     
FROM  
(SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO, MAX(T.NM_CLIE) NM_CLIE, MAX(VL_RENDA_FAT) VL_RENDA_FAT, SUM(VL_OPER) VL_CONS, COUNT(*) QT_CONS 
 FROM TB_TRANS T 
 WHERE T.CD_TP_PESSOA  = 'J' 
   AND T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
   AND T.FL_ANALISADO  = 1
   AND T.CD_TP_OPER    = 4 /*deposito*/ 
   AND T.CD_FORMA_OPER = 7 /*especie*/    
   AND (T.VL_RENDA_FAT IS NOT NULL AND T.VL_RENDA_FAT > (:pm_ValorFaturamentoBaixo)) 
  GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO    
   ) T1    
WHERE T1.QT_CONS >= (:pm_QtdeDepEspecieFatAlto) 
  AND T1.VL_CONS >= (:pm_ValorDepEspecieFatAlto) 
  AND T1.VL_CONS >= (T1.VL_RENDA_FAT * (:pm_PercFaturamentoAlto/100)) 
 
  
   
