/* VERSAO 1 */

SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,      
'Análise: Regra 207 – Movimentação expressiva para Renda/Faturamento Baixo (Faixa 4) |' ||     
'Objetivo: Movimentação expressiva para Renda/Faturamento Baixo (Faixa 4) |' ||     
'Conclusão: Cliente com movimentação expressiva para Renda/Faturamento Baixo (Faixa 4) |' ||     
'Cliente: ' ||  T.NM_CLIE || '|' ||    
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||     
'Mês/Ano de Referência: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) ||  '|' ||     
'Natureza: Crédito |' ||   
'Valor da Renda: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'),'Renda não informada') || '|' ||   
'Valor Consolidado: ' || TO_CHAR(T.VL_TOTAL, 'L999G999G999G990D99')|| '|' ||    
'Parâmetro que indica o valor limite da quarta faixa para uma Renda ser considerada Baixa, para pessoa física (pm_ValorRendaBaixaFaixa4): ' || COALESCE((SELECT TO_CHAR(:pm_ValorRendaBaixaFaixa4, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro que indica valor inicial da quarta faixa para valores de créditos, consolidados no mês calendário fechado (Mês do Processamento) (pm_ValorInfFaixa4_PF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorInfFaixa4_PF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE    
FROM (SELECT T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.CD_MES_ANO, MAX(T1.NM_CLIE) NM_CLIE, SUM(VL_OPER) VL_TOTAL, 
      MAX(T1.VL_RENDA_FAT) VL_RENDA_FAT   
      FROM TB_TRANS T1  
      WHERE T1.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
      AND T1.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
      AND T1.FL_ANALISADO = 1     
      AND T1.CD_TP_PESSOA = 'F'   
      AND T1.CD_NATUR_OPER = 1   
      GROUP BY T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.CD_MES_ANO) T   
     WHERE ((T.VL_RENDA_FAT IS NOT NULL AND   
             T.VL_RENDA_FAT <= (:pm_ValorRendaBaixaFaixa4)   
            )  
            OR  
            T.VL_RENDA_FAT IS NULL  
           )  
     AND T.VL_TOTAL >= (:pm_ValorInfFaixa4_PF)  
UNION ALL   
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,      
'Análise: Regra 207 – Movimentação expressiva para Renda/Faturamento Baixo (Faixa 4) |' ||     
'Objetivo: Movimentação expressiva para Renda/Faturamento Baixo (Faixa 4) |' ||     
'Conclusão: Cliente com movimentação expressiva para Renda/Faturamento Baixo (Faixa 4) |' ||      
'Cliente: ' ||  T.NM_CLIE || '|' ||    
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||     
'Mês/Ano de Referência: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) ||  '|' ||     
'Natureza: Crédito |' ||   
'Valor do Faturamento: ' || COALESCE(TO_CHAR(T.VL_RENDA_FAT, 'L999G999G999G990D99'),'Faturamento não informado') || '|' ||   
'Valor Consolidado: ' || TO_CHAR(T.VL_TOTAL, 'L999G999G999G990D99')|| '|' ||    
'Parâmetro que indica o valor limite da quarta faixa para um Faturamento ser considerado Baixo, para pessoa jurídica (pm_ValorFaturamentoBaixoFaixa4): ' || COALESCE((SELECT TO_CHAR(:pm_ValorFaturamentoBaixoFaixa4, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro que indica valor inicial da quarta faixa para valores de créditos, consolidados no mês calendário fechado (Mês do Processamento) (pm_ValorInfFaixa4_PJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorInfFaixa4_PJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'  
AS DS_INF_ANLSE    
FROM (SELECT T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.CD_MES_ANO, MAX(T1.NM_CLIE) NM_CLIE, SUM(VL_OPER) VL_TOTAL,   
      MAX(T1.VL_RENDA_FAT) VL_RENDA_FAT   
      FROM TB_TRANS T1  
      WHERE T1.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
      AND T1.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)    
      AND T1.FL_ANALISADO = 1   
      AND T1.CD_TP_PESSOA = 'J'   
      AND T1.CD_NATUR_OPER = 1    
      GROUP BY T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, T1.CD_MES_ANO) T   
     WHERE ((T.VL_RENDA_FAT IS NOT NULL AND   
             T.VL_RENDA_FAT <= (:pm_ValorFaturamentoBaixoFaixa4)   
            )  
            OR  
            T.VL_RENDA_FAT IS NULL  
           )  
     AND T.VL_TOTAL >= (:pm_ValorInfFaixa4_PJ)  
  
  
