SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,      
'Análise: Regra 41 - Abertura de conta por procuração ou mandato (Pessoa Física) |' ||     
'Objetivo: b) Abertura, movimentação de contas ou realização de operações por detentor de procuração ou de qualquer outro tipo de mandato. C.C. Bacen n.3.542/2012, Art. 1º, Inciso III |' ||     
'Conclusão: Abertura, movimentação de contas ou realização de operações por detentor de procuração ou de qualquer outro tipo de mandato |' ||     
'Cliente: ' ||  T.NM_CLIE || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||   
'Mês/Ano: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) ||  '|' ||    
xmlcast(xmlagg(xmlelement(cadeia, 
CASE CD_TP_IDENTF_REPRE   
	WHEN 2 THEN 'Representante: CPF: ' || SUBSTR(CD_DOC_IDENTF_REPRE, 1, 3) || '.' || SUBSTR(CD_DOC_IDENTF_REPRE, 4, 3) || '.' || SUBSTR(CD_DOC_IDENTF_REPRE, 7, 3) || '-' || SUBSTR(CD_DOC_IDENTF_REPRE, 10, 2) || ' - Nome: ' || NM_REPRE        
	WHEN 3 THEN 'Representante: CNPJ: ' ||SUBSTR(CD_DOC_IDENTF_REPRE, 1, 2) || '.' || SUBSTR(CD_DOC_IDENTF_REPRE, 3, 3) || '.' || SUBSTR(CD_DOC_IDENTF_REPRE, 6, 3) || '/' || SUBSTR(CD_DOC_IDENTF_REPRE, 9, 4) || '-'  || SUBSTR(CD_DOC_IDENTF_REPRE, 13, 2)  || ' - Nome: ' || NM_REPRE        
	ELSE CD_DOC_IDENTF_REPRE    
END        
|| '| ')    
order by CD_DOC_IDENTF_REPRE) as clob)                             
AS DS_INF_ANLSE     
FROM (SELECT T1.CD_MES_ANO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE, MAX(T1.NM_CLIE) NM_CLIE   
      FROM TB_TRANS T1  
      WHERE T1.CD_TP_PESSOA = 'F'  
      AND T1.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
      AND T1.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)     
      AND T1.FL_ANALISADO = 1  
      GROUP BY T1.CD_MES_ANO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE  
     ) T  
INNER JOIN TB_TRANSMISSAO_ORDEM TO1 
ON TO1.CD_DOC_IDENTF_CLIE = T.CD_DOC_IDENTF_CLIE  
AND TO1.CD_TP_IDENTF_CLIE = T.CD_TP_IDENTF_CLIE  
GROUP BY T.CD_MES_ANO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.NM_CLIE 

