SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,      
'Análise: Regra 111 - Movimentação ou serviço envolvendo pessoa relacionada a atividades terroristas |' ||     
'Objetivo: B) Realização de operações ou prestação de serviços, qualquer que seja o valor, a pessoas que reconhecidamente tenham cometido ou intentado cometer atos terroristas, ou deles participado ou facilitado o seu cometimento. C.C. Bacen n.3.542/2012, Art. 1º, Inciso X |' ||     
'Conclusão: Movimentação ou serviço envolvendo pessoa relacionada a atividades terroristas |' ||     
'Cliente: ' ||  T.NM_CLIE || '|' ||    
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||     
'Mês/Ano de Referência: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) ||  '|' ||    
'Análise: Cliente está em Listas Restritivas Internacionais do DTEC-flex e Destino/Origem não pertence à Lista Auxiliar Branca. |' ||    
'Dados do Destino/Origem: Informações sobre as transações |' ||    
xmlcast(  xmlagg(xmlelement(outros,   
CASE T.CD_TP_IDENTF_DESTORIG   
	WHEN 2 THEN 'CPF-' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 10, 2)   
	WHEN 3 THEN 'CNPJ-' ||SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 13, 2)    
	ELSE T.CD_DOC_IDENTF_DESTORIG   
END   
|| ' - ' || COALESCE(NM_DESTORIG,'Nome não cadastrado') || ': ' || 'Valor consolidado ' || LTRIM(TO_CHAR(VL_TOTAL, 'L999G999G999G990D99')) || ' - Quantidade de Transações ' || TO_CHAR(QT_TOTAL)   
|| '|')    
order by T.CD_DOC_IDENTF_DESTORIG) as clob)   
AS DS_INF_ANLSE      
FROM (SELECT NM_CLIE, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_MES_ANO, CD_DOC_IDENTF_DESTORIG, CD_TP_IDENTF_DESTORIG, NM_DESTORIG, QT_TOTAL, VL_TOTAL,  DT_REF  
      FROM (SELECT MAX(NM_CLIE) NM_CLIE, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_MES_ANO, CD_DOC_IDENTF_DESTORIG, CD_TP_IDENTF_DESTORIG, NM_DESTORIG, COUNT(*) QT_TOTAL, SUM(VL_OPER) VL_TOTAL, MAX(DT_TRANS) DT_REF  
            FROM TB_TRANS 
            WHERE DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
            AND DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
            AND CD_DOC_IDENTF_DESTORIG IS NOT NULL 
            AND FL_ANALISADO = 1
            GROUP BY CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_MES_ANO, CD_DOC_IDENTF_DESTORIG, CD_TP_IDENTF_DESTORIG, NM_DESTORIG) T  
      WHERE EXISTS (SELECT 1 FROM TB_NOTICIA_CLIE N 
                    WHERE N.CD_DOC_IDENTF_CLIE = T.CD_DOC_IDENTF_CLIE 
                    AND N.CD_TP_IDENTF_CLIE  = T.CD_TP_IDENTF_CLIE 
                    AND N.NM_FONTE_NOTICIA LIKE '%LISTA - %' 
                    AND (UPPER(N.NM_TP_SUSP) <> 'GOVERNO'   
                         AND UPPER(N.NM_TP_SUSP) <> 'SOCIOAMBIENTAL'   
                         AND UPPER(N.NM_TP_SUSP) <> 'LISTAS DIVERSAS' 
                        )          
                   )    
      AND NOT EXISTS (SELECT 1 FROM TB_CONTEUDO_LISTA_AUXILIAR CLA  
                      WHERE CLA.CD_LISTA_AUXILIAR = 100               
                      AND CLA.DS_CONTEUDO LIKE '%' || T.CD_DOC_IDENTF_DESTORIG || '%'      
                     ) 
     ) T  
GROUP BY NM_CLIE, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_MES_ANO 
     
UNION ALL    
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,      
'Análise: Regra 111 - Movimentação ou serviço envolvendo pessoa relacionada a atividades terroristas |' ||     
'Objetivo: B) Realização de operações ou prestação de serviços, qualquer que seja o valor, a pessoas que reconhecidamente tenham cometido ou intentado cometer atos terroristas, ou deles participado ou facilitado o seu cometimento. C.C. Bacen n.3.542/2012, Art. 1º, Inciso X |' ||     
'Conclusão: Movimentação ou serviço envolvendo pessoa relacionada a atividades terroristas |' ||     
'Cliente: ' ||  T.NM_CLIE || '|' ||    
CASE T.CD_TP_IDENTF_CLIE     
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)     
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)      
	ELSE T.CD_DOC_IDENTF_CLIE     
END     
|| '|' ||     
'Mês/Ano de Referência: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) ||  '|' ||   
'Análise: O cliente está em Listas Restritivas Internacionais do DTEC-flex e o Destino/Origem pertence à Lista Auxiliar Restritiva. |' ||    
'Dados do Destino/Origem: Informações sobre as transações |' ||    
xmlcast(  xmlagg(xmlelement(outros,   
CASE T.CD_TP_IDENTF_DESTORIG   
	WHEN 2 THEN 'CPF-' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 10, 2)   
	WHEN 3 THEN 'CNPJ-' ||SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_DESTORIG, 13, 2)    
	ELSE T.CD_DOC_IDENTF_DESTORIG   
END   
|| ' - ' || COALESCE(NM_DESTORIG,'Nome não cadastrado') || ': ' || 'Valor consolidado ' || LTRIM(TO_CHAR(VL_TOTAL, 'L999G999G999G990D99')) || ' - Quantidade de Transações ' || TO_CHAR(QT_TOTAL)    
|| '|')    
order by T.CD_DOC_IDENTF_DESTORIG) as clob)   
AS DS_INF_ANLSE         
FROM (SELECT NM_CLIE, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_MES_ANO, CD_DOC_IDENTF_DESTORIG, CD_TP_IDENTF_DESTORIG, NM_DESTORIG, QT_TOTAL, VL_TOTAL,  DT_REF  
      FROM (SELECT MAX(NM_CLIE) NM_CLIE, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_MES_ANO, CD_DOC_IDENTF_DESTORIG, CD_TP_IDENTF_DESTORIG, NM_DESTORIG, COUNT(*) QT_TOTAL, SUM(VL_OPER) VL_TOTAL, MAX(DT_TRANS) DT_REF  
            FROM TB_TRANS 
            WHERE DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
            AND DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
            AND FL_ANALISADO = 1 
            AND CD_DOC_IDENTF_DESTORIG IS NOT NULL 
            GROUP BY CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_MES_ANO, CD_DOC_IDENTF_DESTORIG, CD_TP_IDENTF_DESTORIG, NM_DESTORIG) T  
      WHERE EXISTS (SELECT 1 FROM TB_NOTICIA_CLIE N 
                    WHERE N.CD_DOC_IDENTF_CLIE = T.CD_DOC_IDENTF_CLIE 
                    AND N.CD_TP_IDENTF_CLIE  = T.CD_TP_IDENTF_CLIE 
                    AND N.NM_FONTE_NOTICIA LIKE '%LISTA - %' 
                    AND (UPPER(N.NM_TP_SUSP) <> 'GOVERNO'   
                         AND UPPER(N.NM_TP_SUSP) <> 'SOCIOAMBIENTAL'  
                         AND UPPER(N.NM_TP_SUSP) <> 'LISTAS DIVERSAS'  
                        )          
                   )    
     AND EXISTS (SELECT 1 FROM TB_CONTEUDO_LISTA_AUXILIAR CLA     
                 WHERE CLA.CD_LISTA_AUXILIAR = 107              
                 AND CLA.DS_CONTEUDO LIKE '%' || T.CD_DOC_IDENTF_DESTORIG || '%'       
                ) 
    ) T  
GROUP BY NM_CLIE, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, CD_MES_ANO 
   
   
