SELECT  T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: Regra 42 – Atividades econômicas sensíveis à lavagem de dinheiro |' ||    
'Objetivo: Pessoa Natural ou Pessoa Jurídica envolvida em atividades econômicas indicadas em normas legais ou regulamentares como sensíveis à lavagem de dinheiro. |' ||    
'Conclusão: Cliente envolvido em atividades econômicas sensíveis à lavagem de dinheiro  |' ||    
'Cliente: ' ||  T1.NM_CLIE || '|' ||   
CASE T1.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T1.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||    
'Mês/Ano: ' || SUBSTR(T1.CD_MES_ANO,5,2) || '/' || SUBSTR(T1.CD_MES_ANO,1,4) ||  '|' ||   
'Ocupação: ' || TO_CHAR(T1.CD_OCUP) || '-' || COALESCE((SELECT NM_OCUP FROM TB_OCUP A WHERE A.CD_OCUP = T1.CD_OCUP),'Nome não cadastrado')  
AS DS_INF_ANLSE     
FROM (SELECT T.CD_MES_ANO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, C.CD_OCUP, MAX(T.NM_CLIE) NM_CLIE  
      FROM TB_TRANS T, TB_CLIE_RENDA C 
      WHERE T.CD_DOC_IDENTF_CLIE = C.CD_DOC_IDENTF_CLIE AND T.CD_TP_IDENTF_CLIE = C.CD_TP_IDENTF_CLIE 
      AND T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
      AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
      AND T.FL_ANALISADO = 1
     GROUP BY T.CD_MES_ANO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, C.CD_OCUP 
      ) T1 
WHERE EXISTS (SELECT 1 FROM TB_OCUP O WHERE O.CD_OCUP = T1.CD_OCUP AND O.FL_OCUP_SUSP = 1) 
       
UNION 
 
SELECT  T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: Regra 42 – Atividades econômicas sensíveis à lavagem de dinheiro |' ||    
'Objetivo: Pessoa Natural ou Pessoa Jurídica envolvida em atividades econômicas indicadas em normas legais ou regulamentares como sensíveis à lavagem de dinheiro. |' ||    
'Conclusão: Cliente envolvido em atividades econômicas sensíveis à lavagem de dinheiro  |' ||    
'Cliente: ' ||  T1.NM_CLIE || '|' ||   
CASE T1.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T1.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||    
'Mês/Ano: ' || SUBSTR(T1.CD_MES_ANO,5,2) || '/' || SUBSTR(T1.CD_MES_ANO,1,4) ||  '|' ||   
'Ramo de atividade: ' || TO_CHAR(T1.CD_RAMO_ATIVID) || '-' || COALESCE((SELECT NM_RAMO_ATIVID FROM TB_RAMO_ATIVID A WHERE A.CD_RAMO_ATIVID = T1.CD_RAMO_ATIVID),'Nome não cadastrado')  
AS DS_INF_ANLSE     
FROM (SELECT T.CD_MES_ANO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_RAMO_ATIVID, MAX(T.NM_CLIE) NM_CLIE  
      FROM TB_TRANS T 
      WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
      AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
      AND T.FL_ANALISADO = 1
      AND T.CD_RAMO_ATIVID IS NOT NULL 
      GROUP BY T.CD_MES_ANO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_RAMO_ATIVID 
      ) T1 
WHERE EXISTS (SELECT 1 FROM TB_RAMO_ATIVID O WHERE O.CD_RAMO_ATIVID = T1.CD_RAMO_ATIVID AND O.FL_RAMO_SUSP = 1) 
 
   