SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,       
'Análise: Regra 404 - Pagamento antecipado de consórcio. |' ||     
'Objetivo: E) Pagamento antecipado de quantidade expressiva de prestação vincendas, não condizente com a capacidade econômico-financeira do consorciado. C.C. Bacen n.3.542/2012, Art. 1º, Inciso IX. |' ||     
'Conclusão: Pagamento antecipado de quantidade expressiva de prestação vincendas, não condizente com a capacidade economico-financeira do consorciado |' ||     
'Cliente: ' ||  MAX(T.NM_CLIE) || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||    
'Mês/Ano: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) ||  '|' ||    
'Código do Contrato: ' || T.CD_CONTRATO || '|' ||   
'Data de Vencimento do Contrato: ' || COALESCE(TO_CHAR(MAX(C.DT_VENCTO_CONTRATO),'DD/MM/YYYY'), 'Data não cadastrada') || '|' ||    
'Quantidade de Pagamentos de Consórcio realizadas no mês anterior: ' || TO_CHAR(COUNT(*)) || '|' ||   
'Valor da Parcela do Contrato: ' || COALESCE(TO_CHAR(MAX(C.VL_PCELA_CONTRATO), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' || 
'Quantidade de meses faltantes: ' || TO_CHAR(MONTHS_BETWEEN(MAX(DT_VENCTO_CONTRATO), TO_DATE(TO_CHAR(:cd_lote ) || '01', 'YYYY-MM-DD'))) || '|' || 
'Valor Renda: ' || COALESCE(TO_CHAR(MAX(T.VL_RENDA_FAT), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||   
'Parâmetro percentual de flexibilização da renda (pm_PercRenda): ' || COALESCE((SELECT TO_CHAR(:pm_PercRenda, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro valor mínimo de pagamentos realizados para Pessoa Física (pm_ValorMinimoPF): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPF, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro quantidade flexibilização de meses Faltantes para Término do Consórcio Pessoa Física (pm_QtdeMesesFaltantesPF): ' || COALESCE((':pm_QtdeMesesFaltantesPF'),'Parâmetro não cadastrado') || '|' ||   
'Parâmetro quantidade flexibilização de meses pagos Pessoa Física (pm_QtdeMesesPagosPF): ' || COALESCE((':pm_QtdeMesesPagosPF'),'Parâmetro não cadastrado') || '|'     
AS DS_INF_ANLSE      
FROM TB_TRANS T  
INNER JOIN TB_CONTRATO C ON T.CD_CONTRATO = C.CD_CONTRATO   
WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
  AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
  AND T.FL_ANALISADO = 1
  AND T.CD_TP_OPER = 66   
  AND C.CD_SIT_CONSORCIO = 1  
  AND T.CD_TP_PESSOA = 'F'  
  AND MONTHS_BETWEEN(TO_DATE(TO_CHAR(:cd_lote ) || '01', 'YYYY-MM-DD'),DT_VENCTO_CONTRATO) < (:pm_QtdeMesesFaltantesPF)   
 GROUP BY T.CD_MES_ANO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_CONTRATO      		      
HAVING COUNT(*) > (:pm_QtdeMesesPagosPF)     
  AND ( 
       (MAX(T.VL_RENDA_FAT) IS NOT NULL AND     
       (MAX(C.VL_PCELA_CONTRATO) * COUNT(*)) > (MAX(T.VL_RENDA_FAT) * (:pm_PercRenda/100))     
       ) 
       OR     
       (MAX(T.VL_RENDA_FAT) IS NULL AND   
       (MAX(C.VL_PCELA_CONTRATO) * COUNT(*)) > (:pm_ValorMinimoPF))    
      ) 
UNION ALL 
 
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,       
'Análise: Regra 404 - Pagamento antecipado de consórcio. |' ||     
'Objetivo: E) Pagamento antecipado de quantidade expressiva de prestação vincendas, não condizente com a capacidade econômico-financeira do consorciado. C.C. Bacen n.3.542/2012, Art. 1º, Inciso IX. |' ||     
'Conclusão: Pagamento antecipado de quantidade expressiva de prestação vincendas, não condizente com a capacidade economico-financeira do consorciado |' ||     
'Cliente: ' ||  MAX(T.NM_CLIE) || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||    
'Mês/Ano: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) ||  '|' ||    
'Código do Contrato: ' || T.CD_CONTRATO || '|' ||   
'Data de Vencimento do Contrato: ' || COALESCE(TO_CHAR(MAX(C.DT_VENCTO_CONTRATO),'DD/MM/YYYY'), 'Data não cadastrada') || '|' ||    
'Quantidade de Pagamentos de Consórcio realizadas no mês anterior: ' || TO_CHAR(COUNT(*)) || '|' ||   
'Valor da Parcela do Contrato: ' || COALESCE(TO_CHAR(MAX(C.VL_PCELA_CONTRATO), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||   
'Quantidade de meses faltantes: ' || TO_CHAR(MONTHS_BETWEEN(MAX(DT_VENCTO_CONTRATO), TO_DATE(TO_CHAR(:cd_lote ) || '01', 'YYYY-MM-DD'))) || '|' || 
'Valor Renda: ' || COALESCE(TO_CHAR(MAX(T.VL_RENDA_FAT), 'L999G999G999G990D99'), 'Valor não cadastrado') || '|' ||   
'Parâmetro percentual de flexibilização da faturamento (pm_PercFaturamento): ' || COALESCE((SELECT TO_CHAR(:pm_PercFaturamento, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro valor mínimo de pagamentos realizados para Pessoa Física (pm_ValorMinimoPJ): ' || COALESCE((SELECT TO_CHAR(:pm_ValorMinimoPJ, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||     
'Parâmetro quantidade flexibilização de meses Faltantes para Término do Consórcio Pessoa jurídica (pm_QtdeMesesFaltantesPF): ' || COALESCE((':pm_QtdeMesesFaltantesPJ'),'Parâmetro não cadastrado') || '|' ||   
'Parâmetro quantidade flexibilização de meses pagos Pessoa Física (pm_QtdeMesesPagosPJ): ' || COALESCE((':pm_QtdeMesesPagosPJ'),'Parâmetro não cadastrado') || '|'     
AS DS_INF_ANLSE      
FROM TB_TRANS T  
INNER JOIN TB_CONTRATO C ON T.CD_CONTRATO = C.CD_CONTRATO   
WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
  AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
  AND T.FL_ANALISADO = 1
  AND T.CD_TP_OPER = 66   
  AND C.CD_SIT_CONSORCIO = 1  
  AND T.CD_TP_PESSOA = 'J'  
  AND MONTHS_BETWEEN(TO_DATE(TO_CHAR(:cd_lote ) || '01', 'YYYY-MM-DD'), DT_VENCTO_CONTRATO) < (:pm_QtdeMesesFaltantesPJ)   
 GROUP BY T.CD_MES_ANO, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_CONTRATO      		      
HAVING COUNT(*) > (:pm_QtdeMesesPagosPJ)     
  AND ( 
       (MAX(T.VL_RENDA_FAT) IS NOT NULL AND     
       (MAX(C.VL_PCELA_CONTRATO) * COUNT(*)) > (MAX(T.VL_RENDA_FAT) * (:pm_PercFaturamento/100))     
       ) 
       OR     
       (MAX(T.VL_RENDA_FAT) IS NULL AND   
       (MAX(C.VL_PCELA_CONTRATO) * COUNT(*)) > (:pm_ValorMinimoPJ))    
      ) 
       
      