/* a) movimentaçoes financeiras envolvendo pessoas relacionadas a atividades terroristas listadas pelo Conselho de Segurança das Nações Unidas; */    
    
SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,      
'Análise: Regra 303 – Crimes Sociambientais |' ||     
'Objetivo: Clientes que estejam na base DTEC-flex, categoria Crimes Socioambientais |' ||     
'Conclusão: Cliente consta na base DTEC-Flex, categoria Crimes Socioambientais |' ||     
'Cliente: ' ||  T.NM_CLIE || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|'  || 
'Mês/Ano de Referência: ' || SUBSTR(T.CD_MES_ANO,5,2) || '/' || SUBSTR(T.CD_MES_ANO,1,4) || '|'  
AS DS_INF_ANLSE      
FROM (SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO, MAX(T.NM_CLIE) NM_CLIE FROM TB_TRANS T   
      WHERE T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
      AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)   
      AND T.FL_ANALISADO = 1   
      GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO) T  
WHERE EXISTS (SELECT 1 FROM TB_NOTICIA_CLIE N  
              WHERE N.CD_DOC_IDENTF_CLIE = T.CD_DOC_IDENTF_CLIE  
              AND N.CD_TP_IDENTF_CLIE  = T.CD_TP_IDENTF_CLIE  
              AND UPPER(NM_TP_SUSP) = 'SOCIOAMBIENTAL' 
              AND NM_FONTE_NOTICIA NOT LIKE '%LISTA PARIS%'  
             )   
 

 