SELECT DISTINCT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,     
'Análise: Regra 110 - Movimentação envolvendo pessoa relacionada a atividades terroristas |' ||    
'Objetivo: A) Movimentações financeiras envolvendo pessoas relacionadas a atividades terroristas listadas pelo Conselho de Segurança das Nações Unidas. C.C. Bacen n.3.542/2012, Art. 1º, Inciso X |' ||    
'Conclusão: Movimentações financeiras envolvendo pessoas relacionadas a atividades terroristas listadas pelo Conselho de Segurança das Nações Unidas |' ||    
'Cliente: ' ||  T.NM_CLIE || '|' ||   
CASE T.CD_TP_IDENTF_CLIE    
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)    
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)     
	ELSE T.CD_DOC_IDENTF_CLIE    
END    
|| '|' ||    
'Mês/Ano de Referência: ' || SUBSTR(:cd_lote,5,2) || '/' || SUBSTR(:cd_lote,1,4) ||  '|' ||    
'Cliente está em Lista CSNU (Lista - UN SECURITY COUNCIL SANCTIONS LIST) do DTEC-flex e não pertence à Lista Branca. |'    
AS DS_INF_ANLSE     
FROM TB_CAD_CLIE T   
WHERE EXISTS 
(SELECT 1 FROM TB_TRANS C 
WHERE C.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
  AND C.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
  AND C.FL_ANALISADO = 1 
  AND T.CD_DOC_IDENTF_CLIE = C.CD_DOC_IDENTF_CLIE AND T.CD_TP_IDENTF_CLIE = C.CD_TP_IDENTF_CLIE
)
AND EXISTS (SELECT 1 FROM TB_NOTICIA_CLIE N 
            WHERE N.CD_DOC_IDENTF_CLIE = T.CD_DOC_IDENTF_CLIE 
            AND N.CD_TP_IDENTF_CLIE  = T.CD_TP_IDENTF_CLIE     
            AND NM_FONTE_NOTICIA = 'LISTA - UN SECURITY COUNCIL SANCTIONS LIST' 
           )  
AND NOT EXISTS (SELECT 1 FROM TB_CONTEUDO_LISTA_AUXILIAR CLA 
                WHERE CLA.DS_CONTEUDO LIKE '%' || T.CD_DOC_IDENTF_CLIE || '%' 
                AND CLA.CD_LISTA_AUXILIAR = 100   
               )            
              

   
  
  
  