SELECT DISTINCT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE,   
'Análise: Regra 12 - Histórico de Índicio de Lavagem de Dinheiro confirmada |' ||  
'Objetivo: Cliente com histórico de indício de Lavagem de Dinheiro confirmada |' ||  
'Conclusão: Histórico de indício de Lavagem de dinheiro confirmada |' ||  
'Cliente: ' ||  T.NM_CLIE || '|' || 
CASE T.CD_TP_IDENTF_CLIE  
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 10, 2)  
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T.CD_DOC_IDENTF_CLIE, 13, 2)   
	ELSE T.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Mês/Ano: ' || SUBSTR(:cd_lote,5,2) || '/' || SUBSTR(:cd_lote,1,4) ||  '|' ||  
'Avaliação: Cliente com histórico de envio de informação ao COAF. |'  
AS DS_INF_ANLSE   
FROM TB_CAD_CLIE T    
WHERE EXISTS (SELECT 1 FROM TB_TRANS C 
WHERE DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
  AND DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
  AND C.FL_ANALISADO = 1 AND T.CD_DOC_IDENTF_CLIE = C.CD_DOC_IDENTF_CLIE AND T.CD_TP_IDENTF_CLIE = C.CD_TP_IDENTF_CLIE) 
  AND T.FL_INFO_COAF IS NOT NULL  
  AND T.FL_INFO_COAF = 1 
  