/* REGRA 212 */ 
SELECT  T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: 212 – Saques em espécie fracionados, no último mês calendário fechado. |' ||    
'Objetivo: Verificar valores incompatíveis de saques em espécie fracionados, no último mês calendário fechado, com a renda ou faturamento do cliente, por faixas. |' ||    
'Conclusão: Saques em espécie fracionados, no último mês calendário fechado. Cliente com renda baixa.  |' ||    
'Cliente: ' ||  T1.NM_CLIE || '|' ||   
'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)    
|| '|' ||    
'Mês/Ano Calendário: ' || SUBSTR(:cd_lote,5,2) || '/' || SUBSTR(:cd_lote,1,4) ||  '|' ||   
'Renda:' || COALESCE(TO_CHAR(VL_RENDA_FAT, 'L999G999G999G990D99'),'Renda não informado')  ||  '|' ||    
'Valor consolidado de Saques em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(VL_CONS, 'L999G999G999G990D99')  ||  '|' ||   
'Quantidade consolidada de Saques em Espécie, por cliente, no mês último mês calendário fechado:' || TO_CHAR(QT_CONS, '999999990')  ||  '|' ||   
'Parâmetro que indica o limite para que uma renda possa ser considerada baixa (pm_ValorRendaBaixa):' || (SELECT TO_CHAR(:pm_ValorRendaBaixa, 'L999G999G999G990D99') FROM DUAL) ||  '|' || 
'Parâmetro que indica quantidade expressiva de saques em espécie, para renda baixa, no último mês calendário fechado, para pessoa física (pm_QtdeSaqEspecieRendaBaixa):' || (SELECT TO_CHAR(:pm_QtdeSaqEspecieRendaBaixa, '999999990') FROM DUAL) ||  '|' || 
'Parâmetro que indica valor expressivo de saques em espécie, para renda baixa, no último mês calendário fechado, para pessoa física (pm_ValorSaqEspecieRendaBaixa):' || (SELECT TO_CHAR(:pm_ValorSaqEspecieRendaBaixa, 'L999G999G999G990D99') FROM DUAL) 
AS DS_INF_ANLSE     
FROM  
(SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO, MAX(T.NM_CLIE) NM_CLIE, MAX(VL_RENDA_FAT) VL_RENDA_FAT, SUM(VL_OPER) VL_CONS, COUNT(*) QT_CONS 
 FROM TB_TRANS T 
 WHERE T.CD_TP_PESSOA  = 'F' 
   AND T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
   AND T.FL_ANALISADO = 1
   AND T.CD_TP_OPER    = 7 /*Saques*/ 
   AND T.CD_FORMA_OPER = 7 /*especie*/    
   AND ((T.VL_RENDA_FAT IS NOT NULL AND T.VL_RENDA_FAT <= (:pm_ValorRendaBaixa)) 
        OR 
        T.VL_RENDA_FAT IS NULL) 
   GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO    
   ) T1    
WHERE T1.QT_CONS >= (:pm_QtdeSaqEspecieRendaBaixa) 
  AND T1.VL_CONS >=  (:pm_ValorSaqEspecieRendaBaixa) 
 
UNION ALL 
 
SELECT  T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: 212 – Saques em espécie fracionados, no último mês calendário fechado. |' ||    
'Objetivo: Verificar valores incompatíveis de saques em espécie fracionados, no último mês calendário fechado, com a renda ou faturamento do cliente, por faixas. |' ||    
'Conclusão: Saques em espécie fracionados, no último mês calendário fechado. Cliente com renda alta.  |' ||    
'Cliente: ' ||  T1.NM_CLIE || '|' ||   
'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)    
|| '|' ||    
'Mês/Ano Calendário: ' || SUBSTR(:cd_lote,5,2) || '/' || SUBSTR(:cd_lote,1,4) ||  '|' ||   
'Renda:' || COALESCE(TO_CHAR(VL_RENDA_FAT, 'L999G999G999G990D99'),'Renda não informada')  ||  '|' ||    
'Valor consolidado de Saques em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(VL_CONS, 'L999G999G999G990D99')  ||  '|' ||   
'Quantidade consolidada de Saques em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(QT_CONS, '999999990')  ||  '|' ||   
'Parâmetro que indica o limite para que uma renda possa ser considerada baixa (pm_ValorRendaBaixa):' || (SELECT TO_CHAR(:pm_ValorRendaBaixa, 'L999G999G999G990D99') FROM DUAL) ||  '|' || 
'Parâmetro percentual para flexibilização de renda alta (pm_PercRendaAlta):' || (SELECT TO_CHAR(:pm_PercRendaAlta, '999999990D99') FROM DUAL) ||  '|' || 
'Parâmetro que indica quantidade expressiva de saques em espécie, para renda alta, no último mês calendário fechado, para pessoa física (pm_QtdeSaqEspecieRendaAlta):' || (SELECT TO_CHAR(:pm_QtdeSaqEspecieRendaAlta, '999999990') FROM DUAL) ||  '|' || 
'Parâmetro que indica valor expressivo de saques em espécie, para renda alta, no último mês calendário fechado, para pessoa física (pm_ValorSaqEspecieRendaAlta):' || (SELECT TO_CHAR(:pm_ValorSaqEspecieRendaAlta, 'L999G999G999G990D99') FROM DUAL)  
AS DS_INF_ANLSE     
FROM  
(SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO, MAX(T.NM_CLIE) NM_CLIE, MAX(VL_RENDA_FAT) VL_RENDA_FAT, SUM(VL_OPER) VL_CONS, COUNT(*) QT_CONS 
 FROM TB_TRANS T 
 WHERE T.CD_TP_PESSOA  = 'F' 
   AND T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
   AND T.FL_ANALISADO = 1
   AND T.CD_TP_OPER    = 7 /*Saques*/ 
   AND T.CD_FORMA_OPER = 7 /*especie*/    
   AND (T.VL_RENDA_FAT IS NOT NULL AND T.VL_RENDA_FAT > (:pm_ValorRendaBaixa)) 
  GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO    
   ) T1    
WHERE T1.QT_CONS >= (:pm_QtdeSaqEspecieRendaAlta) 
  AND T1.VL_CONS >= (:pm_ValorSaqEspecieRendaAlta) 
  AND T1.VL_CONS >= (T1.VL_RENDA_FAT * (:pm_PercRendaAlta/100)) 
 
UNION ALL 
 
SELECT  T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: 212 – Saques em espécie fracionados, no último mês calendário fechado. |' ||    
'Objetivo: Verificar valores incompatíveis de saques em espécie fracionados, no último mês calendário fechado, com a renda ou faturamento do cliente, por faixas. |' ||    
'Conclusão: Saques em espécie fracionados, no último mês calendário fechado. Cliente com faturamento baixo.  |' ||    
'Cliente: ' ||  T1.NM_CLIE || '|' ||   
'Tipo de Pessoa Jurídica (CNPJ): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)     
|| '|' ||    
'Mês/Ano Calendário: ' || SUBSTR(:cd_lote,5,2) || '/' || SUBSTR(:cd_lote,1,4) ||  '|' ||   
'Faturamento:' || COALESCE(TO_CHAR(VL_RENDA_FAT, 'L999G999G999G990D99'),'Faturamento não informado')  ||  '|' ||    
'Quantidade consolidada de Saques em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(QT_CONS, '999999990')  ||  '|' ||   
'Valor consolidado de Saques em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(VL_CONS, 'L999G999G999G990D99')  ||  '|' ||   
'Parâmetro que indica o limite para que um faturamento possa ser considerado baixo (pm_ValorFaturamentoBaixo):' || (SELECT TO_CHAR(:pm_ValorFaturamentoBaixo, 'L999G999G999G990D99') FROM DUAL) ||  '|' || 
'Parâmetro que indica quantidade expressiva de saques em espécie, para faturamento baixo, no último mês calendário fechado, para pessoa jurídica (pm_QtdeSaqEspecieFatBaixo):' || (SELECT TO_CHAR(:pm_QtdeSaqEspecieFatBaixo, '999999990') FROM DUAL) ||  '|' || 
'Parâmetro que indica valor expressivo de saques em espécie, para faturamento baixo, no último mês calendário fechado, para pessoa jurídica (pm_ValorSaqEspecieFatBaixo):' || (SELECT TO_CHAR(:pm_ValorSaqEspecieFatBaixo, 'L999G999G999G990D99') FROM DUAL) 
AS DS_INF_ANLSE     
FROM  
(SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO, MAX(T.NM_CLIE) NM_CLIE, MAX(VL_RENDA_FAT) VL_RENDA_FAT, SUM(VL_OPER) VL_CONS, COUNT(*) QT_CONS 
 FROM TB_TRANS T 
 WHERE T.CD_TP_PESSOA  = 'J' 
   AND T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)  
   AND T.FL_ANALISADO  = 1
   AND T.CD_TP_OPER    = 7 /*Saques*/ 
   AND T.CD_FORMA_OPER = 7 /*especie*/    
   AND ((T.VL_RENDA_FAT IS NOT NULL AND T.VL_RENDA_FAT <= (:pm_ValorFaturamentoBaixo)) 
        OR 
        T.VL_RENDA_FAT IS NULL) 
   GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO    
   ) T1    
WHERE T1.QT_CONS >= (:pm_QtdeSaqEspecieFatBaixo) 
  AND T1.VL_CONS >=  (:pm_ValorSaqEspecieFatBaixo) 
   
UNION ALL 
 
SELECT  T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,     
'Análise: 212 – Saques em espécie fracionados, no último mês calendário fechado. |' ||    
'Objetivo: Verificar valores incompatíveis de saques em espécie fracionados, no último mês calendário fechado, com a renda ou faturamento do cliente, por faixas. |' ||    
'Conclusão: Saques em espécie fracionados, no último mês calendário fechado. Cliente com faturamento alto.  |' ||    
'Cliente: ' ||  T1.NM_CLIE || '|' ||   
'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)     
|| '|' ||    
'Mês/Ano Calendário: ' || SUBSTR(:cd_lote,5,2) || '/' || SUBSTR(:cd_lote,1,4) ||  '|' ||   
'Faturamento:' || COALESCE(TO_CHAR(VL_RENDA_FAT, 'L999G999G999G990D99'),'Faturamento não informado')  ||  '|' ||    
'Valor consolidado de Saques em Espécie, por cliente, no último mês calendário fechado:' || TO_CHAR(VL_CONS, 'L999G999G999G990D99')  ||  '|' ||   
'Quantidade consolidada de Saques em Espécie, por Cliente, no último mês calendário fechado:' || TO_CHAR(QT_CONS, '999999990')  ||  '|' ||   
'Parâmetro que indica o limite para que um faturamento possa ser considerado baixo (pm_ValorFaturamentoBaixo):' || (SELECT TO_CHAR(:pm_ValorFaturamentoBaixo, 'L999G999G999G990D99') FROM DUAL) ||  '|' || 
'Parâmetro percentual para flexibilização de faturamento alto (pm_PercFaturamentoAlto):' || (SELECT TO_CHAR(:pm_PercFaturamentoAlto, '999999990D99') FROM DUAL) ||  '|' || 
'Parâmetro que indica quantidade expressiva de saques em espécie, para faturamento alto, no último mês calendário fechado, para pessoa jurídica. (pm_QtdeSaqEspecieFatAlto):' || (SELECT TO_CHAR(:pm_QtdeSaqEspecieFatAlto, '999999990') FROM DUAL) ||  '|' || 
'Parâmetro que indica valor expressivo de saques em espécie, para faturamento alto, no último mês calendário fechado, para pessoa jurídica (pm_ValorSaqEspecieFatAlto):' || (SELECT TO_CHAR(:pm_ValorSaqEspecieFatAlto, 'L999G999G999G990D99') FROM DUAL) 
AS DS_INF_ANLSE     
FROM  
(SELECT T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO, MAX(T.NM_CLIE) NM_CLIE, MAX(VL_RENDA_FAT) VL_RENDA_FAT, SUM(VL_OPER) VL_CONS, COUNT(*) QT_CONS 
 FROM TB_TRANS T 
 WHERE T.CD_TP_PESSOA  = 'J' 
   AND T.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
   AND T.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
   AND T.FL_ANALISADO  = 1
   AND T.CD_TP_OPER    = 7 /*Saques*/ 
   AND T.CD_FORMA_OPER = 7 /*especie*/    
   AND (T.VL_RENDA_FAT IS NOT NULL AND T.VL_RENDA_FAT > (:pm_ValorFaturamentoBaixo)) 
  GROUP BY T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_MES_ANO    
   ) T1    
WHERE T1.QT_CONS >= (:pm_QtdeSaqEspecieFatAlto) 
  AND T1.VL_CONS >= (:pm_ValorSaqEspecieFatAlto) 
  AND T1.VL_CONS >= (T1.VL_RENDA_FAT * (:pm_PercFaturamentoAlto/100)) 
 
  
   
