SELECT DISTINCT T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,    
'Análise: Regra 55 – Movimentação em conta incompatível com o porte declarado |' ||   
'Objetivo: Verificar se a movimentação em conta da empresa está de acordo com o porte declarado |' ||   
'Conclusão: A movimentação em conta da empresa não está de acordo com o porte declarado |' ||   
'Cliente: ' ||  MAX(T1.NM_CLIE) || '|' ||  
CASE T1.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T1.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||   
'Porte: MicroEmpresa' || '|' ||   
'Mês/Ano: ' || SUBSTR(T1.CD_MES_ANO,5,2) || '/' || SUBSTR(T1.CD_MES_ANO,1,4) ||  '|' ||   
'Valor total de crédito no mês: ' || TO_CHAR(SUM(VL_OPER), 'L999G999G999G990D99') ||  '|' || 
'Parâmetro que indica o valor limite de faturamento para empresas ME em 12 meses (pm_valorLimiteME): ' || COALESCE((SELECT TO_CHAR(:pm_valorLimiteME, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||   
'Parametro percentual de flexibilização da movimentação de crédito para ME (pm_percMovCredME): ' || COALESCE((SELECT TO_CHAR(:pm_percMovCredME, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'   
AS DS_INF_ANLSE    
FROM TB_TRANS T1   
WHERE T1.CD_NATUR_OPER = 1   
  AND T1.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
  AND T1.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
  AND T1.FL_ANALISADO = 1
  AND T1.CD_TP_PESSOA = 'J'   
  AND T1.VL_OPER IS NOT NULL    
  AND T1.CD_PORTE = 4   
  HAVING (SUM(VL_OPER) > (    
     (:pm_valorLimiteME/12) *   
     (:pm_percMovCredME/100)))          
GROUP BY T1.CD_MES_ANO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE         
 
UNION ALL 
SELECT DISTINCT T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,    
'Análise: Regra 55 – Movimentação em conta incompatível com o porte declarado |' ||   
'Objetivo: Verificar se a movimentação em conta da empresa está de acordo com o porte declarado |' ||   
'Conclusão: A movimentação em conta da empresa não está de acordo com o porte declarado |' ||   
'Cliente: ' ||  MAX(T1.NM_CLIE) || '|' ||  
CASE T1.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T1.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||   
'Porte: Pequena Empresa' || '|' ||   
'Mês/Ano: ' || SUBSTR(T1.CD_MES_ANO,5,2) || '/' || SUBSTR(T1.CD_MES_ANO,1,4) ||  '|' ||   
'Valor total de crédito no mês: ' || TO_CHAR(SUM(VL_OPER), 'L999G999G999G990D99') ||  '|' || 
'Parâmetro que indica o valor limite de faturamento para empresas de pequeno porte em 12 meses (pm_valorLimiteEPP): ' || COALESCE((SELECT TO_CHAR(:pm_valorLimiteEPP, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||   
'Parâmetro percentual de flexibilização da movimentação de crédito para empresas de pequeno porte (pm_percMovCredEPP): ' || COALESCE((SELECT TO_CHAR(:pm_percMovCredEPP, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'   
AS DS_INF_ANLSE    
FROM TB_TRANS T1   
WHERE T1.CD_NATUR_OPER = 1   
  AND T1.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
  AND T1.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)
  AND T1.FL_ANALISADO = 1
  AND T1.CD_TP_PESSOA = 'J'   
  AND T1.VL_OPER IS NOT NULL    
  AND T1.CD_PORTE = 3   
  GROUP BY T1.CD_MES_ANO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE 
  HAVING (SUM(VL_OPER) > (    
          (:pm_valorLimiteEPP/12) *   
          (:pm_percMovCredEPP/100)))      
 
 
UNION ALL 
SELECT DISTINCT T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE,    
'Análise: Regra 55 – Movimentação em conta incompatível com o porte declarado |' ||   
'Objetivo: Verificar se a movimentação em conta da empresa está de acordo com o porte declarado |' ||   
'Conclusão: A movimentação em conta da empresa não está de acordo com o porte declarado |' ||   
'Cliente: ' ||  MAX(T1.NM_CLIE) || '|' ||  
CASE T1.CD_TP_IDENTF_CLIE   
	WHEN 2 THEN 'Tipo de Pessoa Física (CPF): ' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 10, 2)   
	WHEN 3 THEN 'Tipo de Pessoa Jurídica (CNPJ): ' ||SUBSTR(T1.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(T1.CD_DOC_IDENTF_CLIE, 13, 2)    
	ELSE T1.CD_DOC_IDENTF_CLIE   
END   
|| '|' ||   
'Porte: Média Empresa' || '|' ||   
'Mês/Ano: ' || SUBSTR(T1.CD_MES_ANO,5,2) || '/' || SUBSTR(T1.CD_MES_ANO,1,4) ||  '|' ||   
'Valor total de crédito no mês: ' || TO_CHAR(SUM(VL_OPER), 'L999G999G999G990D99') ||  '|' || 
'Parâmetro que indica o valor limite de faturamento para empresas de médio porte em 12 meses (pm_valorLimiteEPM): ' || COALESCE((SELECT TO_CHAR(:pm_valorLimiteEPM, 'L999G999G999G990D99') FROM DUAL),'Parâmetro não cadastrado') || '|' ||   
'Parâmetro percentual de flexibilização da movimentação de crédito para empresas de médio porte (pm_percMovCredEPM): ' || COALESCE((SELECT TO_CHAR(:pm_percMovCredEPM, '999999990D99') FROM DUAL),'Parâmetro não cadastrado') || '|'   
AS DS_INF_ANLSE    
FROM TB_TRANS T1   
WHERE T1.CD_NATUR_OPER = 1   
  AND T1.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
  AND T1.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1) 
  AND T1.FL_ANALISADO = 1
  AND T1.CD_TP_PESSOA = 'J'   
  AND T1.VL_OPER IS NOT NULL    
  AND T1.CD_PORTE = 2   
  GROUP BY T1.CD_MES_ANO, T1.CD_DOC_IDENTF_CLIE, T1.CD_TP_IDENTF_CLIE  
  HAVING (SUM(VL_OPER) > (    
               (:pm_valorLimiteEPM/12) *   
               (:pm_percMovCredEPM/100)))   

