SELECT O.CD_DOC_IDENTF_CLIE, O.CD_TP_IDENTF_CLIE,    
'Análise: Regra 46 – Mesmos Procuradores ou Representantes |' ||  
'Objetivo: Diferentes Pessoas Jurídicas ou Organizações representadas pelos mesmos procuradores ou representantes legais, sem justificativa razoável para tal. CNPJs de diferentes grupos econômicos onde o CPF do representante é o mesmo |' ||  
'Conclusão: Diferentes Pessoas Jurídicas ou Organizações representadas pelos mesmos procuradores ou representantes legais, sem justificativa razoável para tal |' ||  
'Cliente: ' || COALESCE(O.NM_CLIE, 'Nome não cadastrado') || '|' ||  
CASE O.CD_TP_IDENTF_CLIE  
	 WHEN 2 THEN 'CPF Cliente: ' || SUBSTR(O.CD_DOC_IDENTF_CLIE, 1, 3) || '.' || SUBSTR(O.CD_DOC_IDENTF_CLIE, 4, 3) || '.' || SUBSTR(O.CD_DOC_IDENTF_CLIE, 7, 3) || '-' || SUBSTR(O.CD_DOC_IDENTF_CLIE, 10, 2)  
	 WHEN 3 THEN 'CNPJ Cliente: ' ||SUBSTR(O.CD_DOC_IDENTF_CLIE, 1, 2) || '.' || SUBSTR(O.CD_DOC_IDENTF_CLIE, 3, 3) || '.' || SUBSTR(O.CD_DOC_IDENTF_CLIE, 6, 3) || '/' || SUBSTR(O.CD_DOC_IDENTF_CLIE, 9, 4) || '-'  || SUBSTR(O.CD_DOC_IDENTF_CLIE, 13, 2)   
	 ELSE O.CD_DOC_IDENTF_CLIE  
END  
|| '|' ||  
'Mês/Ano: ' || SUBSTR(:cd_lote, 5, 2)  || '/' || SUBSTR(:cd_lote, 1, 4)  ||  '|' ||  
'Representante: ' || COALESCE(O.NM_REPRE, 'Nome não cadastrado') || '|' ||  
CASE CD_TP_IDENTF_REPRE  
	 WHEN 2 THEN 'CPF Representante: ' || SUBSTR(CD_DOC_IDENTF_REPRE, 1, 3) || '.' || SUBSTR(CD_DOC_IDENTF_REPRE, 4, 3) || '.' || SUBSTR(CD_DOC_IDENTF_REPRE, 7, 3) || '-' || SUBSTR(CD_DOC_IDENTF_REPRE, 10, 2)  
	 WHEN 3 THEN 'CNPJ Representante: ' ||SUBSTR(CD_DOC_IDENTF_REPRE, 1, 2) || '.' || SUBSTR(CD_DOC_IDENTF_REPRE, 3, 3) || '.' || SUBSTR(CD_DOC_IDENTF_REPRE, 6, 3) || '/' || SUBSTR(CD_DOC_IDENTF_REPRE, 9, 4) || '-'  || SUBSTR(CD_DOC_IDENTF_REPRE, 13, 2)   
	 ELSE CD_DOC_IDENTF_REPRE  
END  
|| '|' ||  
'Grupo financeiro do cliente: ' || (GRP_CLIE) || (SELECT ' ' || NM_GRP_FINANC FROM TB_GRP_FINANC WHERE O.GRP_CLIE = cast(CD_GRP_FINANC as varchar(20))) || '|' ||  
'Quantidade de representações (grupos distintos) da pessoa que representa o cliente em análise, desde que as empresas representadas não pertençam ao mesmo grupo financeiro: ' || TO_CHAR(O.QtdeRepresentacao) || '|' ||  
'Grupos considerados: ' || Grupos2 || '|' ||  
'Parâmetro que indica a quantidade mínima de representação, a partir da qual é considerada expressiva (pm_QtdeRepresentacao): ' || COALESCE((':pm_QtdeRepresentacao'),'Parâmetro não cadastrado') || '|'   
AS DS_INF_ANLSE    
FROM (SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, GRP_CLIE, CD_DOC_IDENTF_REPRE, CD_TP_IDENTF_REPRE, NM_REPRE,  
      listagg(case when GRUPO LIKE '%NULO%' THEN 'NULO' ELSE GRUPO END ,', ') within GROUP(ORDER BY GRUPO)  grupos2, 
      COUNT(*) QtdeRepresentacao 
      FROM (SELECT CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, CD_DOC_IDENTF_REPRE, CD_TP_IDENTF_REPRE, NM_REPRE, GRP_CLIE,  
            grupo || (SELECT '-' || NM_GRP_FINANC FROM TB_GRP_FINANC WHERE grupo = CAST(CD_GRP_FINANC AS VARCHAR(20))) grupo 
            FROM (SELECT R.CD_DOC_IDENTF_REPRE, R.CD_TP_IDENTF_REPRE, R.CD_DOC_IDENTF_CLIE, R.CD_TP_IDENTF_CLIE, R.NM_CLIE, R.NM_REPRE, R.GRP_CLIE, X.CD_DOC_IDENTF_CLIE REPRE, X.CD_TP_IDENTF_CLIE TP_REPRE,  
                  CASE WHEN CAST(X.CD_GRP_FINANC AS VARCHAR(20))  IS NULL THEN 'NULO' || X.CD_DOC_IDENTF_CLIE ELSE CAST(X.CD_GRP_FINANC AS VARCHAR(20)) END GRUPO 
                  FROM (SELECT CD_DOC_IDENTF_REPRE, CD_TP_IDENTF_REPRE, CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, NM_REPRE,  
                        CASE WHEN CAST(CD_GRP_FINANC AS VARCHAR(20)) IS NULL THEN 'NULO' ELSE CAST(CD_GRP_FINANC AS VARCHAR(20)) END GRP_CLIE 
                        FROM TB_TRANSMISSAO_ORDEM T  
                        WHERE  EXISTS (SELECT 1 FROM TB_TRANS C   
                                       WHERE C.CD_DOC_IDENTF_CLIE= T.CD_DOC_IDENTF_CLIE   
                                       AND C.CD_TP_IDENTF_CLIE   = T.CD_TP_IDENTF_CLIE  
                                       AND C.CD_TP_PESSOA = 'J'  
                                       AND C.DT_TRANS >=  to_date(to_char(:cd_lote), 'yyyy/mm')  
                                       AND C.DT_TRANS < add_months((to_date(to_char(:cd_lote), 'yyyy/mm')), 1)      
                                       AND C.FL_ANALISADO = 1    
                                      )  
                       ) R  
                       INNER JOIN   
                       (SELECT T.CD_DOC_IDENTF_REPRE, T.CD_TP_IDENTF_REPRE, T.CD_DOC_IDENTF_CLIE, T.CD_TP_IDENTF_CLIE, T.CD_GRP_FINANC  
                        FROM TB_TRANSMISSAO_ORDEM T 
                        WHERE T.CD_TP_IDENTF_CLIE = 3 ) X  
                       ON R.CD_DOC_IDENTF_REPRE = X.CD_DOC_IDENTF_REPRE AND X.CD_DOC_IDENTF_CLIE <> R.CD_DOC_IDENTF_CLIE  
                ) A  
                WHERE A.GRP_CLIE <> GRUPO 
                GROUP BY CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, CD_DOC_IDENTF_REPRE, CD_TP_IDENTF_REPRE, NM_REPRE, GRP_CLIE, GRUPO 
            ) I 
            GROUP BY CD_DOC_IDENTF_CLIE, CD_TP_IDENTF_CLIE, NM_CLIE, GRP_CLIE, CD_DOC_IDENTF_REPRE, CD_TP_IDENTF_REPRE, NM_REPRE 
          ) O 
          WHERE QtdeRepresentacao > (:pm_QtdeRepresentacao)  
        